#pragma once
/**
 * Generated by executorch/kernels/prim_ops/selective_build_prim_ops.h
 * This header conditionally includes selected_prim_ops.h when selective build
 * for prim ops is enabled.
 */

// If no prim ops are selected, then the header is empty.
// that would mean all prim ops are enabled.
#ifdef ET_PRIM_OPS_SELECTIVE_BUILD
#include "selected_prim_ops.h"
#endif
