load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")

oncall("executorch")

non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/extension/flat_tensor/serialize/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "schema",
    srcs = [
        "flat_tensor_schema.py",
    ],
    visibility = [
        "//executorch/...",
    ],
    deps = [
        "//executorch/exir:tensor_layout",
    ]
)

fbcode_target(_kind = runtime.python_library,
    name = "serialize",
    srcs = [
        "serialize.py",
    ],
    resources = [
        "flat_tensor.fbs",
        "scalar_type.fbs",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":schema",
        "//executorch/exir/_serialize:lib",
    ],
)
