load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load(":targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/backends/xnnpack/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_preprocess",
    srcs = [
        "xnnpack_preprocess.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/backends/transforms:lib",
        "//executorch/backends/transforms:remove_getitem_op",
        "//executorch/backends/xnnpack/_passes:xnnpack_passes",
        "//executorch/backends/xnnpack/operators:operators",
        "//executorch/backends/xnnpack/serialization:xnnpack_serializer",
        "//executorch/exir:graph_module",
        "//executorch/exir/backend:backend_details",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_delegate",
    srcs = [
        "__init__.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":xnnpack_preprocess",
        "//executorch/backends/xnnpack/partition:xnnpack_partitioner",
        "//executorch/backends/xnnpack/utils:xnnpack_utils",
    ],
)
