load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load("@fbcode//tools/build/buck:nvcc_flags.bzl", "get_nvcc_arch_args")

oncall("executorch")

fbcode_target(_kind = runtime.cxx_library,
    name = "cuda_platform",
    srcs = [
        "platform/platform.cpp",
    ],
    headers = [
        "platform/platform.h",
    ],
    # @lint-ignore BUCKLINT: Avoid `link_whole=True` (https://fburl.com/avoid-link-whole)
    link_whole = True,
    supports_python_dlopen = True,
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/runtime/core:core",
    ],
    nvcc_flags = get_nvcc_arch_args() + [
        "-_NVCC_HOST_COMPILER_FLAG_",
        "gcc",
    ],
    external_deps = [
        ("cuda", None, "cuda-lazy"),
    ],
)

fbcode_target(_kind = runtime.cxx_library,
    name = "tensor_maker",
    srcs = [
        "tensor/tensor_maker.cpp",
    ],
    headers = [
        "tensor/tensor_maker.h",
    ],
    # @lint-ignore BUCKLINT: Avoid `link_whole=True` (https://fburl.com/avoid-link-whole)
    link_whole = True,
    supports_python_dlopen = True,
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/runtime/core:core",
        "//executorch/runtime/core/exec_aten:lib",
        "//executorch/runtime/core/exec_aten/util:tensor_util",
    ],
)

fbcode_target(_kind = runtime.cxx_library,
    name = "runtime_shims",
    srcs = [
        "guard.cpp",
        "shims/cuda_guard.cpp",
        "shims/int4mm.cu",
        "shims/memory.cpp",
        "shims/tensor_attribute.cpp",
    ],
    headers = [
        "guard.h",
        "shims/cuda_guard.h",
        "shims/int4mm.cuh",
        "shims/int4mm.h",
        "shims/memory.h",
        "shims/tensor_attribute.h",
        "utils.h",
    ],
    # @lint-ignore BUCKLINT: Avoid `link_whole=True` (https://fburl.com/avoid-link-whole)
    link_whole = True,
    supports_python_dlopen = True,
    # Constructor needed for backend registration.
    compiler_flags = ["-Wno-global-constructors"],
    visibility = ["PUBLIC"],
    deps = [
        ":tensor_maker",
        "//executorch/backends/aoti:common_shims",
        "//executorch/runtime/core:core",
        "//executorch/runtime/core/exec_aten:lib",
        "//executorch/runtime/platform:platform",
        "//executorch/backends/cuda/runtime:cuda_platform",
    ],
    nvcc_flags = get_nvcc_arch_args() + [
        "-_NVCC_HOST_COMPILER_FLAG_",
        "gcc",
    ],
    external_deps = [
        ("cuda", None, "cuda-lazy"),
    ],
)

fbcode_target(_kind = runtime.cxx_library,
    name = "cuda_backend",
    srcs = [
        "cuda_backend.cpp",
    ],
    # @lint-ignore BUCKLINT: Avoid `link_whole=True` (https://fburl.com/avoid-link-whole)
    link_whole = True,
    supports_python_dlopen = True,
    # Constructor needed for backend registration.
    compiler_flags = ["-Wno-global-constructors"],
    visibility = ["PUBLIC"],
    deps = [
        ":runtime_shims",
        "//executorch/backends/aoti:aoti_common",
        "//executorch/runtime/backend:interface",
        "//executorch/runtime/core/exec_aten/util:tensor_util",
    ],
    external_deps = [
        ("cuda", None, "cuda-lazy"),
    ],
)
