load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "gemma4",
    srcs = [
        "__init__.py",
        "convert_weights.py",
    ],
    base_module = "executorch.examples.models.gemma4",
    resources = {
        "config/e2b_config.json": "config/e2b_config.json",
        "config/e4b_config.json": "config/e4b_config.json",
    },
    deps = [
        "//caffe2:torch",
        "//executorch/examples/models/llama:llama2_model",
        "//executorch/examples/models:checkpoint",
        "fbsource//third-party/pypi/safetensors:safetensors",
    ],
    visibility = ["PUBLIC"],
)
