load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_library,
    name = "operator_support",
    srcs = glob(["*.py"]),
    deps = [
        "//executorch/backends/arm:constants",
        "//executorch/backends/arm/_passes:passes",
        "//executorch/backends/arm/tosa:tosa",
        "//executorch/backends/transforms:remove_getitem_op",
        "//executorch/backends/xnnpack/_passes:xnnpack_passes",
        "//executorch/exir:lib",
    ],
)
