#!/bin/bash
# Copyright (c) 2026 iote.ai
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# One-shot setup of the Python environment for model export.
#
# Model export (PyTorch → ExecuTorch → AXON) and firmware build
# (Zephyr + west) use DIFFERENT Python environments:
#
#   - Model export needs PyTorch, ExecuTorch, tosa-tools — large ML
#     packages that are not part of the NCS toolchain.
#
#   - Firmware build uses the NCS toolchain Python, which provides
#     west, Zephyr cmake modules, and the ARM cross-compiler. The NCS
#     toolchain sets PYTHONHOME and PYTHONPATH to point at its own
#     Python 3.12, which breaks imports for any other Python.
#
# This script creates an isolated .venv/ in this directory with the
# export dependencies. It does NOT affect the NCS toolchain or any
# other Python environment on the system. The generated run_export.sh
# wrapper unsets PYTHONHOME/PYTHONPATH before running, so it works
# even if you previously sourced nrf-connect-sdk-env.sh.
#
# ExecuTorch itself is NOT pip-installed (its setup.py triggers a
# heavy cmake build). Instead, ExecuTorch's Python source tree is
# added to PYTHONPATH at runtime — this is sufficient for the export
# pipeline which only uses the Python backend code, not the C++ runtime.
#
# Prerequisites: uv (install with: pip install uv)
#
# Usage:
#   cd examples/nordic/hello_axon
#   ./setup_export_env.sh
#   SDK_EDGE_AI_PATH=~/sdk-edge-ai ./run_export.sh

set -e

# Unset the NCS toolchain's Python environment variables. The NCS
# toolchain (activated by sourcing nrf-connect-sdk-env.sh) sets these
# to point at its bundled Python 3.12. If left set, uv would try to
# use the NCS Python's stdlib, causing "SRE module mismatch" errors
# because uv's Python (3.13) and NCS's stdlib (3.12) are incompatible.
unset PYTHONHOME
unset PYTHONPATH

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ET_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "=== Setting up hello_axon export environment ==="
echo "  Directory:  $SCRIPT_DIR"
echo "  ExecuTorch: $ET_ROOT"

# Check uv
if ! command -v uv &>/dev/null; then
    echo "ERROR: 'uv' not found. Install with: pip install uv"
    exit 1
fi

cd "$SCRIPT_DIR"

# Create venv and install base deps from pyproject.toml
echo ""
echo "--- Creating venv and installing base dependencies ---"
uv sync

# Install torch (CPU variant) — needed by ExecuTorch and the export pipeline
echo ""
echo "--- Installing PyTorch (CPU) ---"
uv pip install torch --index-url https://download.pytorch.org/whl/cpu

# Install ExecuTorch Python packages.
# We DON'T do `pip install -e` (which triggers a heavy cmake build).
# Instead, we install the Python-only dependencies and add ExecuTorch
# to the path at runtime via PYTHONPATH.
echo ""
echo "--- Installing ExecuTorch dependencies ---"
uv pip install setuptools flatbuffers packaging "ruamel.yaml" tabulate

# Install tosa-tools and torchao
echo ""
echo "--- Installing tosa-tools and torchao ---"
uv pip install tosa-tools torchao

# Create a wrapper script that sets PYTHONPATH for export
cat > "$SCRIPT_DIR/run_export.sh" << 'WRAPPER'
#!/bin/bash
# Auto-generated by setup_export_env.sh
#
# Runs export_model.py in the isolated .venv with the correct PYTHONPATH.
# Safe to run even if nrf-connect-sdk-env.sh was sourced in this shell —
# we unset PYTHONHOME/PYTHONPATH to avoid NCS toolchain conflicts.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ET_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
# Clear NCS Python env (PYTHONHOME would redirect stdlib to NCS's Python 3.12)
unset PYTHONHOME
unset PYTHONPATH
# Add ExecuTorch Python source to the path (not pip-installed, see README)
export PYTHONPATH="${ET_ROOT}/src"
exec uv run --directory "$SCRIPT_DIR" python "$SCRIPT_DIR/export_model.py" "$@"
WRAPPER
chmod +x "$SCRIPT_DIR/run_export.sh"

# Verify
echo ""
echo "--- Verifying installation ---"
PYTHONPATH="${ET_ROOT}/src" uv run python -c "
from executorch.backends.nordic.axon import AxonBackend, AxonQuantizer
print('  ExecuTorch AXON backend: OK')
import tosa
print('  tosa-tools: OK')
import torch
print(f'  PyTorch: {torch.__version__}')
print('Setup complete.')
"

echo ""
echo "=== Done ==="
echo ""
echo "Export a model with:"
echo "  cd $SCRIPT_DIR"
echo "  SDK_EDGE_AI_PATH=~/sdk-edge-ai ./run_export.sh"
