# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class StablehloBroadcastInDimOptions(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StablehloBroadcastInDimOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStablehloBroadcastInDimOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def StablehloBroadcastInDimOptionsBufferHasIdentifier(
        cls, buf, offset, size_prefixed=False
    ):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed
        )

    # StablehloBroadcastInDimOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StablehloBroadcastInDimOptions
    def BroadcastDimensions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Int64Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8),
            )
        return 0

    # StablehloBroadcastInDimOptions
    def BroadcastDimensionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # StablehloBroadcastInDimOptions
    def BroadcastDimensionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StablehloBroadcastInDimOptions
    def BroadcastDimensionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def StablehloBroadcastInDimOptionsStart(builder):
    builder.StartObject(1)


def Start(builder):
    StablehloBroadcastInDimOptionsStart(builder)


def StablehloBroadcastInDimOptionsAddBroadcastDimensions(builder, broadcastDimensions):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(broadcastDimensions), 0
    )


def AddBroadcastDimensions(builder, broadcastDimensions):
    StablehloBroadcastInDimOptionsAddBroadcastDimensions(builder, broadcastDimensions)


def StablehloBroadcastInDimOptionsStartBroadcastDimensionsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)


def StartBroadcastDimensionsVector(builder, numElems: int) -> int:
    return StablehloBroadcastInDimOptionsStartBroadcastDimensionsVector(
        builder, numElems
    )


def StablehloBroadcastInDimOptionsEnd(builder):
    return builder.EndObject()


def End(builder):
    return StablehloBroadcastInDimOptionsEnd(builder)
