#
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# ============================================================================
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# ============================================================================
#
# This file was generated from schema.fbs by the MLX delegate code generator.
#
# Source:    backends/mlx/serialization/schema.fbs
# Generator: backends/mlx/serialization/generate.py
#
# To regenerate, run from the executorch root:
#     python backends/mlx/serialization/generate.py
#
# ============================================================================

"""
Auto-generated inspector field mappings for MLX delegate.

This module provides field metadata for each op node type, enabling
the pte_inspector to parse FlatBuffer op nodes without manually
maintaining field mappings.
"""

from __future__ import annotations

from typing import Dict, List, Tuple


# Field kinds and their extractors
# Each field is a tuple of (display_name, accessor_name, kind)
# where kind is one of: 'tid', 'vid', 'int_or_vid', 'float_or_vid',
# 'int_list', 'int_or_vid_list', 'tid_list', 'string_list', 'scalar', 'string'

FieldSpec = Tuple[str, str, str]  # (display_name, accessor_name, kind)


# Mapping from op node name to list of field specs
OP_NODE_FIELDS: Dict[str, List[FieldSpec]] = {
    "NoopNode": [
    ],
    "IdCopyNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "AddmmNode": [
        ("mat1", "Mat1", "tid"),
        ("mat2", "Mat2", "tid"),
        ("out", "Out", "tid"),
        ("bias", "Bias", "tid"),
        ("alpha", "Alpha", "scalar"),
        ("beta", "Beta", "scalar"),
    ],
    "ItemIntNode": [
        ("x", "X", "tid"),
        ("out", "Out", "vid"),
    ],
    "ExpandDimsNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "TileNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("reps", "Reps", "int_or_vid_list"),
    ],
    "TakeAlongAxisNode": [
        ("x", "X", "tid"),
        ("indices", "Indices", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "TakeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("index", "Index", "int_or_vid_or_tid"),
        ("axis", "Axis", "scalar"),
    ],
    "RMSNormNode": [
        ("x", "X", "tid"),
        ("weight", "Weight", "tid"),
        ("out", "Out", "tid"),
        ("eps", "Eps", "scalar"),
    ],
    "LayerNormNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("weight", "Weight", "tid"),
        ("bias", "Bias", "tid"),
        ("eps", "Eps", "scalar"),
    ],
    "RopeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("dims", "Dims", "scalar"),
        ("offset", "Offset", "vid_or_tid"),
        ("freqs", "Freqs", "tid"),
        ("traditional", "Traditional", "scalar"),
        ("base", "Base", "scalar"),
        ("scale", "Scale", "scalar"),
    ],
    "SdpaNode": [
        ("q", "Q", "tid"),
        ("k", "K", "tid"),
        ("v", "V", "tid"),
        ("out", "Out", "tid"),
        ("scale", "Scale", "scalar"),
        ("mask", "Mask", "tid"),
        ("causal", "Causal", "scalar"),
    ],
    "AddNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "AddIntNode": [
        ("a", "A", "int_or_vid"),
        ("b", "B", "int_or_vid"),
        ("out", "Out", "vid"),
    ],
    "SubtractIntNode": [
        ("a", "A", "int_or_vid"),
        ("b", "B", "int_or_vid"),
        ("out", "Out", "vid"),
    ],
    "MultiplyIntNode": [
        ("a", "A", "int_or_vid"),
        ("b", "B", "int_or_vid"),
        ("out", "Out", "vid"),
    ],
    "FloorDivideIntNode": [
        ("a", "A", "int_or_vid"),
        ("b", "B", "int_or_vid"),
        ("out", "Out", "vid"),
    ],
    "ModIntNode": [
        ("a", "A", "int_or_vid"),
        ("b", "B", "int_or_vid"),
        ("out", "Out", "vid"),
    ],
    "SymSizeNode": [
        ("a", "A", "tid"),
        ("dim", "Dim", "scalar"),
        ("out", "Out", "vid"),
    ],
    "MultiplyNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "DivideNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "SubtractNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "Conv1DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride", "Stride", "scalar"),
        ("padding", "Padding", "scalar"),
        ("dilation", "Dilation", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "Conv2DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride_h", "StrideH", "scalar"),
        ("stride_w", "StrideW", "scalar"),
        ("padding_h", "PaddingH", "scalar"),
        ("padding_w", "PaddingW", "scalar"),
        ("dilation_h", "DilationH", "scalar"),
        ("dilation_w", "DilationW", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "Conv3DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride_d", "StrideD", "scalar"),
        ("stride_h", "StrideH", "scalar"),
        ("stride_w", "StrideW", "scalar"),
        ("padding_d", "PaddingD", "scalar"),
        ("padding_h", "PaddingH", "scalar"),
        ("padding_w", "PaddingW", "scalar"),
        ("dilation_d", "DilationD", "scalar"),
        ("dilation_h", "DilationH", "scalar"),
        ("dilation_w", "DilationW", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "ConvTranspose1DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride", "Stride", "scalar"),
        ("padding", "Padding", "scalar"),
        ("dilation", "Dilation", "scalar"),
        ("output_padding", "OutputPadding", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "ConvTranspose2DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride_h", "StrideH", "scalar"),
        ("stride_w", "StrideW", "scalar"),
        ("padding_h", "PaddingH", "scalar"),
        ("padding_w", "PaddingW", "scalar"),
        ("dilation_h", "DilationH", "scalar"),
        ("dilation_w", "DilationW", "scalar"),
        ("output_padding_h", "OutputPaddingH", "scalar"),
        ("output_padding_w", "OutputPaddingW", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "ConvTranspose3DNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("out", "Out", "tid"),
        ("stride_d", "StrideD", "scalar"),
        ("stride_h", "StrideH", "scalar"),
        ("stride_w", "StrideW", "scalar"),
        ("padding_d", "PaddingD", "scalar"),
        ("padding_h", "PaddingH", "scalar"),
        ("padding_w", "PaddingW", "scalar"),
        ("dilation_d", "DilationD", "scalar"),
        ("dilation_h", "DilationH", "scalar"),
        ("dilation_w", "DilationW", "scalar"),
        ("output_padding_d", "OutputPaddingD", "scalar"),
        ("output_padding_h", "OutputPaddingH", "scalar"),
        ("output_padding_w", "OutputPaddingW", "scalar"),
        ("groups", "Groups", "scalar"),
    ],
    "GeluNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("approximate", "Approximate", "string"),
    ],
    "ARangeNode": [
        ("out", "Out", "tid"),
        ("start", "Start", "int_or_vid"),
        ("stop", "Stop", "int_or_vid"),
        ("step", "Step", "int_or_vid"),
        ("scalar_type", "ScalarType", "scalar"),
    ],
    "SiluNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SigmoidNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "TanhNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SqueezeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("dims", "Dims", "int_list"),
    ],
    "SplitNode": [
        ("x", "X", "tid"),
        ("outs", "Outs", "tid_list"),
        ("sizes", "Sizes", "int_or_vid_list"),
        ("axis", "Axis", "scalar"),
    ],
    "RsqrtNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "MaximumNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "MinimumNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SoftmaxNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
        ("precise", "Precise", "scalar"),
    ],
    "BroadcastToNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("shape", "Shape", "int_or_vid_list"),
    ],
    "PadNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("pad_width", "PadWidth", "int_or_vid_list"),
        ("mode", "Mode", "string"),
        ("constant_value", "ConstantValue", "scalar"),
    ],
    "WhereNode": [
        ("condition", "Condition", "tid"),
        ("x", "X", "tid"),
        ("y", "Y", "tid"),
        ("out", "Out", "tid"),
    ],
    "ReshapeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("shape", "Shape", "int_or_vid_list"),
    ],
    "TransposeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("perm", "Perm", "int_list"),
    ],
    "AsStridedNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("shape", "Shape", "int_or_vid_list"),
        ("strides", "Strides", "int_or_vid_list"),
        ("offset", "Offset", "scalar"),
    ],
    "ContiguousNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "GatherNode": [
        ("x", "X", "tid"),
        ("indices", "Indices", "tid_list"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("slice_sizes", "SliceSizes", "int_list"),
    ],
    "SliceNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "int_or_vid"),
        ("start", "Start", "int_or_vid"),
        ("stop", "Stop", "int_or_vid"),
        ("step", "Step", "scalar"),
    ],
    "AsTypeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("scalar_type", "ScalarType", "scalar"),
    ],
    "QuantizedMatmulNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("scales", "Scales", "tid"),
        ("out", "Out", "tid"),
        ("biases", "Biases", "tid"),
        ("group_size", "GroupSize", "scalar"),
        ("bits", "Bits", "scalar"),
        ("mode", "Mode", "string"),
        ("transpose", "Transpose", "scalar"),
    ],
    "ScatterAddNode": [
        ("x", "X", "tid"),
        ("indices", "Indices", "tid"),
        ("updates", "Updates", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "ConcatenateNode": [
        ("tensors", "Tensors", "tid_list"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "FullNode": [
        ("out", "Out", "tid"),
        ("shape", "Shape", "int_or_vid_list"),
        ("v", "V", "float_or_vid"),
        ("scalar_type", "ScalarType", "scalar"),
    ],
    "FullLikeNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("v", "V", "float_or_vid"),
        ("scalar_type", "ScalarType", "scalar"),
    ],
    "ArgmaxNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "SliceUpdateNode": [
        ("dst", "Dst", "tid"),
        ("update", "Update", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "int_or_vid"),
        ("start", "Start", "int_or_vid"),
        ("stop", "Stop", "int_or_vid"),
        ("step", "Step", "scalar"),
    ],
    "IndexCopyNode": [
        ("dst", "Dst", "tid"),
        ("update", "Update", "tid"),
        ("indices", "Indices", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "DequantizeNode": [
        ("w", "W", "tid"),
        ("scales", "Scales", "tid"),
        ("out", "Out", "tid"),
        ("biases", "Biases", "tid"),
        ("group_size", "GroupSize", "scalar"),
        ("bits", "Bits", "scalar"),
        ("mode", "Mode", "string"),
        ("global_scale", "GlobalScale", "tid"),
        ("dtype", "Dtype", "scalar"),
    ],
    "LessNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LessEqualNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "GreaterNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "GreaterEqualNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "EqualNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "NotEqualNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogicalNotNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogicalAndNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogicalOrNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "TriNode": [
        ("out", "Out", "tid"),
        ("n", "N", "int_or_vid"),
        ("m", "M", "int_or_vid"),
        ("k", "K", "scalar"),
        ("scalar_type", "ScalarType", "scalar"),
    ],
    "TrilNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("k", "K", "scalar"),
    ],
    "TriuNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("k", "K", "scalar"),
    ],
    "ClipNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("a_min", "AMin", "tid"),
        ("a_max", "AMax", "tid"),
    ],
    "CumsumNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
        ("reverse", "Reverse", "scalar"),
        ("inclusive", "Inclusive", "scalar"),
    ],
    "StackNode": [
        ("tensors", "Tensors", "tid_list"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "SignNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "AnyNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "AllNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "RepeatNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("repeats", "Repeats", "int_or_vid"),
        ("axis", "Axis", "scalar"),
    ],
    "SortNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "ArgsortNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
    ],
    "PartitionNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("kth", "Kth", "int_or_vid"),
        ("axis", "Axis", "scalar"),
    ],
    "ArgPartitionNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("kth", "Kth", "int_or_vid"),
        ("axis", "Axis", "scalar"),
    ],
    "FloorNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "CeilNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SquareNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ExpNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SinNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "CosNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "TanNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArcsinNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArccosNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArctanNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SinhNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "CoshNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArcsinhNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArccoshNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ArctanhNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "Log2Node": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "Log10Node": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "Log1pNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "ErfNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "Expm1Node": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "RoundNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("decimals", "Decimals", "scalar"),
    ],
    "ReciprocalNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "SqrtNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "AbsNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "NegNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
    ],
    "Atan2Node": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogAddExpNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "BitwiseXorNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "FloorDivideNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "RemainderNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "PowerNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
    ],
    "LogSumExpNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "SumNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "MeanNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "VarNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
        ("ddof", "Ddof", "scalar"),
    ],
    "StdNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
        ("ddof", "Ddof", "scalar"),
    ],
    "ProdNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "MaxNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "MinNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "ArgminNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axis", "Axis", "scalar"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "MedianNode": [
        ("x", "X", "tid"),
        ("out", "Out", "tid"),
        ("axes", "Axes", "int_list"),
        ("keepdims", "Keepdims", "scalar"),
    ],
    "GatherMmNode": [
        ("a", "A", "tid"),
        ("b", "B", "tid"),
        ("out", "Out", "tid"),
        ("lhs_indices", "LhsIndices", "tid"),
        ("rhs_indices", "RhsIndices", "tid"),
        ("sorted_indices", "SortedIndices", "scalar"),
    ],
    "GatherQmmNode": [
        ("x", "X", "tid"),
        ("w", "W", "tid"),
        ("scales", "Scales", "tid"),
        ("out", "Out", "tid"),
        ("mode", "Mode", "string"),
        ("biases", "Biases", "tid"),
        ("lhs_indices", "LhsIndices", "tid"),
        ("rhs_indices", "RhsIndices", "tid"),
        ("transpose", "Transpose", "scalar"),
        ("group_size", "GroupSize", "scalar"),
        ("bits", "Bits", "scalar"),
        ("sorted_indices", "SortedIndices", "scalar"),
    ],
    "ScanNode": [
        ("originals", "Originals", "tid_list"),
        ("sliced", "Sliced", "tid_list"),
        ("outputs", "Outputs", "tid_list"),
        ("carry", "Carry", "tid_list"),
        ("body_chain_idx", "BodyChainIdx", "scalar"),
        ("scan_axis", "ScanAxis", "scalar"),
    ],
    "MetalKernelNode": [
        ("name", "Name", "string"),
        ("source", "Source", "string"),
        ("inputs", "Inputs", "tid_list"),
        ("outputs", "Outputs", "tid_list"),
        ("grid", "Grid", "int_or_vid_list"),
        ("threadgroup", "Threadgroup", "int_or_vid_list"),
        ("header", "Header", "string"),
        ("input_names", "InputNames", "string_list"),
        ("output_names", "OutputNames", "string_list"),
        ("ensure_row_contiguous", "EnsureRowContiguous", "scalar"),
        ("atomic_outputs", "AtomicOutputs", "scalar"),
        ("output_shapes_flat", "OutputShapesFlat", "int_or_vid_list"),
        ("output_shape_lengths", "OutputShapeLengths", "int_list"),
        ("output_dtypes", "OutputDtypes", "int_list"),
        ("template_arg_names", "TemplateArgNames", "string_list"),
        ("template_arg_kinds", "TemplateArgKinds", "int_list"),
        ("template_arg_values", "TemplateArgValues", "int_list"),
        ("init_value", "InitValue", "scalar"),
    ],
}


# List of all op node names (for dynamic imports)
OP_NODE_NAMES: List[str] = [
    "NoopNode",
    "IdCopyNode",
    "AddmmNode",
    "ItemIntNode",
    "ExpandDimsNode",
    "TileNode",
    "TakeAlongAxisNode",
    "TakeNode",
    "RMSNormNode",
    "LayerNormNode",
    "RopeNode",
    "SdpaNode",
    "AddNode",
    "AddIntNode",
    "SubtractIntNode",
    "MultiplyIntNode",
    "FloorDivideIntNode",
    "ModIntNode",
    "SymSizeNode",
    "MultiplyNode",
    "DivideNode",
    "SubtractNode",
    "Conv1DNode",
    "Conv2DNode",
    "Conv3DNode",
    "ConvTranspose1DNode",
    "ConvTranspose2DNode",
    "ConvTranspose3DNode",
    "GeluNode",
    "ARangeNode",
    "SiluNode",
    "SigmoidNode",
    "TanhNode",
    "SqueezeNode",
    "SplitNode",
    "RsqrtNode",
    "MaximumNode",
    "MinimumNode",
    "LogNode",
    "SoftmaxNode",
    "BroadcastToNode",
    "PadNode",
    "WhereNode",
    "ReshapeNode",
    "TransposeNode",
    "AsStridedNode",
    "ContiguousNode",
    "GatherNode",
    "SliceNode",
    "AsTypeNode",
    "QuantizedMatmulNode",
    "ScatterAddNode",
    "ConcatenateNode",
    "FullNode",
    "FullLikeNode",
    "ArgmaxNode",
    "SliceUpdateNode",
    "IndexCopyNode",
    "DequantizeNode",
    "LessNode",
    "LessEqualNode",
    "GreaterNode",
    "GreaterEqualNode",
    "EqualNode",
    "NotEqualNode",
    "LogicalNotNode",
    "LogicalAndNode",
    "LogicalOrNode",
    "TriNode",
    "TrilNode",
    "TriuNode",
    "ClipNode",
    "CumsumNode",
    "StackNode",
    "SignNode",
    "AnyNode",
    "AllNode",
    "RepeatNode",
    "SortNode",
    "ArgsortNode",
    "PartitionNode",
    "ArgPartitionNode",
    "FloorNode",
    "CeilNode",
    "SquareNode",
    "ExpNode",
    "SinNode",
    "CosNode",
    "TanNode",
    "ArcsinNode",
    "ArccosNode",
    "ArctanNode",
    "SinhNode",
    "CoshNode",
    "ArcsinhNode",
    "ArccoshNode",
    "ArctanhNode",
    "Log2Node",
    "Log10Node",
    "Log1pNode",
    "ErfNode",
    "Expm1Node",
    "RoundNode",
    "ReciprocalNode",
    "SqrtNode",
    "AbsNode",
    "NegNode",
    "Atan2Node",
    "LogAddExpNode",
    "BitwiseXorNode",
    "FloorDivideNode",
    "RemainderNode",
    "PowerNode",
    "LogSumExpNode",
    "SumNode",
    "MeanNode",
    "VarNode",
    "StdNode",
    "ProdNode",
    "MaxNode",
    "MinNode",
    "ArgminNode",
    "MedianNode",
    "GatherMmNode",
    "GatherQmmNode",
    "ScanNode",
    "MetalKernelNode",
]
