load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("executorch")

fbcode_target(_kind = python_library,
    name = "mobilebert_model",
    srcs = [
        "__init__.py",
        "model.py",
    ],
    deps = [
        "fbsource//third-party/pypi/transformers:transformers",  # @manual
        "//caffe2:torch",
        "//executorch/examples/models:model_base",
    ],
)
