load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# @noautodeps
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("executorch")

fbcode_target(_kind = cpp_unittest,
    name = "pytree_test",
    srcs = ["test_pytree.cpp"],
    deps = ["//executorch/extension/pytree:pytree"],
)

fbcode_target(_kind = python_unittest,
    name = "pybindings_test",
    srcs = [
        "test.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/extension/pytree:pybindings",
        "//executorch/extension/pytree:pylib",
    ],
)
