load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("executorch")

fbcode_target(_kind = python_unittest,
    name = "test_exir_dialect_ops",
    srcs = [
        "test_exir_dialect_ops.py",
    ],
    deps = [
        "//executorch/exir/dialects:lib",
    ],
)
