# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Emit the PIL LANCZOS goldens embedded in the resize parity tests.

Run:
  python gen_resize_golden.py
"""

from PIL import Image


def make_image(w: int, h: int) -> Image.Image:
    """Deterministic RGB content with edges and a gradient (no RNG)."""
    px = bytearray()
    for y in range(h):
        for x in range(w):
            px.append((x * 37 + y * 11) % 256)  # R: diagonal ramp
            px.append(255 if (x < w // 3 and y < h // 2) else 16)  # G: hard edge
            px.append((x * x + y * y * 3) % 256)  # B: curved gradient
    return Image.frombytes("RGB", (w, h), bytes(px))


def emit(src_w: int, src_h: int, dst_w: int, dst_h: int) -> None:
    src = make_image(src_w, src_h)
    dst = src.resize((dst_w, dst_h), Image.LANCZOS)
    print(f"  // {src_w}x{src_h} -> {dst_w}x{dst_h}")
    print(f"  {{{src_w}, {src_h}, {dst_w}, {dst_h},")
    vals = list(dst.tobytes())
    for i in range(0, len(vals), 12):
        chunk = ", ".join(str(v) for v in vals[i : i + 12])
        print(f"      {chunk},")
    print("  },")


def main() -> None:
    print("// Generated by gen_resize_golden.py -- PIL LANCZOS reference output.")
    emit(9, 7, 5, 4)  # downscale, support stretched on both axes
    emit(4, 3, 7, 6)  # upscale
    emit(16, 16, 8, 8)  # exact 2x downscale


main()
