/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Pins the image path's resize to Pillow's LANCZOS.
//
// The reference preprocessing resizes with PIL LANCZOS on the sRGB bytes. The
// runner used to resize with stb Catmull-Rom in linear light instead, which
// differs on essentially every image.
//
// Goldens are Pillow's own output, emitted by tests/gen_resize_golden.py. The
// Python side of the same table lives in
// tests/test_vision_precompute.py::ResizeReferenceParityTest, so a Pillow
// upgrade that changes resampling fails there rather than silently drifting
// away from the C++.

#include <executorch/examples/models/muse-glimmer/vision/preprocess.h>

#include <gtest/gtest.h>

#include <cstdint>
#include <vector>

namespace {

using ::executorch::examples::muse_glimmer_vision::resize_rgb_lanczos;

// Deterministic RGB content with a hard edge and two gradients. Must stay
// byte-identical to make_image() in tests/gen_resize_golden.py.
std::vector<uint8_t> MakeImage(int32_t w, int32_t h) {
  std::vector<uint8_t> px;
  px.reserve(static_cast<size_t>(w) * h * 3);
  for (int32_t y = 0; y < h; ++y) {
    for (int32_t x = 0; x < w; ++x) {
      px.push_back(static_cast<uint8_t>((x * 37 + y * 11) % 256));
      px.push_back((x < w / 3 && y < h / 2) ? 255 : 16);
      px.push_back(static_cast<uint8_t>((x * x + y * y * 3) % 256));
    }
  }
  return px;
}

struct ResizeCase {
  int32_t src_w;
  int32_t src_h;
  int32_t dst_w;
  int32_t dst_h;
  std::vector<uint8_t> expected;
};

// Generated by gen_resize_golden.py -- PIL LANCZOS reference output.
std::vector<ResizeCase> ReferenceResizes() {
  return {
      // Downscale: Pillow stretches the filter support on both axes.
      {9, 7, 5, 4, {19,  255, 1,   83,  189, 6,   161, 0,   17,  182, 20, 35,
                    26,  16,  59,  38,  190, 13,  102, 134, 18,  179, 4,  29,
                    213, 19,  47,  46,  16,  71,  58,  0,   46,  120, 5,  51,
                    208, 17,  62,  123, 16,  80,  54,  16,  104, 77,  20, 95,
                    138, 19,  100, 231, 16,  111, 95,  16,  129, 68,  16, 153}},
      // Upscale.
      {4, 3, 7, 6, {0,   255, 0,  8,   207, 0,  33,  33, 1,  55,  0,   2,
                    76,  19,  4,  101, 19,  8,  113, 16, 9,  1,   211, 0,
                    10,  154, 0,  35,  28,  1,  57,  3,  2,  78,  18,  4,
                    103, 18,  8,  115, 16,  9,  4,   79, 1,  16,  60,  1,
                    41,  20,  2,  63,  12,  3,  84,  17, 5,  109, 17,  9,
                    121, 16,  10, 12,  0,   6,  24,  0,  6,  49,  14,  7,
                    71,  18,  8,  92,  16,  10, 117, 16, 14, 129, 16,  15,
                    17,  1,   11, 30,  6,   11, 55,  15, 12, 77,  17,  13,
                    98,  16,  15, 123, 16,  19, 135, 16, 20, 20,  25,  13,
                    32,  22,  13, 57,  17,  14, 79,  15, 15, 100, 16,  17,
                    125, 16,  21, 137, 16,  22}},
      // Exact 2x downscale.
      {16,
       16,
       8,
       8,
       {25,  250, 1,   92,  255, 7,   194, 135, 21,  119, 0,   43,  43,  20,
        73,  145, 16,  111, 205, 16,  157, 48,  16,  211, 46,  249, 18,  115,
        254, 24,  211, 135, 38,  132, 0,   60,  63,  20,  90,  176, 16,  124,
        160, 16,  178, 48,  16,  233, 68,  254, 60,  143, 255, 66,  213, 137,
        76,  56,  0,   99,  97,  20,  134, 209, 16,  187, 127, 16,  223, 47,
        16,  91,  87,  237, 130, 176, 242, 137, 169, 129, 167, 50,  1,   186,
        130, 20,  193, 210, 16,  176, 96,  16,  82,  83,  16,  61,  108, 29,
        204, 205, 29,  200, 117, 22,  111, 55,  15,  117, 162, 16,  56,  201,
        16,  66,  48,  16,  119, 115, 16,  181, 138, 12,  92,  197, 12,  105,
        48,  14,  96,  90,  16,  119, 197, 16,  142, 136, 16,  173, 49,  16,
        167, 144, 16,  95,  162, 17,  195, 208, 17,  145, 57,  16,  101, 119,
        16,  143, 201, 16,  102, 82,  16,  94,  77,  16,  128, 165, 16,  138,
        199, 16,  135, 131, 16,  122, 50,  16,  114, 153, 16,  140, 201, 16,
        171, 40,  16,  113, 109, 16,  145, 184, 16,  99}},
  };
}

TEST(VisionResizeParityTest, MatchesPillowLanczos) {
  for (const ResizeCase& resize_case : ReferenceResizes()) {
    const std::vector<uint8_t> src =
        MakeImage(resize_case.src_w, resize_case.src_h);

    const std::vector<uint8_t> actual = resize_rgb_lanczos(
        src.data(),
        resize_case.src_w,
        resize_case.src_h,
        resize_case.dst_w,
        resize_case.dst_h);

    EXPECT_EQ(actual, resize_case.expected)
        << resize_case.src_w << "x" << resize_case.src_h << " -> "
        << resize_case.dst_w << "x" << resize_case.dst_h;
  }
}

} // namespace
