[pytest]
addopts =
    # show summary of all tests that did not pass
    -rEfX
    # Make tracebacks shorter
    --tb=native
    # capture only Python print and C++ py::print, but not C output (low-level Python errors)
    --capture=sys
    # don't suppress warnings, but don't shove them all to the end either
    -p no:warnings
    
    # === TEST DIRECTORIES TO RUN ===
    
    # ci/scripts
    .ci/scripts/tests
    
    # backends
    backends/apple/coreml/test
    backends/test/harness/tests
    backends/test/suite/tests
    backends/transforms
    backends/xnnpack/test
    # Ignore ARM backend - requires running examples/arm/setup.sh to install tools
    --ignore-glob=backends/arm/**/*
    # Ignore backends/test root - WIP testing infra, see https://github.com/pytorch/executorch/discussions/11140
    --ignore=backends/test
    
    # codegen
    codegen/test
    
    # devtools
    devtools/
    
    # examples
    examples/models/test
    examples/models/llama/tests
    examples/models/llama/config
    examples/models/llama3_2_vision/preprocess
    examples/models/llama3_2_vision/vision_encoder/test
    examples/models/llama3_2_vision/text_decoder/test
    examples/models/llava/test
    # Ignore test requiring torchao - T200992559: Add torchao to ET as core dependency
    --ignore=examples/models/llama/tests/test_pre_quantization_transforms.py
    
    # exir
    exir/
    
    # export
    export/tests
    --ignore=export/tests/test_export_stages.py
    
    # extension
    extension/
    
    # kernels
    kernels/prim_ops/test
    kernels/quantized
    kernels/test/test_case_gen.py
    # Ignore test depending on test-only cpp ops lib
    --ignore=kernels/quantized/test/test_quant_dequant_per_token.py
    
    # profiler
    profiler/
    
    # runtime
    runtime
    
    # test
    test/
    
    # tools
    tools/cmake

# run the same tests multiple times to determine their
# flakiness status. Default to 50 re-runs
flake-finder = true
flake-runs = 50