load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "jet_nemotron",
    srcs = [
        "__init__.py",
        "jet_block.py",
        "model.py",
    ],
    _is_external_target = True,
    base_module = "executorch.examples.models.jet_nemotron",
    deps = [
        "//caffe2:torch",
        "//executorch/examples/models:model_base",
    ],
    visibility = ["PUBLIC"],
)
