load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_partitioner_configs",
    srcs = glob([
        "*.py",
    ]),
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/exir:lib",
        "//executorch/exir/backend:partitioner",
        "//executorch/exir/backend:utils",
        "//executorch/exir/backend/canonical_partitioners:config_partitioner_lib",
    ],
)
