load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "lib",
    srcs = [
        "merge_to_dim_pass.py",
        "permute_memory_formats_pass.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/example/example_operators:example_operators_lib",
        "//executorch/exir:dim_order_utils",
        "//executorch/exir:pass_base",
        "//executorch/exir/dialects:lib",
    ],
)
