load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_quantizer",
    srcs = ["xnnpack_quantizer.py"],
    deps = [
        ":xnnpack_quantizer_utils",
        "//executorch/backends/xnnpack/utils:xnnpack_utils",
        "//caffe2:torch",
        "//executorch/exir:lib",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_quantizer_utils",
    srcs = ["xnnpack_quantizer_utils.py"],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/backends/xnnpack/utils:xnnpack_utils",
    ],
)
