load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "tester",
    srcs = [
        "__init__.py",
        "tester.py",
    ],
    base_module = "executorch.backends.xnnpack.test.tester",
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/test/harness:tester",
        "//executorch/backends/xnnpack/partition:xnnpack_partitioner",
        "//executorch/backends/xnnpack/quantizer:xnnpack_quantizer",
        "//executorch/backends/xnnpack/quantizer:xnnpack_quantizer_utils",
        "//executorch/backends/xnnpack/utils:xnnpack_utils",
        "//executorch/devtools/visualization:visualization",
        "//executorch/exir:lib",
        "//executorch/exir/_serialize:lib",
        "//executorch/exir/backend:backend_api",
        "//executorch/exir/backend:partitioner",
        "//executorch/exir/passes:spec_prop_pass",
        "//executorch/extension/pybindings:portable_lib",  # @manual
        "//executorch/backends/transforms:duplicate_dynamic_quant_chain"
    ],
)
