load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("ai_infra_mobile_platform")

fbcode_target(_kind = runtime.python_library,
    name = "lib",
    srcs = [
        "gen.py",
        "utils.py",
    ],
    deps = [
        "fbsource//third-party/pypi/ruamel-yaml:ruamel-yaml",
        "//caffe2:torch",
        "//executorch/exir/dialects/edge/arg:lib",
        "//executorch/exir/dialects/edge/dtype:lib",
        "//executorch/exir/dialects/edge/op:lib",
    ],
)

fbcode_target(_kind = python_binary,
    name = "gen",
    srcs = [],
    main_function = "executorch.exir.dialects.edge.spec.gen.main",
    deps = [
        "fbsource//third-party/pypi/expecttest:expecttest",  # @manual
        ":lib",
    ],
)
