load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "multimodal_lib",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//executorch/examples/models/llama3_2_vision/text_decoder:model",
        "//executorch/examples/models/llama3_2_vision/vision_encoder:model",
    ],
)
