load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "performance",
    srcs = [
        "__init__.py",
        "performance.py",
    ],
    base_module = "executorch.backends.xnnpack.test.performance",
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/extension/pybindings:portable_lib",  # @manual
    ],
)
