load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(
    _kind = runtime.python_library,
    name = "runtime",
    srcs = ["__init__.py"],
    deps = [
        "//executorch/extension/pybindings:_C",
        "//executorch/extension/pybindings:_bootstrap",
    ],
    visibility = ["PUBLIC"],
)
