load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")

oncall("executorch")

fbcode_target(
    _kind = runtime.python_library,
    name = "flow",
    srcs = ["flow.py"],
    deps = [
        "//executorch/backends/test/harness:tester",
    ],
)

fbcode_target(_kind = define_common_targets, is_fbcode = True)
