# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Conv3DNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Conv3DNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConv3DNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Conv3DNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Conv3DNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv3DNode
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv3DNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv3DNode
    def StrideD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def StrideH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def StrideW(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def PaddingD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Conv3DNode
    def PaddingH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Conv3DNode
    def PaddingW(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Conv3DNode
    def DilationD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def DilationH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def DilationW(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv3DNode
    def Groups(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def Conv3DNodeStart(builder):
    builder.StartObject(13)

def Start(builder):
    Conv3DNodeStart(builder)

def Conv3DNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    Conv3DNodeAddX(builder, x)

def Conv3DNodeAddW(builder, w):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(w), 0)

def AddW(builder, w):
    Conv3DNodeAddW(builder, w)

def Conv3DNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    Conv3DNodeAddOut(builder, out)

def Conv3DNodeAddStrideD(builder, strideD):
    builder.PrependInt32Slot(3, strideD, 1)

def AddStrideD(builder, strideD):
    Conv3DNodeAddStrideD(builder, strideD)

def Conv3DNodeAddStrideH(builder, strideH):
    builder.PrependInt32Slot(4, strideH, 1)

def AddStrideH(builder, strideH):
    Conv3DNodeAddStrideH(builder, strideH)

def Conv3DNodeAddStrideW(builder, strideW):
    builder.PrependInt32Slot(5, strideW, 1)

def AddStrideW(builder, strideW):
    Conv3DNodeAddStrideW(builder, strideW)

def Conv3DNodeAddPaddingD(builder, paddingD):
    builder.PrependInt32Slot(6, paddingD, 0)

def AddPaddingD(builder, paddingD):
    Conv3DNodeAddPaddingD(builder, paddingD)

def Conv3DNodeAddPaddingH(builder, paddingH):
    builder.PrependInt32Slot(7, paddingH, 0)

def AddPaddingH(builder, paddingH):
    Conv3DNodeAddPaddingH(builder, paddingH)

def Conv3DNodeAddPaddingW(builder, paddingW):
    builder.PrependInt32Slot(8, paddingW, 0)

def AddPaddingW(builder, paddingW):
    Conv3DNodeAddPaddingW(builder, paddingW)

def Conv3DNodeAddDilationD(builder, dilationD):
    builder.PrependInt32Slot(9, dilationD, 1)

def AddDilationD(builder, dilationD):
    Conv3DNodeAddDilationD(builder, dilationD)

def Conv3DNodeAddDilationH(builder, dilationH):
    builder.PrependInt32Slot(10, dilationH, 1)

def AddDilationH(builder, dilationH):
    Conv3DNodeAddDilationH(builder, dilationH)

def Conv3DNodeAddDilationW(builder, dilationW):
    builder.PrependInt32Slot(11, dilationW, 1)

def AddDilationW(builder, dilationW):
    Conv3DNodeAddDilationW(builder, dilationW)

def Conv3DNodeAddGroups(builder, groups):
    builder.PrependInt32Slot(12, groups, 1)

def AddGroups(builder, groups):
    Conv3DNodeAddGroups(builder, groups)

def Conv3DNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return Conv3DNodeEnd(builder)
