# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GatherMmNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GatherMmNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGatherMmNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GatherMmNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GatherMmNode
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherMmNode
    def B(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherMmNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherMmNode
    def LhsIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherMmNode
    def RhsIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherMmNode
    def SortedIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GatherMmNodeStart(builder):
    builder.StartObject(6)

def Start(builder):
    GatherMmNodeStart(builder)

def GatherMmNodeAddA(builder, a):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(a), 0)

def AddA(builder, a):
    GatherMmNodeAddA(builder, a)

def GatherMmNodeAddB(builder, b):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(b), 0)

def AddB(builder, b):
    GatherMmNodeAddB(builder, b)

def GatherMmNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    GatherMmNodeAddOut(builder, out)

def GatherMmNodeAddLhsIndices(builder, lhsIndices):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(lhsIndices), 0)

def AddLhsIndices(builder, lhsIndices):
    GatherMmNodeAddLhsIndices(builder, lhsIndices)

def GatherMmNodeAddRhsIndices(builder, rhsIndices):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(rhsIndices), 0)

def AddRhsIndices(builder, rhsIndices):
    GatherMmNodeAddRhsIndices(builder, rhsIndices)

def GatherMmNodeAddSortedIndices(builder, sortedIndices):
    builder.PrependBoolSlot(5, sortedIndices, 0)

def AddSortedIndices(builder, sortedIndices):
    GatherMmNodeAddSortedIndices(builder, sortedIndices)

def GatherMmNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return GatherMmNodeEnd(builder)
