# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GatherQmmNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GatherQmmNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGatherQmmNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GatherQmmNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GatherQmmNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def Scales(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GatherQmmNode
    def Biases(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def LhsIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def RhsIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GatherQmmNode
    def Transpose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # GatherQmmNode
    def GroupSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GatherQmmNode
    def Bits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GatherQmmNode
    def SortedIndices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GatherQmmNodeStart(builder):
    builder.StartObject(12)

def Start(builder):
    GatherQmmNodeStart(builder)

def GatherQmmNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    GatherQmmNodeAddX(builder, x)

def GatherQmmNodeAddW(builder, w):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(w), 0)

def AddW(builder, w):
    GatherQmmNodeAddW(builder, w)

def GatherQmmNodeAddScales(builder, scales):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(scales), 0)

def AddScales(builder, scales):
    GatherQmmNodeAddScales(builder, scales)

def GatherQmmNodeAddOut(builder, out):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    GatherQmmNodeAddOut(builder, out)

def GatherQmmNodeAddMode(builder, mode):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mode), 0)

def AddMode(builder, mode):
    GatherQmmNodeAddMode(builder, mode)

def GatherQmmNodeAddBiases(builder, biases):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(biases), 0)

def AddBiases(builder, biases):
    GatherQmmNodeAddBiases(builder, biases)

def GatherQmmNodeAddLhsIndices(builder, lhsIndices):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(lhsIndices), 0)

def AddLhsIndices(builder, lhsIndices):
    GatherQmmNodeAddLhsIndices(builder, lhsIndices)

def GatherQmmNodeAddRhsIndices(builder, rhsIndices):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(rhsIndices), 0)

def AddRhsIndices(builder, rhsIndices):
    GatherQmmNodeAddRhsIndices(builder, rhsIndices)

def GatherQmmNodeAddTranspose(builder, transpose):
    builder.PrependBoolSlot(8, transpose, 1)

def AddTranspose(builder, transpose):
    GatherQmmNodeAddTranspose(builder, transpose)

def GatherQmmNodeAddGroupSize(builder, groupSize):
    builder.PrependInt32Slot(9, groupSize, 0)

def AddGroupSize(builder, groupSize):
    GatherQmmNodeAddGroupSize(builder, groupSize)

def GatherQmmNodeAddBits(builder, bits):
    builder.PrependInt32Slot(10, bits, 0)

def AddBits(builder, bits):
    GatherQmmNodeAddBits(builder, bits)

def GatherQmmNodeAddSortedIndices(builder, sortedIndices):
    builder.PrependBoolSlot(11, sortedIndices, 0)

def AddSortedIndices(builder, sortedIndices):
    GatherQmmNodeAddSortedIndices(builder, sortedIndices)

def GatherQmmNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return GatherQmmNodeEnd(builder)
