# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntOrVidOrTid(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntOrVidOrTid()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntOrVidOrTid(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntOrVidOrTid
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntOrVidOrTid
    def Literal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # IntOrVidOrTid
    def Vid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Vid import Vid
            obj = Vid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IntOrVidOrTid
    def Tid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IntOrVidOrTid
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def IntOrVidOrTidStart(builder):
    builder.StartObject(4)

def Start(builder):
    IntOrVidOrTidStart(builder)

def IntOrVidOrTidAddLiteral(builder, literal):
    builder.PrependInt64Slot(0, literal, 0)

def AddLiteral(builder, literal):
    IntOrVidOrTidAddLiteral(builder, literal)

def IntOrVidOrTidAddVid(builder, vid):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(vid), 0)

def AddVid(builder, vid):
    IntOrVidOrTidAddVid(builder, vid)

def IntOrVidOrTidAddTid(builder, tid):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tid), 0)

def AddTid(builder, tid):
    IntOrVidOrTidAddTid(builder, tid)

def IntOrVidOrTidAddKind(builder, kind):
    builder.PrependUint8Slot(3, kind, 0)

def AddKind(builder, kind):
    IntOrVidOrTidAddKind(builder, kind)

def IntOrVidOrTidEnd(builder):
    return builder.EndObject()

def End(builder):
    return IntOrVidOrTidEnd(builder)
