# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LessNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LessNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLessNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LessNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LessNode
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LessNode
    def B(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LessNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LessNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    LessNodeStart(builder)

def LessNodeAddA(builder, a):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(a), 0)

def AddA(builder, a):
    LessNodeAddA(builder, a)

def LessNodeAddB(builder, b):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(b), 0)

def AddB(builder, b):
    LessNodeAddB(builder, b)

def LessNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    LessNodeAddOut(builder, out)

def LessNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return LessNodeEnd(builder)
