# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MetalKernelNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetalKernelNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMetalKernelNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MetalKernelNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetalKernelNode
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetalKernelNode
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetalKernelNode
    def Inputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetalKernelNode
    def InputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def InputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MetalKernelNode
    def Outputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetalKernelNode
    def OutputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def OutputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MetalKernelNode
    def Grid(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetalKernelNode
    def GridLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def GridIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # MetalKernelNode
    def Threadgroup(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetalKernelNode
    def ThreadgroupLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def ThreadgroupIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # MetalKernelNode
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetalKernelNode
    def InputNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MetalKernelNode
    def InputNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def InputNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # MetalKernelNode
    def OutputNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MetalKernelNode
    def OutputNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def OutputNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # MetalKernelNode
    def EnsureRowContiguous(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # MetalKernelNode
    def AtomicOutputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MetalKernelNode
    def OutputShapesFlat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetalKernelNode
    def OutputShapesFlatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def OutputShapesFlatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # MetalKernelNode
    def OutputShapeLengths(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MetalKernelNode
    def OutputShapeLengthsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MetalKernelNode
    def OutputShapeLengthsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def OutputShapeLengthsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # MetalKernelNode
    def OutputDtypes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MetalKernelNode
    def OutputDtypesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # MetalKernelNode
    def OutputDtypesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def OutputDtypesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # MetalKernelNode
    def TemplateArgNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MetalKernelNode
    def TemplateArgNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def TemplateArgNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # MetalKernelNode
    def TemplateArgKinds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MetalKernelNode
    def TemplateArgKindsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # MetalKernelNode
    def TemplateArgKindsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def TemplateArgKindsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # MetalKernelNode
    def TemplateArgValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MetalKernelNode
    def TemplateArgValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MetalKernelNode
    def TemplateArgValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetalKernelNode
    def TemplateArgValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # MetalKernelNode
    def InitValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

def MetalKernelNodeStart(builder):
    builder.StartObject(18)

def Start(builder):
    MetalKernelNodeStart(builder)

def MetalKernelNodeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    MetalKernelNodeAddName(builder, name)

def MetalKernelNodeAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    MetalKernelNodeAddSource(builder, source)

def MetalKernelNodeAddInputs(builder, inputs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)

def AddInputs(builder, inputs):
    MetalKernelNodeAddInputs(builder, inputs)

def MetalKernelNodeStartInputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputsVector(builder, numElems):
    return MetalKernelNodeStartInputsVector(builder, numElems)

def MetalKernelNodeAddOutputs(builder, outputs):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)

def AddOutputs(builder, outputs):
    MetalKernelNodeAddOutputs(builder, outputs)

def MetalKernelNodeStartOutputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputsVector(builder, numElems):
    return MetalKernelNodeStartOutputsVector(builder, numElems)

def MetalKernelNodeAddGrid(builder, grid):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(grid), 0)

def AddGrid(builder, grid):
    MetalKernelNodeAddGrid(builder, grid)

def MetalKernelNodeStartGridVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGridVector(builder, numElems):
    return MetalKernelNodeStartGridVector(builder, numElems)

def MetalKernelNodeAddThreadgroup(builder, threadgroup):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(threadgroup), 0)

def AddThreadgroup(builder, threadgroup):
    MetalKernelNodeAddThreadgroup(builder, threadgroup)

def MetalKernelNodeStartThreadgroupVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartThreadgroupVector(builder, numElems):
    return MetalKernelNodeStartThreadgroupVector(builder, numElems)

def MetalKernelNodeAddHeader(builder, header):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder, header):
    MetalKernelNodeAddHeader(builder, header)

def MetalKernelNodeAddInputNames(builder, inputNames):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(inputNames), 0)

def AddInputNames(builder, inputNames):
    MetalKernelNodeAddInputNames(builder, inputNames)

def MetalKernelNodeStartInputNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputNamesVector(builder, numElems):
    return MetalKernelNodeStartInputNamesVector(builder, numElems)

def MetalKernelNodeAddOutputNames(builder, outputNames):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(outputNames), 0)

def AddOutputNames(builder, outputNames):
    MetalKernelNodeAddOutputNames(builder, outputNames)

def MetalKernelNodeStartOutputNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputNamesVector(builder, numElems):
    return MetalKernelNodeStartOutputNamesVector(builder, numElems)

def MetalKernelNodeAddEnsureRowContiguous(builder, ensureRowContiguous):
    builder.PrependBoolSlot(9, ensureRowContiguous, 1)

def AddEnsureRowContiguous(builder, ensureRowContiguous):
    MetalKernelNodeAddEnsureRowContiguous(builder, ensureRowContiguous)

def MetalKernelNodeAddAtomicOutputs(builder, atomicOutputs):
    builder.PrependBoolSlot(10, atomicOutputs, 0)

def AddAtomicOutputs(builder, atomicOutputs):
    MetalKernelNodeAddAtomicOutputs(builder, atomicOutputs)

def MetalKernelNodeAddOutputShapesFlat(builder, outputShapesFlat):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(outputShapesFlat), 0)

def AddOutputShapesFlat(builder, outputShapesFlat):
    MetalKernelNodeAddOutputShapesFlat(builder, outputShapesFlat)

def MetalKernelNodeStartOutputShapesFlatVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputShapesFlatVector(builder, numElems):
    return MetalKernelNodeStartOutputShapesFlatVector(builder, numElems)

def MetalKernelNodeAddOutputShapeLengths(builder, outputShapeLengths):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(outputShapeLengths), 0)

def AddOutputShapeLengths(builder, outputShapeLengths):
    MetalKernelNodeAddOutputShapeLengths(builder, outputShapeLengths)

def MetalKernelNodeStartOutputShapeLengthsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputShapeLengthsVector(builder, numElems):
    return MetalKernelNodeStartOutputShapeLengthsVector(builder, numElems)

def MetalKernelNodeAddOutputDtypes(builder, outputDtypes):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(outputDtypes), 0)

def AddOutputDtypes(builder, outputDtypes):
    MetalKernelNodeAddOutputDtypes(builder, outputDtypes)

def MetalKernelNodeStartOutputDtypesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartOutputDtypesVector(builder, numElems):
    return MetalKernelNodeStartOutputDtypesVector(builder, numElems)

def MetalKernelNodeAddTemplateArgNames(builder, templateArgNames):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(templateArgNames), 0)

def AddTemplateArgNames(builder, templateArgNames):
    MetalKernelNodeAddTemplateArgNames(builder, templateArgNames)

def MetalKernelNodeStartTemplateArgNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTemplateArgNamesVector(builder, numElems):
    return MetalKernelNodeStartTemplateArgNamesVector(builder, numElems)

def MetalKernelNodeAddTemplateArgKinds(builder, templateArgKinds):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(templateArgKinds), 0)

def AddTemplateArgKinds(builder, templateArgKinds):
    MetalKernelNodeAddTemplateArgKinds(builder, templateArgKinds)

def MetalKernelNodeStartTemplateArgKindsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTemplateArgKindsVector(builder, numElems):
    return MetalKernelNodeStartTemplateArgKindsVector(builder, numElems)

def MetalKernelNodeAddTemplateArgValues(builder, templateArgValues):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(templateArgValues), 0)

def AddTemplateArgValues(builder, templateArgValues):
    MetalKernelNodeAddTemplateArgValues(builder, templateArgValues)

def MetalKernelNodeStartTemplateArgValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTemplateArgValuesVector(builder, numElems):
    return MetalKernelNodeStartTemplateArgValuesVector(builder, numElems)

def MetalKernelNodeAddInitValue(builder, initValue):
    builder.PrependFloat32Slot(17, initValue, None)

def AddInitValue(builder, initValue):
    MetalKernelNodeAddInitValue(builder, initValue)

def MetalKernelNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return MetalKernelNodeEnd(builder)
