# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedMatmulNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedMatmulNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedMatmulNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedMatmulNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedMatmulNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedMatmulNode
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedMatmulNode
    def Scales(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedMatmulNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedMatmulNode
    def Biases(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedMatmulNode
    def GroupSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # QuantizedMatmulNode
    def Bits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # QuantizedMatmulNode
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # QuantizedMatmulNode
    def Transpose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def QuantizedMatmulNodeStart(builder):
    builder.StartObject(9)

def Start(builder):
    QuantizedMatmulNodeStart(builder)

def QuantizedMatmulNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    QuantizedMatmulNodeAddX(builder, x)

def QuantizedMatmulNodeAddW(builder, w):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(w), 0)

def AddW(builder, w):
    QuantizedMatmulNodeAddW(builder, w)

def QuantizedMatmulNodeAddScales(builder, scales):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(scales), 0)

def AddScales(builder, scales):
    QuantizedMatmulNodeAddScales(builder, scales)

def QuantizedMatmulNodeAddOut(builder, out):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    QuantizedMatmulNodeAddOut(builder, out)

def QuantizedMatmulNodeAddBiases(builder, biases):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(biases), 0)

def AddBiases(builder, biases):
    QuantizedMatmulNodeAddBiases(builder, biases)

def QuantizedMatmulNodeAddGroupSize(builder, groupSize):
    builder.PrependInt32Slot(5, groupSize, 0)

def AddGroupSize(builder, groupSize):
    QuantizedMatmulNodeAddGroupSize(builder, groupSize)

def QuantizedMatmulNodeAddBits(builder, bits):
    builder.PrependInt32Slot(6, bits, 0)

def AddBits(builder, bits):
    QuantizedMatmulNodeAddBits(builder, bits)

def QuantizedMatmulNodeAddMode(builder, mode):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(mode), 0)

def AddMode(builder, mode):
    QuantizedMatmulNodeAddMode(builder, mode)

def QuantizedMatmulNodeAddTranspose(builder, transpose):
    builder.PrependBoolSlot(8, transpose, 1)

def AddTranspose(builder, transpose):
    QuantizedMatmulNodeAddTranspose(builder, transpose)

def QuantizedMatmulNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedMatmulNodeEnd(builder)
