# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RandomBitsNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RandomBitsNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRandomBitsNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RandomBitsNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RandomBitsNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RandomBitsNode
    def Shape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RandomBitsNode
    def ShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RandomBitsNode
    def ShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # RandomBitsNode
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Vid import Vid
            obj = Vid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RandomBitsNode
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 4

def RandomBitsNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    RandomBitsNodeStart(builder)

def RandomBitsNodeAddOut(builder, out):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    RandomBitsNodeAddOut(builder, out)

def RandomBitsNodeAddShape(builder, shape):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)

def AddShape(builder, shape):
    RandomBitsNodeAddShape(builder, shape)

def RandomBitsNodeStartShapeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShapeVector(builder, numElems):
    return RandomBitsNodeStartShapeVector(builder, numElems)

def RandomBitsNodeAddSeed(builder, seed):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(seed), 0)

def AddSeed(builder, seed):
    RandomBitsNodeAddSeed(builder, seed)

def RandomBitsNodeAddWidth(builder, width):
    builder.PrependInt32Slot(3, width, 4)

def AddWidth(builder, width):
    RandomBitsNodeAddWidth(builder, width)

def RandomBitsNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RandomBitsNodeEnd(builder)
