# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RepeatNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RepeatNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRepeatNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RepeatNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RepeatNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RepeatNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RepeatNode
    def Repeats(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RepeatNode
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RepeatNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    RepeatNodeStart(builder)

def RepeatNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    RepeatNodeAddX(builder, x)

def RepeatNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    RepeatNodeAddOut(builder, out)

def RepeatNodeAddRepeats(builder, repeats):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(repeats), 0)

def AddRepeats(builder, repeats):
    RepeatNodeAddRepeats(builder, repeats)

def RepeatNodeAddAxis(builder, axis):
    builder.PrependInt32Slot(3, axis, 0)

def AddAxis(builder, axis):
    RepeatNodeAddAxis(builder, axis)

def RepeatNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RepeatNodeEnd(builder)
