# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RollNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RollNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRollNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RollNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RollNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RollNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RollNode
    def Shift(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RollNode
    def ShiftLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RollNode
    def ShiftIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RollNode
    def Axes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RollNode
    def AxesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RollNode
    def AxesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RollNode
    def AxesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def RollNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    RollNodeStart(builder)

def RollNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    RollNodeAddX(builder, x)

def RollNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    RollNodeAddOut(builder, out)

def RollNodeAddShift(builder, shift):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(shift), 0)

def AddShift(builder, shift):
    RollNodeAddShift(builder, shift)

def RollNodeStartShiftVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShiftVector(builder, numElems):
    return RollNodeStartShiftVector(builder, numElems)

def RollNodeAddAxes(builder, axes):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(axes), 0)

def AddAxes(builder, axes):
    RollNodeAddAxes(builder, axes)

def RollNodeStartAxesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAxesVector(builder, numElems):
    return RollNodeStartAxesVector(builder, numElems)

def RollNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RollNodeEnd(builder)
