# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RopeNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RopeNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRopeNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RopeNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RopeNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Dims(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RopeNode
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.VidOrTid import VidOrTid
            obj = VidOrTid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Freqs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Traditional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # RopeNode
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 500000.0

    # RopeNode
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def RopeNodeStart(builder):
    builder.StartObject(8)

def Start(builder):
    RopeNodeStart(builder)

def RopeNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    RopeNodeAddX(builder, x)

def RopeNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    RopeNodeAddOut(builder, out)

def RopeNodeAddDims(builder, dims):
    builder.PrependInt32Slot(2, dims, 0)

def AddDims(builder, dims):
    RopeNodeAddDims(builder, dims)

def RopeNodeAddOffset(builder, offset):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(offset), 0)

def AddOffset(builder, offset):
    RopeNodeAddOffset(builder, offset)

def RopeNodeAddFreqs(builder, freqs):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(freqs), 0)

def AddFreqs(builder, freqs):
    RopeNodeAddFreqs(builder, freqs)

def RopeNodeAddTraditional(builder, traditional):
    builder.PrependBoolSlot(5, traditional, 0)

def AddTraditional(builder, traditional):
    RopeNodeAddTraditional(builder, traditional)

def RopeNodeAddBase(builder, base):
    builder.PrependFloat32Slot(6, base, 500000.0)

def AddBase(builder, base):
    RopeNodeAddBase(builder, base)

def RopeNodeAddScale(builder, scale):
    builder.PrependFloat32Slot(7, scale, 1.0)

def AddScale(builder, scale):
    RopeNodeAddScale(builder, scale)

def RopeNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RopeNodeEnd(builder)
