# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoundNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoundNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoundNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RoundNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoundNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RoundNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RoundNode
    def Decimals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RoundNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    RoundNodeStart(builder)

def RoundNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    RoundNodeAddX(builder, x)

def RoundNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    RoundNodeAddOut(builder, out)

def RoundNodeAddDecimals(builder, decimals):
    builder.PrependInt32Slot(2, decimals, 0)

def AddDecimals(builder, decimals):
    RoundNodeAddDecimals(builder, decimals)

def RoundNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoundNodeEnd(builder)
