# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScanNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScanNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScanNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScanNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScanNode
    def Originals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScanNode
    def OriginalsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScanNode
    def OriginalsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ScanNode
    def Sliced(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScanNode
    def SlicedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScanNode
    def SlicedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ScanNode
    def Outputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScanNode
    def OutputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScanNode
    def OutputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ScanNode
    def Carry(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScanNode
    def CarryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScanNode
    def CarryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ScanNode
    def BodyChainIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScanNode
    def ScanAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def ScanNodeStart(builder):
    builder.StartObject(6)

def Start(builder):
    ScanNodeStart(builder)

def ScanNodeAddOriginals(builder, originals):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(originals), 0)

def AddOriginals(builder, originals):
    ScanNodeAddOriginals(builder, originals)

def ScanNodeStartOriginalsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOriginalsVector(builder, numElems):
    return ScanNodeStartOriginalsVector(builder, numElems)

def ScanNodeAddSliced(builder, sliced):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sliced), 0)

def AddSliced(builder, sliced):
    ScanNodeAddSliced(builder, sliced)

def ScanNodeStartSlicedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSlicedVector(builder, numElems):
    return ScanNodeStartSlicedVector(builder, numElems)

def ScanNodeAddOutputs(builder, outputs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)

def AddOutputs(builder, outputs):
    ScanNodeAddOutputs(builder, outputs)

def ScanNodeStartOutputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputsVector(builder, numElems):
    return ScanNodeStartOutputsVector(builder, numElems)

def ScanNodeAddCarry(builder, carry):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(carry), 0)

def AddCarry(builder, carry):
    ScanNodeAddCarry(builder, carry)

def ScanNodeStartCarryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCarryVector(builder, numElems):
    return ScanNodeStartCarryVector(builder, numElems)

def ScanNodeAddBodyChainIdx(builder, bodyChainIdx):
    builder.PrependInt32Slot(4, bodyChainIdx, 0)

def AddBodyChainIdx(builder, bodyChainIdx):
    ScanNodeAddBodyChainIdx(builder, bodyChainIdx)

def ScanNodeAddScanAxis(builder, scanAxis):
    builder.PrependInt32Slot(5, scanAxis, 1)

def AddScanAxis(builder, scanAxis):
    ScanNodeAddScanAxis(builder, scanAxis)

def ScanNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScanNodeEnd(builder)
