# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScatterAddNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScatterAddNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScatterAddNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScatterAddNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScatterAddNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScatterAddNode
    def Indices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScatterAddNode
    def Updates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScatterAddNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScatterAddNode
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ScatterAddNodeStart(builder):
    builder.StartObject(5)

def Start(builder):
    ScatterAddNodeStart(builder)

def ScatterAddNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    ScatterAddNodeAddX(builder, x)

def ScatterAddNodeAddIndices(builder, indices):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def AddIndices(builder, indices):
    ScatterAddNodeAddIndices(builder, indices)

def ScatterAddNodeAddUpdates(builder, updates):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(updates), 0)

def AddUpdates(builder, updates):
    ScatterAddNodeAddUpdates(builder, updates)

def ScatterAddNodeAddOut(builder, out):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    ScatterAddNodeAddOut(builder, out)

def ScatterAddNodeAddAxis(builder, axis):
    builder.PrependInt32Slot(4, axis, 0)

def AddAxis(builder, axis):
    ScatterAddNodeAddAxis(builder, axis)

def ScatterAddNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScatterAddNodeEnd(builder)
