# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShapeDim(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShapeDim()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShapeDim(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShapeDim
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShapeDim
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # ShapeDim
    def MinValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShapeDim
    def MaxValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def ShapeDimStart(builder):
    builder.StartObject(3)

def Start(builder):
    ShapeDimStart(builder)

def ShapeDimAddValue(builder, value):
    builder.PrependInt32Slot(0, value, -1)

def AddValue(builder, value):
    ShapeDimAddValue(builder, value)

def ShapeDimAddMinValue(builder, minValue):
    builder.PrependInt32Slot(1, minValue, 0)

def AddMinValue(builder, minValue):
    ShapeDimAddMinValue(builder, minValue)

def ShapeDimAddMaxValue(builder, maxValue):
    builder.PrependInt32Slot(2, maxValue, -1)

def AddMaxValue(builder, maxValue):
    ShapeDimAddMaxValue(builder, maxValue)

def ShapeDimEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShapeDimEnd(builder)
