# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SliceUpdateNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SliceUpdateNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSliceUpdateNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SliceUpdateNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SliceUpdateNode
    def Dst(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Update(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliceUpdateNode
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def SliceUpdateNodeStart(builder):
    builder.StartObject(7)

def Start(builder):
    SliceUpdateNodeStart(builder)

def SliceUpdateNodeAddDst(builder, dst):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dst), 0)

def AddDst(builder, dst):
    SliceUpdateNodeAddDst(builder, dst)

def SliceUpdateNodeAddUpdate(builder, update):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(update), 0)

def AddUpdate(builder, update):
    SliceUpdateNodeAddUpdate(builder, update)

def SliceUpdateNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    SliceUpdateNodeAddOut(builder, out)

def SliceUpdateNodeAddAxis(builder, axis):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(axis), 0)

def AddAxis(builder, axis):
    SliceUpdateNodeAddAxis(builder, axis)

def SliceUpdateNodeAddStart(builder, start):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(start), 0)

def AddStart(builder, start):
    SliceUpdateNodeAddStart(builder, start)

def SliceUpdateNodeAddStop(builder, stop):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(stop), 0)

def AddStop(builder, stop):
    SliceUpdateNodeAddStop(builder, stop)

def SliceUpdateNodeAddStep(builder, step):
    builder.PrependInt32Slot(6, step, 1)

def AddStep(builder, step):
    SliceUpdateNodeAddStep(builder, step)

def SliceUpdateNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SliceUpdateNodeEnd(builder)
