# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SoftmaxNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SoftmaxNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSoftmaxNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SoftmaxNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SoftmaxNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SoftmaxNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SoftmaxNode
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SoftmaxNode
    def Precise(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SoftmaxNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    SoftmaxNodeStart(builder)

def SoftmaxNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    SoftmaxNodeAddX(builder, x)

def SoftmaxNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    SoftmaxNodeAddOut(builder, out)

def SoftmaxNodeAddAxis(builder, axis):
    builder.PrependInt32Slot(2, axis, 0)

def AddAxis(builder, axis):
    SoftmaxNodeAddAxis(builder, axis)

def SoftmaxNodeAddPrecise(builder, precise):
    builder.PrependBoolSlot(3, precise, 0)

def AddPrecise(builder, precise):
    SoftmaxNodeAddPrecise(builder, precise)

def SoftmaxNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SoftmaxNodeEnd(builder)
