# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TensorMeta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TensorMeta()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTensorMeta(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TensorMeta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TensorMeta
    def Shape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch.backends.mlx.serialization._generated.mlx_delegate.ShapeDim import ShapeDim
            obj = ShapeDim()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TensorMeta
    def ShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TensorMeta
    def ShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TensorMeta
    def ScalarType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TensorMeta
    def DimOrder(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TensorMeta
    def DimOrderAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TensorMeta
    def DimOrderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TensorMeta
    def DimOrderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def TensorMetaStart(builder):
    builder.StartObject(3)

def Start(builder):
    TensorMetaStart(builder)

def TensorMetaAddShape(builder, shape):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)

def AddShape(builder, shape):
    TensorMetaAddShape(builder, shape)

def TensorMetaStartShapeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShapeVector(builder, numElems):
    return TensorMetaStartShapeVector(builder, numElems)

def TensorMetaAddScalarType(builder, scalarType):
    builder.PrependInt8Slot(1, scalarType, 0)

def AddScalarType(builder, scalarType):
    TensorMetaAddScalarType(builder, scalarType)

def TensorMetaAddDimOrder(builder, dimOrder):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(dimOrder), 0)

def AddDimOrder(builder, dimOrder):
    TensorMetaAddDimOrder(builder, dimOrder)

def TensorMetaStartDimOrderVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDimOrderVector(builder, numElems):
    return TensorMetaStartDimOrderVector(builder, numElems)

def TensorMetaEnd(builder):
    return builder.EndObject()

def End(builder):
    return TensorMetaEnd(builder)
