# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WhereNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WhereNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWhereNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WhereNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WhereNode
    def Condition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WhereNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WhereNode
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WhereNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WhereNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    WhereNodeStart(builder)

def WhereNodeAddCondition(builder, condition):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(condition), 0)

def AddCondition(builder, condition):
    WhereNodeAddCondition(builder, condition)

def WhereNodeAddX(builder, x):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    WhereNodeAddX(builder, x)

def WhereNodeAddY(builder, y):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(y), 0)

def AddY(builder, y):
    WhereNodeAddY(builder, y)

def WhereNodeAddOut(builder, out):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    WhereNodeAddOut(builder, out)

def WhereNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return WhereNodeEnd(builder)
