load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("executorch")

fbcode_target(_kind = cpp_unittest,
    name = "test_common_shims",
    srcs = [
        "test_common_shims.cpp",
    ],
    headers = [
        "utils.h",
    ],
    deps = [
        "//executorch/backends/aoti:common_shims",
        "//executorch/extension/tensor:tensor",
        "//executorch/runtime/core:core",
        "//executorch/runtime/platform:platform",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
        "//executorch/runtime/core/exec_aten:lib",
        "//executorch/extension/tensor:tensor",
    ],
)
