load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_recipes",
    srcs = [
        "__init__.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/export:recipe_registry",
        ":xnnpack_recipe_provider",
        ":xnnpack_recipe_types",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_recipe_provider",
    srcs = [
        "xnnpack_recipe_provider.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/export:lib",
        "//executorch/runtime:runtime",  # @manual
        "//executorch/backends/xnnpack/quantizer:xnnpack_quantizer",
        "//executorch/backends/xnnpack/partition:xnnpack_partitioner",
        ":xnnpack_recipe_types",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_recipe_types",
    srcs = [
        "xnnpack_recipe_types.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/export:recipe",
    ],
)
