load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load(":targets.bzl", "define_common_targets")

oncall("executorch")
non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/backends/xnnpack/serialization/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_schema",
    srcs = [
        "xnnpack_graph_schema.py",
    ],
    visibility = ["PUBLIC"],
)

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_serializer",
    srcs = [
        "xnnpack_graph_serialize.py",
    ],
    resources = [
        "schema.fbs",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":xnnpack_schema",
        "//executorch/exir/_serialize:lib",
    ],
)
