load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_test,
    name = "test",
    srcs = ["test_export.py"],
    visibility = ["//executorch/extension/training/examples/XOR/test/..."],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/extension/training:lib",
        "//executorch/extension/training/examples/XOR:export_model_lib",
    ],
)
