load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(
    _kind = runtime.cxx_test,
    name = "executor_utils_test",
    srcs = ["executor_utils_test.cpp"],
    deps = ["//executorch/extension/llm/batching:executor_utils"],
)
