load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl.

load(":targets.bzl", "define_common_targets")

oncall("executorch")

fbcode_target(_kind = define_common_targets,)
