/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

apply plugin: 'kotlin'
apply plugin: 'java-library'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'com.diffplug.spotless'

spotless {
    kotlin {
        target '**/*.kt'
        ktfmt()
    }
}

def execuTorchVersion = System.properties['execuTorchVersion']

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets {
    main {
        kotlin {
            srcDirs = ['../android/executorch_android/src/main/java', 'src/main/java']
            exclude { element ->
                element.file.path.contains("executorch_android") && element.file.name == "Log.kt"
            }
        }
    }
    test {
        kotlin {
            srcDirs = ['../android/executorch_android/src/test/java', 'src/test/java']
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'com.facebook.fbjni:fbjni-java-only:0.7.0'
    implementation 'com.facebook.soloader:nativeloader:0.10.5'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${libs.versions.kotlin.get()}"
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.assertj:assertj-core:3.27.2'
    testImplementation "org.jetbrains.kotlin:kotlin-test:${libs.versions.kotlin.get()}"
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += ["-Xjvm-default=all"]
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates("org.pytorch", "executorch-jvm", execuTorchVersion ? execuTorchVersion : "1.2.0-SNAPSHOT")

    pom {
        name = "ExecuTorch JVM"
        description = "ExecuTorch Java/Kotlin bindings for standard desktop JVM (Linux, macOS, Windows)"
        inceptionYear = "2024"
        url = "https://github.com/pytorch/executorch/"
        licenses {
            license {
                name = "BSD 3-Clause"
                url = "https://github.com/pytorch/executorch/blob/main/LICENSE"
                distribution = "https://github.com/pytorch/executorch/blob/main/LICENSE"
            }
        }
        developers {
            developer {
                id = "pytorch"
                name = "pytorch"
                url = "https://github.com/pytorch/executorch/"
            }
        }
        scm {
            url = "https://github.com/pytorch/executorch.git"
            connection = "scm:git:https://github.com/pytorch/executorch"
            developerConnection = "scm:git:git@github.com:pytorch/executorch.git"
        }
    }
}
