load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_test,
    name = "test_backend_ops",
    srcs = [
        "test_backend_ops.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir/dialects:lib",
        "//executorch/exir/dialects/backend:lib",
        "//executorch/exir/dialects/edge:lib",
    ],
)
