base:
  model_class: phi_4_mini
  metadata: '{"get_bos_id":199999, "get_eos_ids":[200020,199999]}'

model:
  use_kv_cache: True
  use_sdpa_with_kv_cache: True
  dtype_override: fp32

backend:
  xnnpack:
    enabled: True