# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import os
import subprocess
import sys
from pathlib import Path


_FLATC_ARGS = [
    "--python",
    "--python-typing",
    "--gen-object-api",
    "--gen-mutable",
    "-o",
    "devtools/bundled_program/serialize/generated",
]
_PACKAGE_PREFIX = "executorch.devtools.bundled_program.serialize.generated"
_NAMESPACE_PACKAGES = ("bundled_program_flatbuffer", "executorch_flatbuffer")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _flatc_executable() -> str:
    return os.getenv("FLATC_EXECUTABLE", "flatc")


def _run_flatc(repo_root: Path) -> None:
    schema_dir = repo_root / "devtools" / "bundled_program" / "schema"
    schema_files = [
        schema_dir / "bundled_program_schema.fbs",
        schema_dir / "scalar_type.fbs",
    ]
    output_dir = repo_root / "devtools" / "bundled_program" / "serialize" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    cmd = [_flatc_executable(), *_FLATC_ARGS, *[str(path) for path in schema_files]]
    subprocess.run(cmd, check=True, cwd=repo_root)


def _rewrite_import_line(line: str, package_name: str) -> str:
    package_import = f"from {_PACKAGE_PREFIX} import {package_name}"
    from_import_prefix = f"from {_PACKAGE_PREFIX}.{package_name} import "

    if f"from {package_name}" in line:
        line = line.replace(
            f"from {package_name}", f"from {_PACKAGE_PREFIX}.{package_name}"
        )
    stripped = line.lstrip()
    if stripped.startswith(f"import {package_name}."):
        indent = line[: len(line) - len(stripped)]
        remainder = stripped[len(f"import {package_name}.") :]
        return f"{indent}{from_import_prefix}{remainder}"
    if stripped.startswith(f"import {package_name}"):
        indent = line[: len(line) - len(stripped)]
        remainder = stripped[len(f"import {package_name}") :]
        return f"{indent}{package_import}{remainder}"
    return line


def _first_import_line(lines: list[str]) -> int:
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("from __future__ import"):
            continue
        return index
    return len(lines)


def _ensure_package_import(contents: str, package_name: str) -> str:
    package_import = f"from {_PACKAGE_PREFIX} import {package_name}"
    if f"{package_name}." not in contents or package_import in contents:
        return contents

    lines = contents.splitlines(keepends=True)
    lines.insert(_first_import_line(lines), package_import + "\n")
    return "".join(lines)


def _rewrite_imports(repo_root: Path) -> int:
    generated_dir = (
        repo_root / "devtools" / "bundled_program" / "serialize" / "generated"
    )
    updated = 0
    for package_name in _NAMESPACE_PACKAGES:
        package_dir = generated_dir / package_name
        if not package_dir.is_dir():
            raise SystemExit(f"Expected generated directory at {package_dir}")

        for path in sorted(package_dir.rglob("*.py")):
            contents = path.read_text(encoding="utf-8")
            new_contents = "".join(
                _rewrite_import_line(line, package_name)
                for line in contents.splitlines(keepends=True)
            )
            new_contents = _ensure_package_import(new_contents, package_name)

            if new_contents != contents:
                path.write_text(new_contents, encoding="utf-8")
                updated += 1
    return updated


def _write_init_files(repo_root: Path) -> int:
    generated_dir = (
        repo_root / "devtools" / "bundled_program" / "serialize" / "generated"
    )
    generated_dir.mkdir(parents=True, exist_ok=True)

    top_init = generated_dir / "__init__.py"
    top_init_contents = [
        "# automatically generated by "
        "devtools/bundled_program/serialize/generate_bundled_program.py, "
        "do not modify",
        "",
        "from . import bundled_program_flatbuffer",
        "from . import executorch_flatbuffer",
        "",
        "__all__ = [",
        '    "bundled_program_flatbuffer",',
        '    "executorch_flatbuffer",',
        "]",
        "",
    ]
    top_init.write_text("\n".join(top_init_contents), encoding="utf-8")

    updated = 1
    for package_name in _NAMESPACE_PACKAGES:
        package_dir = generated_dir / package_name
        if not package_dir.is_dir():
            raise SystemExit(f"Expected generated directory at {package_dir}")

        module_names = sorted(
            path.stem for path in package_dir.glob("*.py") if path.name != "__init__.py"
        )
        init_file = package_dir / "__init__.py"
        init_contents = [
            "# automatically generated by "
            "devtools/bundled_program/serialize/generate_bundled_program.py, "
            "do not modify",
            "",
        ]
        init_contents.extend(f"from . import {name}" for name in module_names)
        init_contents.extend(
            [
                "",
                "__all__ = [",
                *[f'    "{name}",' for name in module_names],
                "]",
                "",
            ]
        )
        init_file.write_text("\n".join(init_contents), encoding="utf-8")
        updated += 1
    return updated


def main() -> int:
    repo_root = _repo_root()
    _run_flatc(repo_root)
    updated = _rewrite_imports(repo_root)
    updated += _write_init_files(repo_root)
    print(f"Updated {updated} file(s).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
