load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load(
    "@fbsource//tools/build_defs:default_platform_defs.bzl",
    "ANDROID",
)
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")


non_fbcode_target(_kind = runtime.cxx_library,
    name = "neuron_backend",
    srcs = [
        "NeuronBackend.cpp",
        "NeuronBufferAllocator.cpp",
        "NeuronExecutor.cpp",
    ],
    headers = glob([
        "include/**/*.h",
    ]),
    include_directories = ["include"],
    deps = [
        "fbsource//third-party/mediatek/neuropilot-express-sdk:runtime_api",
        "//executorch/runtime/backend:interface",
        "//executorch/runtime/core:memory_allocator",
        "//executorch/runtime/executor:pte_data_map",
    ],
    define_static_target = True,
    link_whole = True,
    platforms = [ANDROID],
    visibility = ["PUBLIC"],
)

# !!!! fbcode/executorch/backends/mediatek/runtime/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

