# Copyright 2026 Arm Limited and/or its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("executorch")

fbcode_target(
    _kind = python_library,
    name = "quantizer_reporter",
    srcs = [
        "quantizer_reporter.py",
    ],
    deps = [
        "//caffe2:torch",
        "//pytorch/ao:torchao",
        "fbsource//third-party/pypi/tabulate:tabulate",
    ],
)

fbcode_target(
    _kind = python_library,
    name = "cmsis_nn",
    srcs = [
        "library/__init__.py",
        "library/cmsis_nn.py",
    ],
    deps = [
        "fbsource//third-party/cmsis-nn:cmsis_nn_py",
    ],
)

fbcode_target(
    _kind = python_library,
    name = "target_config",
    srcs = [
        "target_config.py",
    ],
    deps = [
        ":cmsis_nn",
    ],
)
