load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
#
#  Copyright (c) 2023 Apple Inc. All rights reserved.
#  Provided subject to the LICENSE file in the top level directory.
#

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load("@fbsource//tools/build_defs:default_platform_defs.bzl", "APPLE")
load(":targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,
    is_xplat = True,
    platforms = [APPLE],
)

# !!!! fbcode/executorch/backends/apple/mps/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

#
#  Copyright (c) 2023 Apple Inc. All rights reserved.
#  Provided subject to the LICENSE file in the top level directory.
#

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "backend",
    srcs = [
        "__init__.py",
        "mps_preprocess.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":operators",
        ":serialization",
        ":utils",
        "//caffe2:torch",
        "//executorch/exir/backend:backend_details",
        "//executorch/exir/backend:compile_spec_schema",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "operators",
    srcs = glob([
        "operators/*.py",
    ]),
    deps = [
        ":serialization",
        ":utils",
        "//executorch/backends/transforms:lib",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "partitioner",
    srcs = glob([
        "partition/*.py",
    ]),
    visibility = ["PUBLIC"],
    deps = [
        ":backend",
        "//caffe2:torch",
        "//executorch/exir/backend:compile_spec_schema",
        "//executorch/exir/backend:partitioner",
        "//executorch/exir/backend/canonical_partitioners:canonical_partitioner_lib",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "serialization",
    srcs = glob([
        "serialization/*.py",
    ]),
    resources = [
        "serialization/schema.fbs",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "utils",
    srcs = glob([
        "utils/*.py",
    ]),
    deps = [
        ":serialization",
        "//caffe2:torch",
        "//executorch/exir:lib",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test",
    srcs = glob([
        "test/*.py",
    ]),
    deps = [
        ":backend",
        ":partitioner",
        "//caffe2:torch",
        "//executorch/examples/models:models",
        "//executorch/exir/tests:models",
        "//executorch/extension/export_util:export_util",
        "//executorch/devtools:lib",
        "//executorch/devtools/bundled_program/serialize:lib",
        "fbsource//third-party/pypi/pytest:pytest",
    ],
)
