load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "tester",
    srcs = native.glob(["*.py", "stages/*.py"]),
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/exir:graph_module",
    ],
)
