name: 📚 Documentation
description: Report an issue related to https://pytorch.org/executorch/

body:
- type: textarea
  attributes:
    label: 📚 The doc issue
    description: >
      A clear and concise description of what content in https://pytorch.org/executorch/ is an issue. Please include the URL to the page or pages with the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
