load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

oncall("executorch")

# BUCK2 does not require user-defined configurations to set config_setting
# executorch-max-kernel-num-64 could be utilized by Executorch user apps to define the macro MAX_KERNEL_NUM=64
# MAX_KERNEL_NUM macro specifies the max number of kernels that can be registered in Executorch.

fb_native.config_setting(
    name = "executorch-max-kernel-num-64",
    constraint_values = [
        ":max-kernel-num-64",
    ],
    visibility = ["PUBLIC"],
)

fb_native.config_setting(
    name = "executorch-max-kernel-num-128",
    constraint_values = [
        ":max-kernel-num-128",
    ],
    visibility = ["PUBLIC"],
)

fb_native.config_setting(
    name = "executorch-max-kernel-num-256",
    constraint_values = [
        ":max-kernel-num-256",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "executorch-max-kernel-num",
    aliases = {
        "max-kernel-num-64": "64",
        "max-kernel-num-128": "128",
        "max-kernel-num-256": "256",
    },
    default = "unspecified",
    values = [
        "64",
        "128",
        "256",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "executorch-event-tracer",
    aliases = {
        "event-tracer-enabled": "enabled",
    },
    default = "unspecified",
    values = [
        "enabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

fb_native.config_setting(
    name = "executorch-program-verification-disabled",
    constraint_values = [
        ":program-verification-disabled",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "executorch-program-verification",
    aliases = {
        "program-verification-disabled": "disabled",
    },
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

fb_native.config_setting(
    name = "executorch-builtin-function-name-disabled",
    constraint_values = [
        ":builtin-function-name-disabled",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "executorch-builtin-function-name",
    aliases = {
        "builtin-function-name-disabled": "disabled",
    },
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

fb_native.config_setting(
    name = "executorch-et-log-disabled",
    constraint_values = [
        ":et-log-disabled",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "executorch-et-log",
    aliases = {
        "et-log-disabled": "disabled",
    },
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
