load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_library,
    name = "quantizer",
    srcs = [
        "__init__.py",
        "annotator.py",
        "qconfig.py",
        "quantizer.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//pytorch/ao:torchao",
        "//executorch/backends/mediatek/_passes:passes",
    ],
)
