load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "etrecord",
    srcs = [
        "__init__.py",
        "_etrecord.py",
    ],
    deps = [
        "//executorch/devtools/bundled_program:core",
        "//executorch/devtools/bundled_program/schema:bundled_program_schema_py",
        "//executorch/exir:lib",
        "//executorch/exir/emit:emit",
        "//executorch/exir/serde:serialize",
    ],
)
