load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "lib",
    srcs = ["__init__.py"],
    deps = [
        "//executorch/devtools/bundled_program:core",
        "//executorch/devtools/etrecord:etrecord",
        "//executorch/devtools/inspector:lib",
    ],
)
