# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AddScalarNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AddScalarNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAddScalarNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AddScalarNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AddScalarNode
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AddScalarNode
    def B(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mlx_delegate.IntOrVid import IntOrVid
            obj = IntOrVid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AddScalarNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Vid import Vid
            obj = Vid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AddScalarNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    AddScalarNodeStart(builder)

def AddScalarNodeAddA(builder, a):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(a), 0)

def AddA(builder, a):
    AddScalarNodeAddA(builder, a)

def AddScalarNodeAddB(builder, b):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(b), 0)

def AddB(builder, b):
    AddScalarNodeAddB(builder, b)

def AddScalarNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    AddScalarNodeAddOut(builder, out)

def AddScalarNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return AddScalarNodeEnd(builder)
