# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Conv1DNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Conv1DNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConv1DNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Conv1DNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Conv1DNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv1DNode
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv1DNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Conv1DNode
    def Stride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv1DNode
    def Padding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Conv1DNode
    def Dilation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Conv1DNode
    def Groups(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def Conv1DNodeStart(builder):
    builder.StartObject(7)

def Start(builder):
    Conv1DNodeStart(builder)

def Conv1DNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    Conv1DNodeAddX(builder, x)

def Conv1DNodeAddW(builder, w):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(w), 0)

def AddW(builder, w):
    Conv1DNodeAddW(builder, w)

def Conv1DNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    Conv1DNodeAddOut(builder, out)

def Conv1DNodeAddStride(builder, stride):
    builder.PrependInt32Slot(3, stride, 1)

def AddStride(builder, stride):
    Conv1DNodeAddStride(builder, stride)

def Conv1DNodeAddPadding(builder, padding):
    builder.PrependInt32Slot(4, padding, 0)

def AddPadding(builder, padding):
    Conv1DNodeAddPadding(builder, padding)

def Conv1DNodeAddDilation(builder, dilation):
    builder.PrependInt32Slot(5, dilation, 1)

def AddDilation(builder, dilation):
    Conv1DNodeAddDilation(builder, dilation)

def Conv1DNodeAddGroups(builder, groups):
    builder.PrependInt32Slot(6, groups, 1)

def AddGroups(builder, groups):
    Conv1DNodeAddGroups(builder, groups)

def Conv1DNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return Conv1DNodeEnd(builder)
