# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LayerNormNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LayerNormNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLayerNormNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LayerNormNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LayerNormNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LayerNormNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LayerNormNode
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LayerNormNode
    def Bias(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LayerNormNode
    def Eps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def LayerNormNodeStart(builder):
    builder.StartObject(5)

def Start(builder):
    LayerNormNodeStart(builder)

def LayerNormNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    LayerNormNodeAddX(builder, x)

def LayerNormNodeAddOut(builder, out):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    LayerNormNodeAddOut(builder, out)

def LayerNormNodeAddWeight(builder, weight):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(weight), 0)

def AddWeight(builder, weight):
    LayerNormNodeAddWeight(builder, weight)

def LayerNormNodeAddBias(builder, bias):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bias), 0)

def AddBias(builder, bias):
    LayerNormNodeAddBias(builder, bias)

def LayerNormNodeAddEps(builder, eps):
    builder.PrependFloat32Slot(4, eps, 0.0)

def AddEps(builder, eps):
    LayerNormNodeAddEps(builder, eps)

def LayerNormNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return LayerNormNodeEnd(builder)
