# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NamedSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NamedSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNamedSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NamedSlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NamedSlot
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NamedSlot
    def Slot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mlx_delegate.SlotVariant import SlotVariant
            obj = SlotVariant()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def NamedSlotStart(builder):
    builder.StartObject(2)

def Start(builder):
    NamedSlotStart(builder)

def NamedSlotAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NamedSlotAddName(builder, name)

def NamedSlotAddSlot(builder, slot):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(slot), 0)

def AddSlot(builder, slot):
    NamedSlotAddSlot(builder, slot)

def NamedSlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return NamedSlotEnd(builder)
