# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RopeNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RopeNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRopeNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RopeNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RopeNode
    def QIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def KIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def QOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def KOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def HeadDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RopeNode
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Vid import Vid
            obj = Vid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Freqs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RopeNode
    def Traditional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # RopeNode
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RopeNode
    def BaseIsSet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # RopeNode
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def RopeNodeStart(builder):
    builder.StartObject(11)

def Start(builder):
    RopeNodeStart(builder)

def RopeNodeAddQIn(builder, qIn):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(qIn), 0)

def AddQIn(builder, qIn):
    RopeNodeAddQIn(builder, qIn)

def RopeNodeAddKIn(builder, kIn):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kIn), 0)

def AddKIn(builder, kIn):
    RopeNodeAddKIn(builder, kIn)

def RopeNodeAddQOut(builder, qOut):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(qOut), 0)

def AddQOut(builder, qOut):
    RopeNodeAddQOut(builder, qOut)

def RopeNodeAddKOut(builder, kOut):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(kOut), 0)

def AddKOut(builder, kOut):
    RopeNodeAddKOut(builder, kOut)

def RopeNodeAddHeadDim(builder, headDim):
    builder.PrependInt32Slot(4, headDim, 0)

def AddHeadDim(builder, headDim):
    RopeNodeAddHeadDim(builder, headDim)

def RopeNodeAddPos(builder, pos):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    RopeNodeAddPos(builder, pos)

def RopeNodeAddFreqs(builder, freqs):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(freqs), 0)

def AddFreqs(builder, freqs):
    RopeNodeAddFreqs(builder, freqs)

def RopeNodeAddTraditional(builder, traditional):
    builder.PrependBoolSlot(7, traditional, 0)

def AddTraditional(builder, traditional):
    RopeNodeAddTraditional(builder, traditional)

def RopeNodeAddBase(builder, base):
    builder.PrependFloat32Slot(8, base, 0.0)

def AddBase(builder, base):
    RopeNodeAddBase(builder, base)

def RopeNodeAddBaseIsSet(builder, baseIsSet):
    builder.PrependBoolSlot(9, baseIsSet, 0)

def AddBaseIsSet(builder, baseIsSet):
    RopeNodeAddBaseIsSet(builder, baseIsSet)

def RopeNodeAddScale(builder, scale):
    builder.PrependFloat32Slot(10, scale, 1.0)

def AddScale(builder, scale):
    RopeNodeAddScale(builder, scale)

def RopeNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RopeNodeEnd(builder)
