# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SdpaNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SdpaNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSdpaNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SdpaNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SdpaNode
    def Q(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SdpaNode
    def K(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SdpaNode
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SdpaNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SdpaNode
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SdpaNode
    def Mask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SdpaNode
    def Causal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SdpaNodeStart(builder):
    builder.StartObject(7)

def Start(builder):
    SdpaNodeStart(builder)

def SdpaNodeAddQ(builder, q):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(q), 0)

def AddQ(builder, q):
    SdpaNodeAddQ(builder, q)

def SdpaNodeAddK(builder, k):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(k), 0)

def AddK(builder, k):
    SdpaNodeAddK(builder, k)

def SdpaNodeAddV(builder, v):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def AddV(builder, v):
    SdpaNodeAddV(builder, v)

def SdpaNodeAddOut(builder, out):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    SdpaNodeAddOut(builder, out)

def SdpaNodeAddScale(builder, scale):
    builder.PrependFloat32Slot(4, scale, 0.0)

def AddScale(builder, scale):
    SdpaNodeAddScale(builder, scale)

def SdpaNodeAddMask(builder, mask):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(mask), 0)

def AddMask(builder, mask):
    SdpaNodeAddMask(builder, mask)

def SdpaNodeAddCausal(builder, causal):
    builder.PrependBoolSlot(6, causal, 0)

def AddCausal(builder, causal):
    SdpaNodeAddCausal(builder, causal)

def SdpaNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SdpaNodeEnd(builder)
