# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SlotVariant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SlotVariant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSlotVariant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SlotVariant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SlotVariant
    def Idx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SlotVariant
    def SlotType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SlotVariantStart(builder):
    builder.StartObject(2)

def Start(builder):
    SlotVariantStart(builder)

def SlotVariantAddIdx(builder, idx):
    builder.PrependUint32Slot(0, idx, 0)

def AddIdx(builder, idx):
    SlotVariantAddIdx(builder, idx)

def SlotVariantAddSlotType(builder, slotType):
    builder.PrependInt8Slot(1, slotType, 0)

def AddSlotType(builder, slotType):
    SlotVariantAddSlotType(builder, slotType)

def SlotVariantEnd(builder):
    return builder.EndObject()

def End(builder):
    return SlotVariantEnd(builder)
