# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SymSizeNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SymSizeNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSymSizeNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SymSizeNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SymSizeNode
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SymSizeNode
    def Dim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SymSizeNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Vid import Vid
            obj = Vid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SymSizeNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    SymSizeNodeStart(builder)

def SymSizeNodeAddA(builder, a):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(a), 0)

def AddA(builder, a):
    SymSizeNodeAddA(builder, a)

def SymSizeNodeAddDim(builder, dim):
    builder.PrependInt32Slot(1, dim, 0)

def AddDim(builder, dim):
    SymSizeNodeAddDim(builder, dim)

def SymSizeNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    SymSizeNodeAddOut(builder, out)

def SymSizeNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SymSizeNodeEnd(builder)
