# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mlx_delegate

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TakeAlongAxisNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TakeAlongAxisNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTakeAlongAxisNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TakeAlongAxisNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TakeAlongAxisNode
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TakeAlongAxisNode
    def Indices(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TakeAlongAxisNode
    def Out(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from mlx_delegate.Tid import Tid
            obj = Tid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TakeAlongAxisNode
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TakeAlongAxisNodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    TakeAlongAxisNodeStart(builder)

def TakeAlongAxisNodeAddX(builder, x):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    TakeAlongAxisNodeAddX(builder, x)

def TakeAlongAxisNodeAddIndices(builder, indices):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def AddIndices(builder, indices):
    TakeAlongAxisNodeAddIndices(builder, indices)

def TakeAlongAxisNodeAddOut(builder, out):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(out), 0)

def AddOut(builder, out):
    TakeAlongAxisNodeAddOut(builder, out)

def TakeAlongAxisNodeAddAxis(builder, axis):
    builder.PrependInt32Slot(3, axis, 0)

def AddAxis(builder, axis):
    TakeAlongAxisNodeAddAxis(builder, axis)

def TakeAlongAxisNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return TakeAlongAxisNodeEnd(builder)
