load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("executorch")

fbcode_target(_kind = python_unittest,
    name = "prim_ops_test_py",
    srcs = [
        "prim_ops_test.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir/passes:prim_ops_py_registry",
    ],
)

fbcode_target(_kind = runtime.cxx_test,
    name = "prim_ops_test_cpp",
    srcs = [
        "prim_ops_test.cpp",
    ],
    deps = [
        "//executorch/kernels/prim_ops:prim_ops_registry",  # @manual
        "//executorch/kernels/test:test_util",  # @manual
        "//executorch/runtime/core:evalue",  # @manual
        "//executorch/runtime/core/exec_aten:lib",  # @manual
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",  # @manual
        "//executorch/runtime/core/exec_aten/util:tensor_util",  # @manual
        "//executorch/runtime/kernel:kernel_runtime_context",  # @manual
        "//executorch/runtime/kernel:operator_registry",
        "//executorch/runtime/platform:platform",
        "//executorch/test/utils:utils",
    ],
)
