load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "mobilenet_v2",
    srcs = [
        "mobilenet_v2.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/examples/models:model_base",
        "fbsource//third-party/pypi/numpy:numpy",
        "//pytorch/vision:torchvision",  # @manual
    ],
)
