# Copyright 2025-2026 NXP
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import logging

import torch

from executorch.examples.models.mobilenet_v2 import MV2Model
from executorch.examples.nxp.models.nxp_test_base_model import NXPTestBaseModel
from torch.ao.nn.intrinsic.qat import freeze_bn_stats
from torchao.quantization.pt2e import disable_observer
from tqdm import tqdm

log = logging.getLogger(__name__)


class MobileNetV2(NXPTestBaseModel):
    """
    MobileNet V2 model.

    Calibration data for MobileNet V2 can be generated by backends/nxp/tests/prepare_calibration_data_mobilenet_v2.py
    from Imagenette dataset, a subset of 10 classes from ImageNet dataset the model is trained on.
    """

    INPUT_SHAPE = (1, 3, 224, 224)
    IDX_TO_LABEL = {
        0: "bench703",
        1: "English_springer217",
        2: "cassette_player482",
        3: "chain_saw491",
        4: "church497",
        5: "French_horn566",
        6: "garbage_truck569",
        7: "gas_pump571",
        8: "golf_ball574",
        9: "parachute701",
    }

    TRAIN_HYPERPARAMETERS = {
        "num_epochs": 20,
        "batch_size": 64,
        "lr": 1e-4,
        "momentum": 0.9,
        "weight_decay": 1e-5,
    }

    @property
    def input_shape(self):
        return self.INPUT_SHAPE

    @property
    def labels(self):
        return self.IDX_TO_LABEL

    def _init_eager_model(self) -> torch.nn.Module:
        return MV2Model().get_eager_model().eval()

    def train_model_fn(
        self, model, num_epochs=None, batch_size=None, channels_last=False
    ):
        hyperparameters = self.TRAIN_HYPERPARAMETERS
        num_epochs = (
            num_epochs if num_epochs is not None else hyperparameters["num_epochs"]
        )
        batch_size = (
            batch_size if batch_size is not None else hyperparameters["batch_size"]
        )

        torch.manual_seed(42)
        torch.use_deterministic_algorithms(True)

        optimizer = torch.optim.SGD(
            params=model.parameters(),
            lr=hyperparameters["lr"],
            momentum=hyperparameters["momentum"],
            weight_decay=hyperparameters["weight_decay"],
        )
        loss_fn = torch.nn.CrossEntropyLoss()

        log.warning("Starting training...")

        data = self.get_qat_train_inputs(batch_size=batch_size)
        for nepoch in range(num_epochs):
            for samples, labels in tqdm(data):
                if channels_last:
                    samples = samples.to(memory_format=torch.channels_last)

                optimizer.zero_grad()
                outputs = model(samples)
                loss = loss_fn(outputs, labels)
                loss.backward()
                optimizer.step()

            if nepoch >= 15:
                model.apply(disable_observer)

            # freeze BN stats
            if nepoch >= 18:
                model.apply(freeze_bn_stats)

        return model
