# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.
load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(
    _kind = runtime.python_library,
    name = "visualization",
    srcs = [
        "__init__.py",
        "visualization_utils.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/exir/_serialize:lib",
    ],
)

fbcode_target(
    _kind = runtime.python_library,
    name = "test",
    srcs = [
        "visualization_utils_test.py",
    ],
    deps = [
        ":visualization",
    ]
)
