load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load(":targets.bzl", "define_common_targets")

oncall("executorch")

# Define shared targets in targets.bzl. This file contains repository-specific
# targets only.

non_fbcode_target(_kind = define_common_targets)

fbcode_target(_kind = define_common_targets)
