load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load(":targets.bzl", "define_common_targets")

oncall("executorch")

non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/devtools/etdump/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "schema_flatcc",
    srcs = [
        "schema_flatcc.py",
    ],
    visibility = [
        "//executorch/devtools/...",
    ],
    deps = [
        "//executorch/exir:scalar_type",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "serialize",
    srcs = [
        "serialize.py",
    ],
    resources = {
        "//executorch/devtools/etdump:etdump_schema_flatcc.fbs": "etdump_schema_flatcc.fbs",
        "//executorch/schema:scalar_type.fbs": "scalar_type.fbs",
    },
    visibility = [
        "//executorch/devtools/...",
        "//executorch/runtime/test/...",
    ],
    deps = [
        "fbsource//third-party/pypi/setuptools:setuptools",
        ":schema_flatcc",
        "//executorch/exir/_serialize:lib",
    ],
)
