load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "passes",
    srcs = [
      "replace_view_copy_with_view.py",
    ],
    visibility = [
        "//executorch/...",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:pass_base",
    ],
)
