# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load("@fbsource//tools/build_defs:fb_xplat_resource.bzl", "fb_xplat_resource")
load("@fbsource//tools/build_defs:fb_xplat_cxx_test.bzl", "fb_xplat_cxx_test")
load("@fbsource//tools/build_defs:platform_defs.bzl", "APPLE", "ANDROID", "CXX", "IOS", "MACOSX")

oncall("executorch")

fb_xplat_resource(
    name = "resources",
    srcs = [
        "resources/test_tiktoken_tokenizer.model",
    ],
    dirs = [],
    files = [
        "resources/test_tiktoken_tokenizer.model",
    ],
    apple_sdks = (IOS, MACOSX),
    platforms = (APPLE, ANDROID, CXX),
    visibility = ["PUBLIC"],
)

fb_xplat_cxx_test(
    name = "test_tiktoken",
    srcs = [
        "test_tiktoken.cpp",
    ],
    deps = [
        ":resources",
        "//xplat/common/testing/utils:TestResourceUtils",
        "//xplat/executorch/examples/models/llama/tokenizer:tiktoken",
    ],
    test_resource = ":resources",
    preprocessor_flags = ["-DEXECUTORCH_FB_BUCK"],
)
