load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//xplat/executorch/backends/qualcomm/qnn_version.bzl", "get_qnn_library_version")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "models",
    srcs = ["models.py"],
    deps = [
        "//caffe2:torch",
    ]
)

# Test targets have transitive deps (caffe2, torchvision, torchaudio, etc.)
# that are not available in OSS Buck builds.
fbcode_target(_kind = runtime.python_library,
    name = "test_qnn_delegate",
    srcs = [
        "test_qnn_delegate.py",
        "utils.py",
    ],
    # env = {
    #     "LD_LIBRARY_PATH": "$(location fbsource//third-party/qualcomm/qnn/qnn-{0}:qnn_offline_compile_libs)".format(get_qnn_library_version()),
    # },
    deps = [
        ":models",
        "//caffe2:torch",
        "//caffe2/functorch:functorch_src",
        "//executorch/exir/backend:partitioner",
        "//executorch/exir/dialects:lib",
        "//executorch/extension/pytree:pylib",
        "//executorch/backends/qualcomm/partition:partition",
        "//executorch/backends/qualcomm/quantizer:quantizer",
        "//executorch/backends/qualcomm/serialization:serialization",
        "//executorch/backends/qualcomm/utils:utils",
        "//executorch/devtools:lib",
        "//executorch/examples/qualcomm:utils",
        "//executorch/backends/qualcomm:export_utils",
        "//executorch/backends/qualcomm/debugger:utils",
        "//executorch/backends/qualcomm/debugger:qnn_intermediate_debugger",
    ] + ([] if runtime.is_oss else [
        # These deps have pre-existing issues in OSS Buck:
        # portable_lib: shim//build_defs/cpp_python_extension.bzl missing
        # models: examples/models/BUCK uses raw python_library (no dep patching)
        "//executorch/extension/pybindings:portable_lib",  # @manual
        "//executorch/examples/models:models",
    ]),
)

fbcode_target(_kind = runtime.python_library,
    name = "tester",
    srcs = [
        "tester.py",
    ],
    deps = [
        ":test_qnn_delegate"
    ]
)

fbcode_target(_kind = runtime.python_test,
    name = "test_passes",
    srcs = [
        "test_passes.py",
    ],
    deps = [
        ":models",
        "fbsource//third-party/pypi/expecttest:expecttest",  # @manual
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/exir:debug_handle_utils",
        "//executorch/backends/qualcomm/_passes:passes",
        "//executorch/backends/qualcomm/partition:partition",
        "//executorch/backends/qualcomm/serialization:serialization",
        "//executorch/backends/qualcomm/utils:utils",
        "//executorch/backends/qualcomm/builders:builders",
    ] + ([] if runtime.is_oss else [
        "//executorch/examples/models/llama:transformer_modules",
        "//executorch/examples/qualcomm/oss_scripts/llama:masking_utils",
        "//executorch/examples/qualcomm/oss_scripts/llama:static_llama",
    ]),
)
