[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
py-modules = []

[project]
name = "executorchcoreml"
version = "0.0.1"

# Python dependencies required for development
dependencies=[
    "pybind11",
    "numpy",
]
