load("@fbsource//tools/build_defs:platform_defs.bzl", "CXX")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("odai_jarvis")

runtime.cxx_test(
    name = "test_op_add",
    srcs = ["test_op_add.cpp"],
    platforms = CXX,
    deps = [
        "//executorch/backends/cadence/fused_quant:op_add",
        "//executorch/kernels/test:gtest_utils",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
    ],
)

runtime.cxx_test(
    name = "test_op_mul",
    srcs = ["test_op_mul.cpp"],
    platforms = CXX,
    deps = [
        "//executorch/backends/cadence/fused_quant:op_mul",
        "//executorch/kernels/test:gtest_utils",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
    ],
)

runtime.cxx_test(
    name = "test_op_relu",
    srcs = ["test_op_relu.cpp"],
    platforms = CXX,
    deps = [
        "//executorch/backends/cadence/fused_quant:op_relu",
        "//executorch/kernels/test:gtest_utils",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
    ],
)

runtime.cxx_test(
    name = "test_op_hardswish",
    srcs = ["test_op_hardswish.cpp"],
    platforms = CXX,
    deps = [
        "//executorch/backends/cadence/fused_quant:op_hardswish",
        "//executorch/kernels/test:gtest_utils",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
    ],
)

runtime.cxx_test(
    name = "test_op_bmm",
    srcs = ["test_op_bmm.cpp"],
    platforms = CXX,
    deps = [
        "//executorch/backends/cadence/fused_quant:op_bmm",
        "//executorch/kernels/test:gtest_utils",
        "//executorch/runtime/core/exec_aten/testing_util:tensor_util",
    ],
)
