# Copyright 2023-2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
"""Import and register Arm TOSA operator visitors.

Importing this package loads all visitor modules so their classes can be
registered via decorators and discovered at runtime.

"""

from . import (  # noqa
    node_visitor,
    op_amax,
    op_amin,
    op_any,
    op_cat,
    op_cond_if,
    op_flip,
    op_permute,
    op_repeat,
    op_sum,
    op_to_dim_order_copy,
    op_tosa_abs,
    op_tosa_add,
    op_tosa_argmax,
    op_tosa_avg_pool2d,
    op_tosa_avg_pool2d_adaptive,
    op_tosa_binary_ops,
    op_tosa_bitwise_not,
    op_tosa_cast_to_block_scaled,
    op_tosa_ceil,
    op_tosa_clamp,
    op_tosa_clz,
    op_tosa_conv2d,
    op_tosa_conv2d_block_scaled,
    op_tosa_conv3d,
    op_tosa_cos,
    op_tosa_custom,
    op_tosa_depthwise_conv2d,
    op_tosa_eq,
    op_tosa_erf,
    op_tosa_exp,
    op_tosa_fft,
    op_tosa_floor,
    op_tosa_gather,
    op_tosa_ge,
    op_tosa_gt,
    op_tosa_identity,
    op_tosa_log,
    op_tosa_logical_not,
    op_tosa_matmul,
    op_tosa_matmul_t_block_scaled,
    op_tosa_max_pool2d,
    op_tosa_max_pool2d_adaptive,
    op_tosa_maximum,
    op_tosa_minimum,
    op_tosa_mul,
    op_tosa_neg,
    op_tosa_pad,
    op_tosa_pow,
    op_tosa_reciprocal,
    op_tosa_rescale,
    op_tosa_resize,
    op_tosa_rshift_tensor,
    op_tosa_rsqrt,
    op_tosa_scatter,
    op_tosa_shapes,
    op_tosa_sigmoid,
    op_tosa_sin,
    op_tosa_slice,
    op_tosa_sub,
    op_tosa_table,
    op_tosa_tanh,
    op_tosa_transpose_conv2d,
    op_view,
    op_where,
    op_while,
)
