load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("executorch")

fbcode_target(_kind = python_unittest,
    name = "test_model_factory",
    srcs = [
        "test_model_factory.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/examples/models:models",
    ],
)
