# add this empty BUCK file to unblock landing. Without this, we get land error:
#   "No build file at xplat/executorch/exir/dialects/backend/BUCK when resolving target fbsource//xplat/executorch/exir/dialects/backend:."

oncall("executorch")
