load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("executorch")

fbcode_target(_kind = python_unittest,
    name = "test_delegation_info",
    srcs = [
        "test_delegation_info.py",
    ],
    deps = [
        "fbsource//third-party/pypi/pandas:pandas",
        "//caffe2:torch",
        "//executorch/devtools/backend_debug:delegation_info",
        "//executorch/exir:lib",
        "//executorch/exir/backend/test:op_partitioner_demo",
    ],
)
