# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")

oncall("executorch")

load(":targets.bzl", "define_common_targets")

non_fbcode_target(_kind = define_common_targets)

fbcode_target(_kind = define_common_targets)
