/* Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* This is an example ExecuTorch runner for Espressif ESP32 and ESP32-S3 chips.
 * It is inspired by the Arm Cortex-M example runner and adapted for the
 * ESP-IDF build system and ESP32 memory architecture.
 *
 * Some defines used to configure the code:
 *
 * ET_ESP_METHOD_ALLOCATOR_POOL_SIZE      - Size of memory area used when
 *                                          setting up the model.
 * ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE - Size of memory area used when
 *                                           running inferences (scratch).
 * ET_NUM_INFERENCES  - Number of times to run the inference.
 * ET_LOG_DUMP_INPUT  - Control if you want input to be dumped to the log.
 * ET_LOG_DUMP_OUTPUT - Control if you want output to be dumped to the log.
 *
 * Devtool BundleIO: Use Bundle PTE with input and reference output included
 * to check if it matches.
 *
 * ET_BUNDLE_IO       - Build in Devtools BundleIO support. Makes it possible
 *                      to use bpte with bundled input and output ref data.
 *   ET_ATOL          - The atol used to compare output and ref data.
 *   ET_RTOL          - The rtol used to compare output and ref data.
 *
 * Devtools ETDump: Speed and dumping output
 *
 * ET_EVENT_TRACER_ENABLED       - Build in Devtools ETDump event trace code
 *                                 to generate cycle data.
 * ET_DUMP_OUTPUTS               - Collect and print outputs as a base64
 *                                 buffer in the log.
 * ET_DUMP_INTERMEDIATE_OUTPUTS  - Collect and print intermediate outputs.
 * ET_DEBUG_BUFFER_SIZE          - Override size of memory area used by
 *                                 ET_DUMP_OUTPUTS / ET_DUMP_INTERMEDIATE_OUTPUTS.
 *
 * ESP32 Memory Notes:
 *   - ESP32 has ~520KB internal SRAM, optionally 4-8MB PSRAM.
 *   - ESP32-S3 has ~512KB internal SRAM, optionally 2-32MB PSRAM (octal).
 *   - For larger models, PSRAM is required. Memory pools are placed in
 *     PSRAM when available using EXT_RAM_BSS_ATTR.
 *   - The model .pte data is converted to a C array and compiled in,
 *     or can be loaded from SPIFFS/LittleFS/SD card filesystem.
 *
 * FILESYSTEM_LOAD - When defined, the runner will load the .pte model
 *                   from the filesystem (SPIFFS/LittleFS/SD) instead of
 *                   compiled-in data. Useful for larger models that don't
 *                   fit in flash as a C array.
 */

#include <errno.h>
#include <stdio.h>
#include <memory>
#include <type_traits>
#include <utility>
#include <vector>

#include <executorch/extension/data_loader/buffer_data_loader.h>
#include <executorch/extension/runner_util/inputs.h>
#include <executorch/runtime/core/exec_aten/util/scalar_type_util.h>
#include <executorch/runtime/core/memory_allocator.h>
#include <executorch/runtime/executor/program.h>
#include <executorch/runtime/platform/log.h>
#include <executorch/runtime/platform/platform.h>
#include <executorch/runtime/platform/runtime.h>

#include "esp_memory_allocator.h"
#include "esp_perf_monitor.h"

#if defined(ESP_PLATFORM)
#include <esp_heap_caps.h>
#include <esp_log.h>
#include <esp_system.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#endif

#if defined(ET_BUNDLE_IO)
#include <executorch/devtools/bundled_program/bundled_program.h>
#endif

#if defined(ET_EVENT_TRACER_ENABLED)
#include <executorch/devtools/etdump/etdump_flatcc.h>

#if defined(ET_DUMP_INTERMEDIATE_OUTPUTS) || defined(ET_DUMP_OUTPUTS)
#include <executorch/devtools/etdump/data_sinks/buffer_data_sink.h>

#if !defined(ET_DEBUG_BUFFER_SIZE)
#define ET_DEBUG_BUFFER_SIZE (64 * 1024)
#endif

#endif // ET_DUMP_INTERMEDIATE_OUTPUTS || ET_DUMP_OUTPUTS

#endif // ET_EVENT_TRACER_ENABLED

#if defined(FILESYSTEM_LOAD)
#include <sys/stat.h>
#if defined(ESP_PLATFORM)
#include <esp_spiffs.h>
#endif
#else
/* When not loading from filesystem, include the model as a compiled-in
 * C array. This header is generated by the build process from the .pte file
 * specified in ET_PTE_FILE_PATH. */
#include "model_pte.h"
#endif

using executorch::aten::ScalarType;
using executorch::aten::Tensor;
using executorch::extension::BufferDataLoader;
using executorch::runtime::Error;
using executorch::runtime::EValue;
using executorch::runtime::HierarchicalAllocator;
using executorch::runtime::MemoryAllocator;
using executorch::runtime::MemoryManager;
using executorch::runtime::Method;
using executorch::runtime::MethodMeta;
using executorch::runtime::Program;
using executorch::runtime::Result;
using executorch::runtime::Span;
using executorch::runtime::Tag;
using executorch::runtime::TensorInfo;
using executorch::runtime::toString;

#if defined(ET_BUNDLE_IO)
using executorch::bundled_program::compute_method_output_error_stats;
using executorch::bundled_program::ErrorStats;
using executorch::bundled_program::verify_method_outputs;
#endif

#if defined(ET_EVENT_TRACER_ENABLED)
using executorch::etdump::BufferDataSink;
using executorch::etdump::ETDumpGen;
using executorch::etdump::ETDumpResult;
using executorch::runtime::EventTracerDebugLogLevel;
using torch::executor::etdump_result;
#endif

/**
 * Memory pool sizes for the ExecuTorch runtime.
 *
 * ESP32:    ~520KB internal SRAM total. With PSRAM: 4-8MB external.
 * ESP32-S3: ~512KB internal SRAM total. With PSRAM: 2-32MB external.
 *
 * For models that fit in internal SRAM, use smaller pool sizes.
 * For larger models, enable PSRAM and increase these values.
 *
 * Default: 256KB method allocator, 128KB scratch (suitable for small models).
 * With PSRAM: These can be increased significantly.
 */
#if !defined(ET_ESP_METHOD_ALLOCATOR_POOL_SIZE)
#if defined(CONFIG_SPIRAM)
/* With PSRAM available, use larger pools */
#define ET_ESP_METHOD_ALLOCATOR_POOL_SIZE (2 * 1024 * 1024)
#else
/* Internal SRAM only - conservative defaults */
#define ET_ESP_METHOD_ALLOCATOR_POOL_SIZE (256 * 1024)
#endif
#endif

#if !defined(ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE)
#if defined(CONFIG_SPIRAM)
#define ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE (512 * 1024)
#else
#define ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE (128 * 1024)
#endif
#endif

/**
 * Memory pool placement.
 * On ESP32 with PSRAM, place large buffers in external RAM.
 * EXT_RAM_BSS_ATTR places the buffer in PSRAM .bss section.
 */
#if defined(CONFIG_SPIRAM) && defined(ESP_PLATFORM)
#include <esp_heap_caps.h>
// Use PSRAM for large allocations
static const size_t method_allocation_pool_size =
    ET_ESP_METHOD_ALLOCATOR_POOL_SIZE;
static uint8_t __attribute__((aligned(16)))
    method_allocation_pool[ET_ESP_METHOD_ALLOCATOR_POOL_SIZE]
    EXT_RAM_BSS_ATTR;

static const size_t temp_allocation_pool_size =
    ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE;
static uint8_t __attribute__((aligned(16)))
    temp_allocation_pool[ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE]
    EXT_RAM_BSS_ATTR;
#else
// Internal SRAM allocation
static const size_t method_allocation_pool_size =
    ET_ESP_METHOD_ALLOCATOR_POOL_SIZE;
static uint8_t __attribute__((aligned(16)))
    method_allocation_pool[ET_ESP_METHOD_ALLOCATOR_POOL_SIZE];

static const size_t temp_allocation_pool_size =
    ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE;
static uint8_t __attribute__((aligned(16)))
    temp_allocation_pool[ET_ESP_SCRATCH_TEMP_ALLOCATOR_POOL_SIZE];
#endif

#if defined(FILESYSTEM_LOAD)
static char* model_pte = nullptr;
static size_t model_pte_size = 0;
#endif

#if defined(ET_BUNDLE_IO)
static const size_t testset_idx = 0;

#if defined(ET_ATOL)
static const float et_atol = ET_ATOL;
#else
static const float et_atol = 0.01;
#endif

#if defined(ET_RTOL)
static const float et_rtol = ET_RTOL;
#else
static const float et_rtol = 0.01;
#endif
#endif // ET_BUNDLE_IO

#if defined(ET_NUM_INFERENCES)
static const int num_inferences = ET_NUM_INFERENCES;
#else
static const int num_inferences = 1;
#endif

/**
 * ESP-IDF platform adaptation layer (et_pal) implementations.
 */

void et_pal_init(void) {
#if defined(ESP_PLATFORM)
  ET_LOG(
      Info,
      "ESP32 ExecuTorch runner initialized. Free heap: %lu bytes.",
      static_cast<unsigned long>(esp_get_free_heap_size()));
#if defined(CONFIG_SPIRAM)
  ET_LOG(
      Info,
      "PSRAM available. Free PSRAM: %lu bytes.",
      static_cast<unsigned long>(
          heap_caps_get_free_size(MALLOC_CAP_SPIRAM)));
#endif
#endif
}

ET_NORETURN void et_pal_abort(void) {
#if defined(ESP_PLATFORM)
  esp_restart();
#else
  abort();
#endif
  // Should never reach here
  while (1) {
  }
}

et_timestamp_t et_pal_current_ticks(void) {
#if defined(ESP_PLATFORM)
  return (et_timestamp_t)esp_cpu_get_cycle_count();
#else
  return 0;
#endif
}

et_tick_ratio_t et_pal_ticks_to_ns_multiplier(void) {
  // ESP32 default clock is 240MHz, ESP32-S3 is 240MHz
  // 1 tick = 1/240MHz = ~4.167ns
  // Return ratio: multiply ticks by 1000 and divide by 240 to get ns
  // This gives approximately correct ns values at 240MHz
  return {1000, 240};
}

/**
 * Emit a log message via platform output.
 * On ESP32, this goes to the UART serial console.
 */
void et_pal_emit_log_message(
    ET_UNUSED et_timestamp_t timestamp,
    et_pal_log_level_t level,
    const char* filename,
    ET_UNUSED const char* function,
    size_t line,
    const char* message,
    ET_UNUSED size_t length) {
  fprintf(
      stderr,
      "%c [executorch:%s:%lu %s()] %s\n",
      level,
      filename,
      static_cast<unsigned long>(line),
      function,
      message);
}

/**
 * Dynamic memory allocators - not used in this example.
 * On ESP32, heap_caps_malloc could be used here if needed.
 */
void* et_pal_allocate(ET_UNUSED size_t size) {
  return nullptr;
}

void et_pal_free(ET_UNUSED void* ptr) {}

namespace {

/// Lightweight heapless container that constructs and stores a T in-place.
/// Useful when you want to avoid heap allocations but need to delay
/// construction.
template <typename T>
class Box {
 public:
  Box() = default;

  ~Box() {
    if (has_value) {
      ptr()->~T();
    }
  }

  Box(const Box&) = delete;
  Box& operator=(const Box&) = delete;

  template <typename... Args>
  void reset(Args&&... args) {
    if (has_value) {
      reinterpret_cast<T*>(mem)->~T();
    }
    new (mem) T(std::forward<Args>(args)...);
    has_value = true;
  }

  T& value() {
    return *ptr();
  }

  const T& value() const {
    return *ptr();
  }

  T* operator->() {
    return ptr();
  }

  const T* operator->() const {
    return ptr();
  }

 private:
  alignas(T) uint8_t mem[sizeof(T)];
  bool has_value = false;

  T* ptr() {
    return reinterpret_cast<T*>(mem);
  }

  const T* ptr() const {
    return reinterpret_cast<const T*>(mem);
  }
};

template <typename ValueType>
void fill_tensor_with_default_value(Tensor& tensor) {
  ValueType fill_value{};
  if constexpr (std::is_same_v<ValueType, bool>) {
    fill_value = true;
  } else {
    fill_value = ValueType(1);
  }

  ValueType* data_ptr = tensor.mutable_data_ptr<ValueType>();
  std::fill(data_ptr, data_ptr + tensor.numel(), fill_value);
}

Error prepare_input_tensors(Method& method, MemoryAllocator& allocator) {
  MethodMeta method_meta = method.method_meta();
  size_t num_inputs = method_meta.num_inputs();

  EValue* input_evalues = allocator.allocateList<EValue>(num_inputs);
  ET_CHECK_OR_RETURN_ERROR(
      input_evalues != nullptr,
      MemoryAllocationFailed,
      "Could not allocate memory for input evalues.");

  Error err = method.get_inputs(input_evalues, num_inputs);
  ET_CHECK_OK_OR_RETURN_ERROR(err);

  for (size_t i = 0; i < num_inputs; i++) {
    auto tag = method_meta.input_tag(i);
    ET_CHECK_OK_OR_RETURN_ERROR(tag.error());

    if (tag.get() != Tag::Tensor) {
      ET_LOG(
          Debug,
          "Skipping non-tensor input %lu",
          static_cast<unsigned long>(i));
      continue;
    }

    // Fill tensors with default values (1) when no input data is provided
    if (input_evalues[i].isTensor()) {
      Tensor& tensor = input_evalues[i].toTensor();
      switch (tensor.scalar_type()) {
#define HANDLE_SCALAR_TYPE(cpp_type, scalar_name)     \
  case ScalarType::scalar_name:                       \
    fill_tensor_with_default_value<cpp_type>(tensor); \
    break;
        ET_FORALL_SCALAR_TYPES(HANDLE_SCALAR_TYPE)
#undef HANDLE_SCALAR_TYPE
        default:
          ET_LOG(
              Error,
              "Unhandled ScalarType %s",
              toString(tensor.scalar_type()));
          err = Error::InvalidArgument;
          break;
      }
    } else {
      printf("Input[%lu]: Not Tensor\n", static_cast<unsigned long>(i));
    }
  }

  return err;
}

#if defined(FILESYSTEM_LOAD)
/**
 * Load a binary file from the filesystem.
 * Supports SPIFFS, LittleFS, or SD card mounted filesystems.
 */
std::pair<char*, size_t> load_file_from_fs(
    const char* filepath,
    MemoryAllocator& allocator) {
  FILE* fp = fopen(filepath, "rb");
  if (!fp) {
    ET_LOG(
        Fatal,
        "Could not open file %s (errno: %d)",
        filepath,
        errno);
    return std::make_pair(nullptr, 0);
  }

  fseek(fp, 0, SEEK_END);
  auto file_size = ftell(fp);
  fseek(fp, 0, SEEK_SET);

  char* buffer = static_cast<char*>(allocator.allocate(file_size));
  if (buffer == nullptr) {
    ET_LOG(
        Fatal,
        "Failed to allocate %lu bytes for file %s",
        static_cast<unsigned long>(file_size),
        filepath);
    fclose(fp);
    return std::make_pair(nullptr, 0);
  }

  auto read_size = fread(buffer, 1, file_size, fp);
  if (read_size != static_cast<size_t>(file_size)) {
    ET_LOG(
        Info,
        "Partial read of %s: got %lu of %lu bytes",
        filepath,
        static_cast<unsigned long>(read_size),
        static_cast<unsigned long>(file_size));
  }
  fclose(fp);
  return std::make_pair(buffer, read_size);
}

#if defined(ESP_PLATFORM)
/**
 * Initialize SPIFFS filesystem for loading model files.
 */
bool init_spiffs(const char* base_path, const char* partition_label) {
  esp_vfs_spiffs_conf_t conf = {
      .base_path = base_path,
      .partition_label = partition_label,
      .max_files = 5,
      .format_if_mount_failed = false,
  };

  esp_err_t ret = esp_vfs_spiffs_register(&conf);
  if (ret != ESP_OK) {
    if (ret == ESP_FAIL) {
      ET_LOG(Error, "Failed to mount SPIFFS filesystem");
    } else if (ret == ESP_ERR_NOT_FOUND) {
      ET_LOG(Error, "SPIFFS partition not found");
    } else {
      ET_LOG(Error, "SPIFFS init failed: %s", esp_err_to_name(ret));
    }
    return false;
  }

  size_t total = 0, used = 0;
  ret = esp_spiffs_info(partition_label, &total, &used);
  if (ret == ESP_OK) {
    ET_LOG(
        Info,
        "SPIFFS: total=%lu, used=%lu",
        static_cast<unsigned long>(total),
        static_cast<unsigned long>(used));
  }
  return true;
}
#endif // ESP_PLATFORM
#endif // FILESYSTEM_LOAD

/// Holds all state needed for setup and run phases
struct RunnerContext {
  RunnerContext() = default;
  RunnerContext(const RunnerContext& ctx) = delete;
  RunnerContext& operator=(const RunnerContext& ctx) = delete;

  const char* method_name = nullptr;
  size_t planned_buffer_memsize = 0;
  size_t method_loaded_memsize = 0;
  size_t executor_membase = 0;
  size_t program_data_len = 0;
  size_t input_memsize = 0;
  size_t pte_size = 0;
  bool bundle_io = false;
  Box<BufferDataLoader> loader;
  Box<Program> program;
  Box<EspMemoryAllocator> method_allocator;
  Box<EspMemoryAllocator> temp_allocator;
  std::vector<Span<uint8_t>> planned_spans;
  Box<HierarchicalAllocator> planned_memory;
  Box<MemoryManager> memory_manager;
  Box<Result<Method>> method;
#if defined(ET_EVENT_TRACER_ENABLED)
  Box<ETDumpGen> etdump_gen;
#if defined(ET_DUMP_INTERMEDIATE_OUTPUTS) || defined(ET_DUMP_OUTPUTS)
  void* debug_buffer;
#endif
#endif
};

void runner_init(RunnerContext& ctx, size_t pte_size) {
  const void* program_data = model_pte;
  ctx.program_data_len = pte_size;
  ctx.pte_size = pte_size;

#if defined(ET_BUNDLE_IO)
  ctx.bundle_io = executorch::bundled_program::is_bundled_program(
      reinterpret_cast<void*>(model_pte), ctx.pte_size);
  if (ctx.bundle_io) {
    Error status = executorch::bundled_program::get_program_data(
        reinterpret_cast<void*>(model_pte),
        ctx.pte_size,
        &program_data,
        &ctx.program_data_len);
    ET_CHECK_MSG(
        status == Error::Ok,
        "get_program_data() from bundle PTE failed: 0x%x",
        (unsigned int)status);
  }
#endif

  ctx.loader.reset(program_data, ctx.program_data_len);
  auto& loader = ctx.loader.value();
  ET_LOG(
      Info,
      "PTE Model data loaded. Size: %lu bytes.",
      static_cast<unsigned long>(ctx.program_data_len));

  // Parse the program file
  Result<Program> program_result = Program::load(&loader);
  ET_CHECK_MSG(
      program_result.ok(),
      "Program loading failed @ %p: 0x%" PRIx32,
      program_data,
      program_result.error());
  ctx.program.reset(std::move(program_result.get()));
  Program& program = ctx.program.value();

  ET_LOG(
      Info,
      "Model buffer loaded, has %lu methods",
      static_cast<unsigned long>(program.num_methods()));

  {
    const auto method_name_result = program.get_method_name(0);
    ET_CHECK_MSG(method_name_result.ok(), "Program has no methods");
    ctx.method_name = *method_name_result;
  }
  ET_LOG(Info, "Running method %s", ctx.method_name);

  Result<MethodMeta> method_meta = program.method_meta(ctx.method_name);
  if (!method_meta.ok()) {
    ET_LOG(
        Info,
        "Failed to get method_meta for %s: 0x%x",
        ctx.method_name,
        (unsigned int)method_meta.error());
  }

  ET_LOG(
      Info,
      "Setup Method allocator pool. Size: %lu bytes.",
      static_cast<unsigned long>(method_allocation_pool_size));

  ctx.method_allocator.reset(
      method_allocation_pool_size, method_allocation_pool);

  ctx.planned_spans.clear();
  size_t num_memory_planned_buffers = method_meta->num_memory_planned_buffers();
  ctx.planned_spans.reserve(num_memory_planned_buffers);
  size_t planned_buffer_membase = ctx.method_allocator->used_size();

  for (size_t id = 0; id < num_memory_planned_buffers; ++id) {
    size_t buffer_size =
        static_cast<size_t>(method_meta->memory_planned_buffer_size(id).get());
    ET_LOG(
        Info,
        "Setting up planned buffer %lu, size %lu.",
        static_cast<unsigned long>(id),
        static_cast<unsigned long>(buffer_size));

    uint8_t* buffer = reinterpret_cast<uint8_t*>(
        ctx.method_allocator->allocate(buffer_size, 16UL));
    ET_CHECK_MSG(
        buffer != nullptr,
        "Could not allocate memory for memory planned buffer size %lu",
        static_cast<unsigned long>(buffer_size));
    ctx.planned_spans.push_back({buffer, buffer_size});
  }

  ctx.planned_buffer_memsize =
      ctx.method_allocator->used_size() - planned_buffer_membase;

  Span<Span<uint8_t>> planned_memory_span;
  if (!ctx.planned_spans.empty()) {
    planned_memory_span =
        Span<Span<uint8_t>>(ctx.planned_spans.data(), ctx.planned_spans.size());
  }
  ctx.planned_memory.reset(planned_memory_span);

  ctx.temp_allocator.reset(temp_allocation_pool_size, temp_allocation_pool);

  ctx.memory_manager.reset(
      &ctx.method_allocator.value(),
      &ctx.planned_memory.value(),
      &ctx.temp_allocator.value());

  size_t method_loaded_membase = ctx.method_allocator->used_size();

  executorch::runtime::EventTracer* event_tracer_ptr = nullptr;

#if defined(ET_EVENT_TRACER_ENABLED)
  ET_LOG(Info, "Setting up ETDump");
  ctx.etdump_gen.reset();
  event_tracer_ptr = &ctx.etdump_gen.value();

#if defined(ET_DUMP_INTERMEDIATE_OUTPUTS) || defined(ET_DUMP_OUTPUTS)
  ctx.debug_buffer = ctx.method_allocator->allocate(ET_DEBUG_BUFFER_SIZE, 16);
  if (ctx.debug_buffer != nullptr) {
    Span<uint8_t> debug_buffer_span(
        (uint8_t*)ctx.debug_buffer, ET_DEBUG_BUFFER_SIZE);

    Result<bool> result =
        ctx.etdump_gen.value().set_debug_buffer(debug_buffer_span);

    if (result.ok()) {
#if defined(ET_DUMP_INTERMEDIATE_OUTPUTS)
      ET_LOG(
          Info,
          "ETDump: Allocated intermediate output buffer size: %d at 0x%p",
          ET_DEBUG_BUFFER_SIZE,
          ctx.debug_buffer);
      ctx.etdump_gen.value().set_event_tracer_debug_level(
          EventTracerDebugLogLevel::kIntermediateOutputs);
#else
      ET_LOG(
          Info,
          "ETDump: Allocated output buffer size: %d at 0x%p",
          ET_DEBUG_BUFFER_SIZE,
          ctx.debug_buffer);
      ctx.etdump_gen.value().set_event_tracer_debug_level(
          EventTracerDebugLogLevel::kProgramOutputs);
#endif
    } else {
      ctx.debug_buffer = nullptr;
      ET_LOG(
          Error,
          "ETDump: Could not set_debug_buffer() error:0x%" PRIx32,
          result.error());
    }
  } else {
    ET_LOG(
        Error,
        "ETDump: Could not allocate output buffer size %lu",
        static_cast<unsigned long>(ET_DEBUG_BUFFER_SIZE));
  }
#endif // ET_DUMP_INTERMEDIATE_OUTPUTS || ET_DUMP_OUTPUTS
#endif // ET_EVENT_TRACER_ENABLED

  ctx.method.reset(program.load_method(
      ctx.method_name, &ctx.memory_manager.value(), event_tracer_ptr));

  if (!ctx.method->ok()) {
    ET_LOG(
        Info,
        "Loading of method %s failed with status 0x%" PRIx32,
        ctx.method_name,
        ctx.method->error());
  }
  ctx.method_loaded_memsize =
      ctx.method_allocator->used_size() - method_loaded_membase;
  ET_LOG(Info, "Method '%s' loaded.", ctx.method_name);

  ET_LOG(Info, "Preparing inputs...");
  size_t input_membase = ctx.method_allocator->used_size();

#if defined(ET_BUNDLE_IO)
  if (ctx.bundle_io) {
    ET_LOG(Info, "Input testset[%d] from bundled bpte", testset_idx);
    Error status = executorch::bundled_program::load_bundled_input(
        *ctx.method.value(), model_pte, testset_idx);
    ET_CHECK_MSG(
        status == Error::Ok,
        "load_bundled_input failed with status 0x%" PRIx32,
        status);
  } else
#endif
  {
    Error status =
        ::prepare_input_tensors(*ctx.method.value(), ctx.method_allocator.value());
    ET_CHECK_MSG(
        status == Error::Ok, "Failed to prepare inputs 0x%" PRIx32, status);
  }

#if defined(ET_LOG_DUMP_INPUT)
  {
    std::vector<EValue> inputs((*ctx.method.value())->inputs_size());
    ET_LOG(Info, "%lu inputs: ", static_cast<unsigned long>(inputs.size()));
    Error status = ctx.method.value()->get_inputs(inputs.data(), inputs.size());
    ET_CHECK(status == Error::Ok);

    for (int i = 0; i < inputs.size(); ++i) {
      if (inputs[i].isTensor()) {
        Tensor tensor = inputs[i].toTensor();
        for (int j = 0; j < tensor.numel(); ++j) {
          if (tensor.scalar_type() == ScalarType::Int) {
            printf(
                "Input[%d][%d]: (int) %d\n",
                i, j, tensor.const_data_ptr<int>()[j]);
          } else if (tensor.scalar_type() == ScalarType::Float) {
            printf(
                "Input[%d][%d]: (float) %f\n",
                i, j, tensor.const_data_ptr<float>()[j]);
          } else if (tensor.scalar_type() == ScalarType::Char) {
            printf(
                "Input[%d][%d]: (char) %d\n",
                i, j, tensor.const_data_ptr<int8_t>()[j]);
          } else if (tensor.scalar_type() == ScalarType::Bool) {
            printf(
                "Input[%d][%d]: (bool) %s (0x%x)\n",
                i, j,
                tensor.const_data_ptr<int8_t>()[j] ? "true" : "false",
                tensor.const_data_ptr<int8_t>()[j]);
          }
        }
      } else {
        printf("Input[%d]: Not Tensor\n", i);
      }
    }
  }
#endif

  ctx.input_memsize = ctx.method_allocator->used_size() - input_membase;
  ctx.executor_membase = ctx.method_allocator->used_size();

  ET_LOG(Info, "Input prepared.");
}

void log_mem_status(RunnerContext& ctx) {
  size_t executor_memsize =
      ctx.method_allocator->used_size() - ctx.executor_membase;

  ET_LOG(
      Info,
      "model_pte_program_size:     %lu bytes.",
      static_cast<unsigned long>(ctx.program_data_len));
  ET_LOG(
      Info,
      "model_pte_loaded_size:      %lu bytes.",
      static_cast<unsigned long>(ctx.pte_size));

  if (ctx.method_allocator->size() != 0) {
    size_t method_allocator_used = ctx.method_allocator->used_size();
    ET_LOG(
        Info,
        "method_allocator_used:     %lu / %lu  free: %lu ( used: %lu %% ) ",
        static_cast<unsigned long>(method_allocator_used),
        static_cast<unsigned long>(ctx.method_allocator->size()),
        static_cast<unsigned long>(ctx.method_allocator->free_size()),
        static_cast<unsigned long>(
            100 * method_allocator_used / ctx.method_allocator->size()));
    ET_LOG(
        Info,
        "method_allocator_planned:  %lu bytes",
        static_cast<unsigned long>(ctx.planned_buffer_memsize));
    ET_LOG(
        Info,
        "method_allocator_loaded:   %lu bytes",
        static_cast<unsigned long>(ctx.method_loaded_memsize));
    ET_LOG(
        Info,
        "method_allocator_input:    %lu bytes",
        static_cast<unsigned long>(ctx.input_memsize));
    ET_LOG(
        Info,
        "method_allocator_executor: %lu bytes",
        static_cast<unsigned long>(executor_memsize));
  }
  if (ctx.temp_allocator->size() > 0) {
    ET_LOG(
        Info,
        "temp_allocator:            %lu",
        static_cast<unsigned long>(ctx.temp_allocator->size()));
  }

#if defined(ESP_PLATFORM)
  ET_LOG(
      Info,
      "ESP free heap:             %lu bytes",
      static_cast<unsigned long>(esp_get_free_heap_size()));
  ET_LOG(
      Info,
      "ESP min free heap ever:    %lu bytes",
      static_cast<unsigned long>(esp_get_minimum_free_heap_size()));
#if defined(CONFIG_SPIRAM)
  ET_LOG(
      Info,
      "ESP free PSRAM:            %lu bytes",
      static_cast<unsigned long>(
          heap_caps_get_free_size(MALLOC_CAP_SPIRAM)));
#endif
#endif

#if defined(ET_EVENT_TRACER_ENABLED)
#if defined(ET_DUMP_INTERMEDIATE_OUTPUTS) || defined(ET_DUMP_OUTPUTS)
  if (ctx.debug_buffer != nullptr) {
    size_t outputdump_len = ctx.etdump_gen->get_data_sink()->get_used_bytes();
    ET_LOG(
        Info,
        "ETDump_outputs_buffer:     %lu / %lu free: %lu ( used: %lu %% ) ",
        static_cast<unsigned long>(outputdump_len),
        static_cast<unsigned long>(ET_DEBUG_BUFFER_SIZE),
        static_cast<unsigned long>(ET_DEBUG_BUFFER_SIZE - outputdump_len),
        static_cast<unsigned long>(
            100 * outputdump_len / ET_DEBUG_BUFFER_SIZE));
  }
#endif
#endif
}

void print_outputs(RunnerContext& ctx) {
  std::vector<EValue> outputs(ctx.method.value()->outputs_size());
  ET_LOG(Info, "%lu outputs: ", static_cast<unsigned long>(outputs.size()));
  Error status =
      ctx.method.value()->get_outputs(outputs.data(), outputs.size());
  ET_CHECK(status == Error::Ok);

  for (int i = 0; i < outputs.size(); ++i) {
    if (outputs[i].isTensor()) {
      Tensor tensor = outputs[i].toTensor();
#if defined(ET_LOG_DUMP_OUTPUT)
      for (int j = 0; j < tensor.numel(); ++j) {
        if (tensor.scalar_type() == ScalarType::Int) {
          printf(
              "Output[%d][%d]: (int) %d\n",
              i, j, tensor.const_data_ptr<int>()[j]);
        } else if (tensor.scalar_type() == ScalarType::Float) {
          printf(
              "Output[%d][%d]: (float) %f\n",
              i, j, tensor.const_data_ptr<float>()[j]);
        } else if (tensor.scalar_type() == ScalarType::Char) {
          printf(
              "Output[%d][%d]: (char) %d\n",
              i, j, tensor.const_data_ptr<int8_t>()[j]);
        } else if (tensor.scalar_type() == ScalarType::Bool) {
          printf(
              "Output[%d][%d]: (bool) %s (0x%x)\n",
              i, j,
              tensor.const_data_ptr<int8_t>()[j] ? "true " : "false",
              tensor.const_data_ptr<int8_t>()[j]);
        }
      }
#endif
    } else {
      printf("Output[%d]: Not Tensor\n", i);
    }
  }
}

void write_etdump(RunnerContext& ctx) {
#if defined(ET_EVENT_TRACER_ENABLED)
  ETDumpResult result = ctx.etdump_gen->get_etdump_data();
  if (result.buf != nullptr && result.size > 0) {
    ET_LOG(
        Info,
        "ETDump data generated: %lu bytes",
        static_cast<unsigned long>(result.size));

    // On ESP32, we could write to SPIFFS/SD or dump via serial.
    // For now, log the size. In a production setup, you would
    // write this to a filesystem or transmit over a network interface.
#if defined(FILESYSTEM_LOAD) && defined(ESP_PLATFORM)
    const char* etdump_filename = "/spiffs/etdump.bin";
    ET_LOG(Info, "Writing etdump to file: %s", etdump_filename);
    FILE* f = fopen(etdump_filename, "w+");
    if (f) {
      fwrite((uint8_t*)result.buf, 1, result.size, f);
      fclose(f);
    } else {
      ET_LOG(Error, "Could not open %s for writing", etdump_filename);
    }
#endif
  }
#endif
}

bool verify_result(RunnerContext& ctx, const void* model_pte) {
  bool model_ok = false;
#if defined(ET_BUNDLE_IO)
  if (ctx.bundle_io) {
    ErrorStats stats = compute_method_output_error_stats(
        *ctx.method.value(), model_pte, testset_idx);
    if (stats.status == Error::Ok) {
      ET_LOG(Info, "=== Error stats for testset %d ===", testset_idx);
      ET_LOG(Info, " mean_absolute_error: %f", stats.mean_abs_error);
      ET_LOG(Info, " max_absolute_error:  %f", stats.max_abs_error);
      ET_LOG(Info, " mean_relative_error: %f", stats.mean_relative_error);
      ET_LOG(Info, " max_relative_error:  %f", stats.max_relative_error);
    } else {
      ET_LOG(
          Info,
          "=== Error calculating stats for testset %d ERROR:%d ===",
          testset_idx,
          stats.status);
    }

    Error status = verify_method_outputs(
        *ctx.method.value(), model_pte, testset_idx, et_rtol, et_atol);
    if (status == Error::Ok) {
      ET_LOG(Info, "Model output match expected BundleIO bpte ref data.");
      ET_LOG(Info, "TEST: BundleIO index[%d] Test_result: PASS", testset_idx);
      model_ok = true;
    } else {
      ET_LOG(
          Error,
          "Model output don't match expected BundleIO bpte ref data. rtol=%f atol=%f",
          et_rtol,
          et_atol);
      ET_LOG(Error, "TEST: BundleIO index[%d] Test_result: FAIL", testset_idx);
      model_ok = false;
    }
  } else {
    model_ok = true;
  }
#else
  (void)ctx;
  (void)model_pte;
  model_ok = true;
#endif
  return model_ok;
}

bool run_model(RunnerContext& ctx, const void* model_pte) {
  Error status;
  ET_LOG(Info, "Starting running %d inferences...", num_inferences);
  int n = 0;
  StartMeasurements();
  for (n = 0; n < num_inferences; n++) {
    ET_LOG(Debug, "Running inference number %d", n);
    status = ctx.method.value()->execute();
    if (status != Error::Ok) {
      break;
    }
    // Reset the temporary allocator between inferences
    ctx.temp_allocator.reset(temp_allocation_pool_size, temp_allocation_pool);
  }
  StopMeasurements(n);

  ET_CHECK_MSG(
      status == Error::Ok,
      "Execution of method %s failed with status 0x%" PRIx32,
      ctx.method_name,
      status);

  ET_LOG(Info, "%d inferences finished", num_inferences);
  print_outputs(ctx);
  bool model_ok = verify_result(ctx, model_pte);
  ET_LOG(Info, "Model run: %d", model_ok);

  return model_ok;
}

} // namespace

/**
 * Main entry point for the ESP32 executor runner.
 *
 * On ESP-IDF, this is called from app_main() (see below).
 * The function can also be compiled for host testing without ESP-IDF.
 */
void executor_runner_main(void) {
  executorch::runtime::runtime_init();

  size_t pte_size;

#if defined(FILESYSTEM_LOAD)
#if defined(ESP_PLATFORM)
  // Initialize SPIFFS for model loading
  if (!init_spiffs("/spiffs", "storage")) {
    ET_LOG(Fatal, "Failed to initialize SPIFFS. Cannot load model.");
    return;
  }
#endif

  // Load model from filesystem
  // Use a temporary allocator for the file loading
  EspMemoryAllocator file_allocator(
      method_allocation_pool_size, method_allocation_pool);
  auto [buffer, buffer_size] =
      load_file_from_fs("/spiffs/model.pte", file_allocator);
  if (buffer == nullptr) {
    ET_LOG(Fatal, "Failed to load model from filesystem.");
    return;
  }
  model_pte = buffer;
  model_pte_size = buffer_size;
  pte_size = buffer_size;
#else
  pte_size = sizeof(model_pte);
#endif

  // Log the PTE magic bytes for quick sanity check
  ET_LOG(
      Info,
      "PTE @ %p [----%c%c%c%c]",
      model_pte,
      model_pte[4],
      model_pte[5],
      model_pte[6],
      model_pte[7]);

  RunnerContext ctx;
  runner_init(ctx, pte_size);
  bool model_ok = run_model(ctx, model_pte);
  ET_LOG(Info, "Model run: %d", model_ok);

  log_mem_status(ctx);
  write_etdump(ctx);

  ET_CHECK_MSG(model_ok == true, "Problem running model");

  ET_LOG(Info, "Program complete.");
}

#if defined(ESP_PLATFORM)
/**
 * ESP-IDF application entry point.
 * Runs the executor runner on a task with a sufficiently large stack.
 */
extern "C" void app_main(void) {
  ET_LOG(Info, "ExecuTorch ESP32 Executor Runner starting...");

  // Run directly - for production use, consider creating a dedicated
  // FreeRTOS task with appropriate stack size:
  //
  //   xTaskCreatePinnedToCore(
  //       [](void*) { executor_runner_main(); vTaskDelete(nullptr); },
  //       "et_runner",
  //       32768,  // Stack size in bytes
  //       nullptr,
  //       5,      // Priority
  //       nullptr,
  //       1       // Core ID (0 or 1)
  //   );
  //
  executor_runner_main();
}
#else
/**
 * Host/test entry point when building outside ESP-IDF.
 */
int main(int argc, const char* argv[]) {
  (void)argc;
  (void)argv;
  executor_runner_main();
  return 0;
}
#endif
