load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    # @autodeps-skip for some reason autodeps thinks this target
    # needs to depend on exir:lib which it doesn't.
    name = "serialize",
    srcs = [
        "export_serialize.py",
        "schema.py",
        "schema_check.py",
        "serialize.py",
        "union.py",
    ],
    deps = [
        "fbsource//third-party/pypi/sympy:sympy",
        "//caffe2:torch",
        "//executorch/exir:delegate",
        "//executorch/exir:lowered_backend_module",
        "//executorch/exir:memory",
        "//executorch/exir/backend:compile_spec_schema",
        "//executorch/exir/dialects:lib",
        "//executorch/exir/dialects/backend:lib",
        "//executorch/exir/dialects/edge:lib",
    ],
)
