# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set_overridable_option(EXECUTORCH_BUILD_COREML OFF)
set_overridable_option(EXECUTORCH_ENABLE_EVENT_TRACER OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_LLM OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_LLM_AOT OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_DATA_LOADER OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_FLAT_TENSOR OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_LLM OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_MODULE OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_TRAINING OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_APPLE OFF)
set_overridable_option(EXECUTORCH_BUILD_MPS OFF)
set_overridable_option(EXECUTORCH_BUILD_NEURON OFF)
set_overridable_option(EXECUTORCH_BUILD_OPENVINO OFF)
set_overridable_option(EXECUTORCH_BUILD_PYBIND OFF)
set_overridable_option(EXECUTORCH_BUILD_QNN OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_OPTIMIZED OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_QUANTIZED OFF)
set_overridable_option(EXECUTORCH_BUILD_DEVTOOLS OFF)
set_overridable_option(EXECUTORCH_BUILD_TESTS OFF)
set_overridable_option(EXECUTORCH_BUILD_XNNPACK OFF)
set_overridable_option(EXECUTORCH_BUILD_VULKAN OFF)
set_overridable_option(EXECUTORCH_BUILD_PORTABLE_OPS ON)
set_overridable_option(EXECUTORCH_BUILD_CADENCE OFF)
set_overridable_option(EXECUTORCH_BUILD_PTHREADPOOL OFF)
set_overridable_option(EXECUTORCH_BUILD_CPUINFO OFF)
set_overridable_option(EXECUTORCH_USE_CPP_CODE_COVERAGE OFF)
