
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set_overridable_option(CMAKE_SYSTEM_PROCESSOR                   cortex-m55)
set_overridable_option(CMAKE_BUILD_TYPE                         Release)
set_overridable_option(PYTHON_EXECUTABLE                        /home/zephyruser/executorch/.venv/bin/python3)
set_overridable_option(CMAKE_CXX_COMPILER_ID                    GNU)
set_overridable_option(CMAKE_TOOLCHAIN_FILE                     "${PROJECT_SOURCE_DIR}/examples/arm/ethos-u-setup/arm-zephyr-eabi-gcc.cmake")
set_overridable_option(EXECUTORCH_ENABLE_LOGGING                ON)
set_overridable_option(EXECUTORCH_BUILD_COREML                  OFF)
set_overridable_option(EXECUTORCH_FLATBUFFERS_MAX_ALIGNMENT     1024)
set(EXECUTORCH_PAL_DEFAULT_FILE_PATH         "${PROJECT_SOURCE_DIR}/runtime/platform/default/zephyr.cpp")
set_overridable_option(EXECUTORCH_LOG_LEVEL                     Info)
set_overridable_option(EXECUTORCH_ENABLE_PROGRAM_VERIFICATION   OFF)
set_overridable_option(EXECUTORCH_ENABLE_EVENT_TRACER           OFF)
set_overridable_option(EXECUTORCH_OPTIMIZE_SIZE                 ON)
set_overridable_option(EXECUTORCH_BUILD_ARM_BAREMETAL           OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_CUSTOM          OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_CUSTOM_AOT      OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_QUANTIZED_AOT   OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_DATA_LOADER   OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_FLAT_TENSOR   OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_LLM           OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_MODULE        OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_RUNNER_UTIL   OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_TENSOR        OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_TRAINING      OFF)
set_overridable_option(EXECUTORCH_BUILD_EXTENSION_APPLE         OFF)
set_overridable_option(EXECUTORCH_BUILD_MPS                     OFF)
set_overridable_option(EXECUTORCH_BUILD_NEURON                  OFF)
set_overridable_option(EXECUTORCH_BUILD_OPENVINO                OFF)
set_overridable_option(EXECUTORCH_BUILD_PYBIND                  OFF)
set_overridable_option(EXECUTORCH_BUILD_QNN                     OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_OPTIMIZED       OFF)
set_overridable_option(EXECUTORCH_BUILD_KERNELS_QUANTIZED       OFF)
set_overridable_option(EXECUTORCH_BUILD_DEVTOOLS                OFF)
set_overridable_option(EXECUTORCH_BUILD_TESTS                   OFF)
set_overridable_option(EXECUTORCH_NNLIB_OPT                     OFF)
set_overridable_option(EXECUTORCH_CADENCE_CPU_RUNNER            OFF)
set_overridable_option(EXECUTORCH_BUILD_SIZE_TEST               OFF)
set_overridable_option(EXECUTORCH_BUILD_XNNPACK                 OFF)
set_overridable_option(EXECUTORCH_BUILD_VULKAN                  OFF)
set_overridable_option(EXECUTORCH_BUILD_PORTABLE_OPS            ON)
set_overridable_option(EXECUTORCH_USE_DL                        ON)
set_overridable_option(EXECUTORCH_BUILD_CADENCE                 OFF)
set_overridable_option(EXECUTORCH_BUILD_CORTEX_M                ON)
set_overridable_option(EXECUTORCH_COREML_BUILD_EXECUTOR_RUNNER  OFF)
set_overridable_option(EXECUTORCH_BUILD_PTHREADPOOL             OFF)
set_overridable_option(EXECUTORCH_BUILD_CPUINFO                 OFF)
set_overridable_option(EXECUTORCH_BUILD_EXECUTOR_RUNNER         ON)
set_overridable_option(EXECUTORCH_XNNPACK_SHARED_WORKSPACE      ON)
set_overridable_option(EXECUTORCH_XNNPACK_ENABLE_KLEIDI         OFF)
set_overridable_option(EXECUTORCH_XNNPACK_ENABLE_WEIGHT_CACHE   OFF)
set_overridable_option(EXECUTORCH_USE_CPP_CODE_COVERAGE         OFF)
