load("@fbsource//tools/build_defs:manifold.bzl", "manifold_get")
load("@fbsource//tools/build_defs/android:fb_android_binary.bzl", "fb_android_binary")
load("@fbsource//tools/build_defs/android:fb_android_library.bzl", "fb_android_library")
load("@fbsource//tools/build_defs/android:fb_android_resource.bzl", "fb_android_resource")

manifold_get(
    name = "dl3_xnnpack_fp32",
    out = "dl3_xnnpack_fp32.pte",
    api_key = "executorch-key",
    artifact_path = "tree/models/benchmarking/executorch/dl3_xnnpack_fp32.pte",
    bucket_name = "executorch",
    sha1 = "3e7af1d8f5ec4acb6de156d361715e16e5f53783",
    timeout_msec = 120000,
)

fb_android_resource(
    name = "app_res",
    assets = "assets",
    package = "com.example.executorchdemo",
    res = "res",
)

fb_android_resource(
    name = "model_res",
    assets = {"dl3_xnnpack_fp32.pte": ":dl3_xnnpack_fp32"},
    package = "com.example.executorchdemo",
    res = "res",
)

fb_android_library(
    name = "app_lib",
    srcs = [
        "java/com/example/executorchdemo/ClassificationActivity.java",
        "java/com/example/executorchdemo/ImageNetClasses.java",
        "java/com/example/executorchdemo/MainActivity.java",
        "java/com/example/executorchdemo/TensorImageUtils.java",
    ],
    autoglob = False,
    language = "JAVA",
    deps = [
        ":app_res",
        "//xplat/executorch/extension/android:executorch",
    ],
)

fb_android_binary(
    name = "ExecuTorchDemo",
    keystore = "//fbandroid/keystores:debug",
    manifest = "AndroidManifest.xml",
    manifest_entries = {
        "min_sdk_version": 19,  # Android supports 19 for minimum
        "target_sdk_version": 34,
        "version_code": "1",
        "version_name": "1.0",
    },
    package_type = "release",
    skip_proguard = True,
    deps = [
        ":app_lib",
        ":app_res",
        ":model_res",
        "//third-party/java/androidx/appcompat/appcompat:appcompat",
        "//third-party/java/androidx/constraintlayout/constraintlayout:constraintlayout",
        "//xplat/executorch/extension/android:executorch",
        "//xplat/executorch/extension/android/jni:executorch_jni_full",
    ],
)
