load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("odai_jarvis")

fbcode_target(_kind = runtime.python_library,
    name = "fuse_ops",
    srcs = [
        "fuse_ops.py",
    ],
    typing = True,
    deps = [
        "//caffe2:torch",
        "//executorch/backends/cadence/aot:pass_utils",
        "//executorch/backends/transforms:quantize_fused_convbn_bias_pass",
    ],
)
