load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbcode_macros//build_defs:python_unittest_remote_gpu.bzl", "python_unittest_remote_gpu")

oncall("executorch")

fbcode_target(_kind = python_unittest_remote_gpu,
    name = "test_cuda_export",
    srcs = [
        "test_cuda_export.py",
    ],
    visibility = [
        "//executorch/...",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/cuda:cuda_backend",
        "//executorch/backends/cuda:cuda_partitioner",
        "//executorch/exir:lib",
        "//executorch/exir/backend:backend_api",
        "//executorch/exir/backend:compile_spec_schema",
        "//executorch/examples/models/toy_model:toy_model",
    ],
    keep_gpu_sections = True,
)

fbcode_target(_kind = python_unittest,
    name = "test_cuda_partitioner",
    srcs = [
        "test_cuda_partitioner.py",
    ],
    visibility = [
        "//executorch/...",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/cuda:cuda_partitioner",
        "//executorch/backends/cuda:cuda_backend",
        "//executorch/exir:lib",
        "//executorch/exir/backend:compile_spec_schema",
    ],
)
