load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Copyright 2025 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "dw_convs_shared_weights_module",
    srcs = ["test_dw_convs_with_shared_weights.py"],
    deps = [
        "//executorch/backends/arm/test:arm_tester_lib",
    ],
)

fbcode_target(_kind = runtime.python_binary,
    name = "test_conv_to_fc_cycles",
    srcs = ["test_conv_to_fc_cycles.py"],
    main_function = "executorch.backends.arm.test.misc.test_conv_to_fc_cycles.main",
    deps = [
        "//executorch/backends/arm:ethosu",
        "//executorch/backends/arm:_factory",
        "//executorch/backends/arm/quantizer:lib",
        "//executorch/exir:lib",
    ],
)
