# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")

oncall("executorch")

define_common_targets()

fbcode_target(
    _kind = runtime.cxx_library,
    name = "aot_ops_test_lib",
    srcs = [
        "register_ops_aot_for_test.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/extension/aten_util:aten_bridge",
        "//executorch/kernels/portable/cpu:op_grid_sampler_2d",
        "//executorch/kernels/portable/cpu:op_upsample_bilinear2d",
        "//executorch/kernels/portable/cpu:op_upsample_bilinear2d_aa",
        "//executorch/kernels/portable/cpu:op_upsample_nearest2d",
        "//executorch/runtime/core/exec_aten:lib",
    ],
    external_deps = [
        "libtorch",
    ],
)
