# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeSystem.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/ExternalProject-download.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/ExternalProject.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/miniconda/share/cmake-3.19/Modules/RepositoryInfo.txt.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/tmp_executorch/executorch/FP16-download/CMakeFiles/3.19.4/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/tmp_executorch/executorch/FP16-download/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/chenlai/tmp_executorch/executorch/FP16-download/fp16-prefix/tmp/fp16-cfgcmd.txt.in))

/Users/chenlai/tmp_executorch/executorch/FP16-download/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Users/chenlai/miniconda/bin/cmake -H/Users/chenlai/tmp_executorch/executorch/FP16-download -B/Users/chenlai/tmp_executorch/executorch/FP16-download
