#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
"""Embed the per-op test models into the all-ops firmware.

Reads ``models/manifest.json`` (produced by generate_test_models.py) and emits
three sources the consumer build compiles in:

  * embedded_models_blob.S  -- ``.incbin`` of each <name>.pte into .rodata, so
    the image is self-contained and needs no semihosting filesystem access at
    run time. (The ``.S`` stem is distinct from embedded_models.cpp to avoid
    AC6's cbuild2cmake object-name clash.)
  * embedded_models.cpp     -- the g_embedded_models[] table referencing the
    blob symbols.
  * embedded_models.h       -- the EmbeddedModel struct.

Each test is fully self-contained in its .pte: besides the model, the program
carries constant methods (nb_inputs, nb_outputs, atol, rtol, channel_last,
input_<i>, output_<i>) that main.cpp executes to discover inputs, expected
outputs and tolerances. The manifest therefore only maps op/category to a
.pte file name; there are no side-band .bin files.

The ``.incbin`` paths are RELATIVE to this directory (``models/<name>.pte``).
The consumer project carries ``add-path: [.]`` -> ``-I<project-dir>``, which the
assembler searches for ``.incbin``, so the same generated file resolves whether
the build runs on the host or inside the Docker build container (host absolute
paths would not exist in the container).

If ``models/manifest.json`` is absent (build/link-coverage only, no torch
export step), a valid empty stub is emitted so the image still links and runs
(reporting 0/0). Re-run whenever the manifest or any model changes.

"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent

_H_CONTENT = """\
// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#pragma once

#include <cstddef>

struct EmbeddedModel {
    const char* op;
    const char* category;
    const unsigned char* pte_data;
    std::size_t pte_size;
};

extern const EmbeddedModel g_embedded_models[];
extern const std::size_t g_embedded_models_count;
"""

# A 1-element dummy array (never indexed: count is 0) keeps g_embedded_models a
# well-formed definition when no models are embedded -- C++ has no zero-length
# arrays.
_CPP_STUB = """\
// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
// Stub: no models/manifest.json found (build/link coverage only).
#include "embedded_models.h"

const EmbeddedModel g_embedded_models[] = {
    { "", "", nullptr, 0 },
};
const std::size_t g_embedded_models_count = 0;
"""

_S_STUB = """\
/* AUTO-GENERATED by gen_embedded_models.py -- do not edit. */
/* Stub: no models embedded (build/link coverage only). */
"""


def _sym(name: str) -> str:
    return f"_emb_pte_{name}"


def build(models_dir: Path, output_dir: Path) -> tuple[str, str, str, int, int]:
    """Return (blob_s, cpp, header, n_models, n_bytes)."""
    manifest_path = models_dir / "manifest.json"
    if not manifest_path.exists():
        return _S_STUB, _CPP_STUB, _H_CONTENT, 0, 0

    manifest = json.loads(manifest_path.read_text())
    # .incbin paths are relative to output_dir (resolved via -I<project-dir>).
    rel_models = Path(os.path.relpath(models_dir, output_dir))

    s_lines = [
        "/* AUTO-GENERATED by gen_embedded_models.py -- do not edit. */",
        '    .section .rodata.embedded_models,"a",%progbits',
        "    .balign 16",
        "",
    ]
    cpp_lines = [
        "// AUTO-GENERATED by gen_embedded_models.py -- do not edit.",
        '#include "embedded_models.h"',
        "",
        'extern "C" {',
    ]
    table_entries: list[str] = []
    n_bytes = 0

    for entry in manifest:
        name = entry["name"]
        op = entry["op"]
        category = entry["category"]
        disk = models_dir / f"{name}.pte"
        # The manifest is the contract for what gets tested: silently dropping
        # a listed model would shrink the embedded set and the firmware would
        # report a full pass over fewer ops.
        if not disk.exists():
            raise SystemExit(
                f"ERROR: {disk} is listed in {manifest_path} but missing.\n"
                "  The models directory is stale or incomplete; re-run "
                "generate_test_models.py."
            )

        n_bytes += disk.stat().st_size
        s = _sym(name)
        incbin = (rel_models / f"{name}.pte").as_posix()
        s_lines.extend(
            [
                "    .balign 16",
                f"    .global {s}_start",
                f"{s}_start:",
                f'    .incbin "{incbin}"',
                f"    .global {s}_end",
                f"{s}_end:",
                "",
            ]
        )
        cpp_lines.extend(
            [
                f"extern const unsigned char {s}_start[];",
                f"extern const unsigned char {s}_end[];",
            ]
        )
        table_entries.append(
            f'    {{ "{op}", "{category}",\n'
            f"      {s}_start, static_cast<std::size_t>({s}_end - {s}_start) }},"
        )

    cpp_lines.append('}  // extern "C"')
    cpp_lines.append("")
    cpp_lines.append("const EmbeddedModel g_embedded_models[] = {")
    cpp_lines.extend(table_entries)
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_lines.append(
        "const std::size_t g_embedded_models_count = "
        "sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);"
    )
    cpp_lines.append("")
    return (
        "\n".join(s_lines),
        "\n".join(cpp_lines),
        _H_CONTENT,
        len(table_entries),
        n_bytes,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Embed per-op test models into the all-ops firmware"
    )
    parser.add_argument(
        "--models-dir",
        default=str(_HERE / "models"),
        help="directory with per-op .pte files + manifest.json",
    )
    parser.add_argument(
        "--output-dir",
        default=str(_HERE),
        help="where to write embedded_models.{h,cpp,_blob.S}",
    )
    args = parser.parse_args()

    models_dir = Path(args.models_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    blob_s, cpp, header, n_models, n_bytes = build(models_dir, output_dir)

    (output_dir / "embedded_models_blob.S").write_text(blob_s)
    (output_dir / "embedded_models.cpp").write_text(cpp)
    (output_dir / "embedded_models.h").write_text(header)

    if n_models:
        print(f"embedded {n_bytes:,} bytes across {n_models} models -> {output_dir}")
    else:
        print(f"no models/manifest.json under {models_dir}: wrote empty stub")
    return 0


if __name__ == "__main__":
    sys.exit(main())
