# Copyright (c) Meta Platforms, Inc. and affiliates.
# Copyright 2024 - 2026 NXP
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import logging
import os
import shutil

import numpy as np

import torch
from executorch.backends.nxp.backend.edge_helper import is_channels_last_dim_order

from executorch.backends.nxp.backend.ir.converter.conversion.translator import (
    dims_to_channels_last,
    torch_type_to_numpy_type,
)
from executorch.backends.nxp.tests.executorch_pipeline import ModelInputSpec
from executorch.devtools.visualization.visualization_utils import (
    visualize_with_clusters,
)
from executorch.exir import ExecutorchProgramManager
from torch._subclasses import FakeTensor


def save_pte_program(
    prog: ExecutorchProgramManager, model_name: str, output_dir: str = ""
) -> str:
    if model_name.endswith(".pte"):
        filename = model_name
        visualize_file_name = f"{model_name}.json"
    else:
        filename = os.path.join(output_dir, f"{model_name}.pte")
        visualize_file_name = os.path.join(output_dir, f"{model_name}.json")
    try:
        with open(filename, "wb") as file:
            prog.write_to_file(file)
            logging.info(f"Saved exported program to {filename}")
    except Exception as e:
        logging.error(f"Error while saving to {filename}: {e}")

    visualize_with_clusters(prog.exported_program(), visualize_file_name, False)
    return filename


def change_filepath_extension(path: str, extension: str) -> str:
    base, _ = os.path.splitext(path)
    return base + "." + extension


def store_txt_input_tensor(
    input_tensor_path: str,
    tensor_spec: ModelInputSpec | FakeTensor,
    quant_dataset: bool = False,
):
    dtype = np.int8 if quant_dataset else torch_type_to_numpy_type(tensor_spec.dtype)
    input_tensor = np.fromfile(input_tensor_path, dtype=dtype)
    int__max = np.iinfo(np.int32).max

    with open(change_filepath_extension(input_tensor_path, "txt"), "w") as f:
        f.write("Flattened tensor shape:" + str(input_tensor.shape))
        f.write("\nOriginal tensor shape:" + str(list(tensor_spec.shape)) + "\n")
        f.write(np.array2string(input_tensor, threshold=int__max))


def archive_test_dir(test_dir: str):
    shutil.make_archive(test_dir, "zip", test_dir)


def read_prepared_samples(
    dataset_dir: str, input_spec: list[ModelInputSpec]
) -> list[tuple[np.ndarray, ...]]:
    """Read numpy arrays generated by a `DatasetCreator`.

    :param dataset_dir: Directory containing the generated samples
    :param input_spec: List of ModelInputSpec defining the shape and type of each input

    :return:  List of tuples, where each tuple contains numpy arrays for one sample
    """
    all_samples = []

    # Multi-input: samples are in numbered subdirectories
    if len(input_spec) > 1:
        sample_dirs = sorted(
            [
                d
                for d in os.listdir(dataset_dir)
                if os.path.isdir(os.path.join(dataset_dir, d))
            ]
        )

        for sample_name in sample_dirs:
            sample_dir = os.path.join(dataset_dir, sample_name)
            current_samples = []

            for spec_idx, spec in enumerate(input_spec):
                bin_file_path = os.path.join(
                    sample_dir, f"{str(spec_idx).zfill(2)}.bin"
                )
                sample_vector = np.fromfile(
                    bin_file_path, dtype=torch_type_to_numpy_type(spec.dtype)
                ).reshape(spec.shape)
                current_samples.append(sample_vector)

            all_samples.append(tuple(current_samples))

    # Single-input: binary files are directly in dataset_dir
    else:
        bin_files = sorted([f for f in os.listdir(dataset_dir) if f.endswith(".bin")])

        for bin_file in bin_files:
            bin_file_path = os.path.join(dataset_dir, bin_file)
            sample_vector = np.fromfile(
                bin_file_path, dtype=torch_type_to_numpy_type(input_spec[0].dtype)
            ).reshape(input_spec[0].shape)
            all_samples.append((sample_vector,))

    return all_samples


def store_results(
    results: list[tuple[np.ndarray, ...]], output_dir: str, reference_dir: str
):
    """Store a list of output arrays in the directory structure matching the reference directory.

    :param results: List of tuples, where each tuple contains numpy arrays (outputs for one sample)
    :param output_dir: Directory where results will be stored

    Directory structure created matches reference_dir:
        output_dir/
        ├── sample_0/
        │   ├── 0000.bin
        │   └── 0001.bin
        ├── some_other_sample/
        │   ├── 0000.bin
        │   └── 0001.bin
    """
    os.makedirs(output_dir, exist_ok=True)

    # Get subdirectories from reference directory
    sample_dirs = sorted(
        [
            d
            for d in os.listdir(reference_dir)
            if os.path.isdir(os.path.join(reference_dir, d))
        ]
    )

    assert len(sample_dirs) == len(
        results
    ), f"Number of samples ({len(results)}) must match number of subdirectories in reference_dir ({len(sample_dirs)})"

    for _sample_idx, (sample_name, sample_outputs) in enumerate(
        zip(sample_dirs, results)
    ):
        sample_dir = os.path.join(output_dir, sample_name)
        os.makedirs(sample_dir, exist_ok=True)

        # Store each output tensor
        for output_idx, output_array in enumerate(sample_outputs):
            bin_file_name = f"{str(output_idx).zfill(4)}.bin"
            bin_file_path = os.path.join(sample_dir, bin_file_name)
            output_array.tofile(bin_file_path)


def process_input_sample(
    input_spec: list[ModelInputSpec], input_samples: tuple[np.ndarray, ...]
) -> list[torch.Tensor]:
    """Process input samples by converting them to PyTorch tensors with correct dimension order.

    :param input_spec: List of ModelInputSpec defining the shape, type, and dimension order of each input
    :param input_samples: Tuple of numpy arrays representing one sample

    :return: List of PyTorch tensors with correct dimension order
    """
    current_input_samples = []
    for spec, sample in zip(input_spec, input_samples, strict=True):
        match spec.dim_order:
            case torch.contiguous_format:
                # Use the data as is, just turn it into a PyTorch tensor.
                sample = torch.tensor(sample)

            case torch.channels_last:
                # The tensor data was stored by the DatasetCreator as channels last (NHWC), but it was now
                #  incorrectly parsed as contiguous/channels first (NCHW). Transpose it to channels last to preserve
                #  the semantics.
                channels_last_shape = dims_to_channels_last(list(spec.shape))
                sample = np.moveaxis(sample.reshape(channels_last_shape), -1, 1)
                sample = torch.tensor(sample).to(memory_format=torch.channels_last)

            case _:
                raise ValueError(f"Unsupported dim_order: {spec.dim_order}")

        current_input_samples.append(sample)

    return current_input_samples


def process_output_sample(
    output: tuple[torch.Tensor, ...] | torch.Tensor, output_spec: list[torch.Tensor]
) -> list[np.ndarray]:
    """Process output tensors by converting them to numpy arrays with correct dimension order.

    :param output: Model output - either a single tensor or tuple of tensors
    :param output_spec: List of output tensor specifications

    :return: List of numpy arrays with correct dimension order matching NPU output format
    """

    if isinstance(output, torch.Tensor):
        output = (output,)

    current_outputs = []

    for o, o_spec in zip(output, output_spec, strict=True):
        dim_order = list(o_spec.dim_order())  # ExecuTorch dim order.
        rank = len(o_spec.shape)
        if dim_order == list(range(rank)):  # Contiguous dim order.
            current_outputs.append(o.detach().numpy())

        elif is_channels_last_dim_order(dim_order):  # Channels last dim order.
            # The NPU variant outputs channels last (NHWC). We need to convert the CPU output to match.
            o = o.detach().numpy().reshape(o_spec.shape)
            current_outputs.append(np.moveaxis(o, 1, -1))

        else:
            raise ValueError(f"Unsupported dim_order: {o_spec.dim_order}")

    return current_outputs
