load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")

oncall("executorch")

fbcode_target(_kind = python_binary,
    name = "export_model",
    srcs = [
        "export_model.py",
    ],
    main_function = "executorch.examples.models.phi-3-mini-lora.export_model.main",
    deps = [
        "fbsource//third-party/pypi/tiktoken:tiktoken",  # @manual
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//pytorch/torchtune:lib",
    ],
)
