load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load(":targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/extension/pytree/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.cxx_python_extension,
    name = "pybindings",
    srcs = [
        "pybindings.cpp",
    ],
    base_module = "executorch.extension.pytree",
    deps = [
        ":pytree",
    ],
    external_deps = [
        "pybind11",
    ],
)

fbcode_target(_kind = runtime.cxx_python_extension,
    name = "pybindings_debug",
    srcs = [
        "pybindings.cpp",
    ],
    base_module = "executorch.extension.pytree",
    deps = [
        ":pytree",
    ],
    external_deps = [
        "pybind11",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "pylib",
    srcs = [
        "__init__.py",
    ],
    base_module = "executorch.extension.pytree",
    deps = [
        ":pybindings",
        "//caffe2:torch",
    ],
)
