load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "xnnpack_passes",
    srcs = native.glob(["*.py"]),
    deps = [
        "//caffe2:torch",
        "//executorch/backends/transforms:addmm_mm_to_linear",
        "//executorch/backends/transforms:remove_clone_ops",
        "//executorch/backends/transforms:lib",
        "//executorch/backends/xnnpack/partition:partitioner_graphs",
        "//executorch/backends/xnnpack/serialization:xnnpack_schema",
        "//executorch/backends/xnnpack/utils:xnnpack_utils",
        "//executorch/exir:lib",
        "//executorch/exir:pass_base",
        "//executorch/exir/dialects:lib",
        "//executorch/exir/passes:const_prop_pass",
        "//executorch/exir/passes:memory_format_ops_pass",
        "//executorch/exir/program:program",
        "//executorch/backends/transforms:utils",
    ],
)
