load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_library,
    name = "passes",
    srcs = glob(["*.py"]),
    deps = [
        "//executorch/backends/arm:common",
        "//executorch/backends/arm:constants",
        "//executorch/backends/arm/tosa:utils",
        "//executorch/backends/arm/tosa/dialect:lib",
        "//executorch/backends/transforms:fuse_view_copy",
        "//executorch/backends/transforms:remove_getitem_op",
        "//executorch/backends/transforms:replace_scalar_with_tensor",
        "//executorch/backends/xnnpack/_passes:xnnpack_passes",
        "//executorch/exir:lib",
        "//executorch/backends/transforms:utils",
        "//executorch/backends/transforms:decompose_sdpa",
    ],
)
