load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("executorch")

fbcode_target(
    _kind = python_library,
    name = "models",
    srcs = [
        "__init__.py",
        "deep_autoencoder.py",
        "ds_cnn.py",
        "mobilenet_v1_025.py",
        "resnet8.py",
        "streaming_wakeword.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/examples/models:model_base",
    ],
)
