load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load(":targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,)

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "cache",
    srcs = [
        "reference_cache.py",
        "update_and_attend.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:_warnings",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test_update_and_attend",
    srcs = [
        "test_update_and_attend.py",
    ],
    deps = [
        ":cache",
        "//caffe2:torch",
    ],
)
