load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

fbcode_target(_kind = runtime.python_binary,
    name = "export_gemma4_text_decoder_coreml",
    srcs = [
        "export_gemma4_text_decoder_coreml.py",
    ],
    main_module = "executorch.examples.apple.coreml.gemma4.export_gemma4_text_decoder_coreml",
    _is_external_target = True,
    base_module = "executorch.examples.apple.coreml.gemma4",
    visibility = ["PUBLIC"],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/apple/coreml:backend",
        "//executorch/backends/apple/coreml:partitioner",
        "//executorch/examples/models/gemma4:text_decoder",
        "//executorch/exir:lib",
        "//executorch/extension/export_util:export_util",
    ],
)
