load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# add this empty BUCK file to unblock landing. Without this, we get land error:
#   "No build file at xplat/executorch/exir/dialects/edge/test/BUCK when resolving target fbsource//xplat/executorch/exir/dialects/edge/test:."


# !!!! fbcode/executorch/exir/dialects/edge/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")


fbcode_target(_kind = python_unittest,
    name = "test_edge_yaml",
    srcs = [
        "test_edge_yaml.py",
    ],
    resources = {
        "//executorch/exir/dialects/edge:edge_yaml": "edge.yaml",
    },
    labels = ["long_running"],
    deps = [
        "fbsource//third-party/pypi/expecttest:expecttest",  # @manual
        "//caffe2:torch",
        "//executorch/exir/dialects/edge/dtype:lib",
        "//executorch/exir/dialects/edge/spec:lib",
    ],
)

fbcode_target(_kind = python_unittest,
    name = "test_edge_ops",
    srcs = [
        "test_edge_ops.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir/dialects:lib",
        "//executorch/exir/dialects/edge:lib",
    ],
)
