load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain xplat-only targets.

load(":targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/examples/models/llama/runner/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

# Any targets that should be shared between fbcode and xplat must be defined in
# targets.bzl. This file can contain fbcode-only targets.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_common_targets")


fbcode_target(_kind = define_common_targets,)

fbcode_target(_kind = runtime.python_library,
    name = "eager_runner_library",
    srcs = [
        "eager.py",
        "generation.py"
    ],
    _is_external_target = True,
    base_module = "executorch.examples.models.llama.runner",
    visibility = ["PUBLIC"],
    deps = [
        "//executorch/examples/models/llama:export_library",
    ],
)

fbcode_target(_kind = runtime.python_binary,
    name = "eager",
    main_function = "executorch.examples.models.llama.runner.eager.main",
    deps = [
        ":eager_runner_library",
        "//caffe2:torch",
    ],
)
