load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")


fbcode_target(_kind = runtime.python_library,
    name = "numerical_comparator_base",
    srcs = ["numerical_comparator_base.py"],
    deps = [],
)

fbcode_target(_kind = runtime.python_library,
    name = "l1_numerical_comparator",
    srcs = ["l1_numerical_comparator.py"],
    deps = [
        "//executorch/devtools/inspector/numerical_comparator:numerical_comparator_base",
        "//executorch/devtools/inspector:inspector_utils",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "mse_numerical_comparator",
    srcs = ["mse_numerical_comparator.py"],
    deps = [
        "//executorch/devtools/inspector/numerical_comparator:numerical_comparator_base",
        "//executorch/devtools/inspector:inspector_utils",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "snr_numerical_comparator",
    srcs = ["snr_numerical_comparator.py"],
    deps = [
        "//executorch/devtools/inspector/numerical_comparator:numerical_comparator_base",
        "//executorch/devtools/inspector:inspector_utils",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "lib",
    srcs = ["__init__.py"],
    deps = [
        ":l1_numerical_comparator",
        ":mse_numerical_comparator",
        ":snr_numerical_comparator",
    ],
)
