load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name="replace_quant_nodes_pass",
    srcs=[
        "replace_quant_nodes_pass.py",
        "quantized_op_fusion_pass.py",
    ],
    deps=[
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/exir:pass_base",
        "//executorch/exir/dialects:lib",
        "//executorch/backends/cortex_m/ops:ops",
        "//executorch/backends/cortex_m/passes:passes_utils",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name="passes_utils",
    srcs=[
        "passes_utils.py",
    ],
    deps=[
        "fbcode//caffe2:torch",
    ],
)
