load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name="replace_quant_nodes_pass",
    srcs=[
        "replace_quant_nodes_pass.py",
    ],
    deps=[
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/exir:pass_base",
        "//executorch/exir/dialects:lib",
        "//executorch/backends/cortex_m/ops:ops",
        "//executorch/backends/cortex_m/passes:passes_utils",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name="cortex_passes",
    srcs=[
        "activation_fusion_pass.py",
        "aten_to_cortex_m_pass.py",
        "clamp_hardswish_pass.py",
        "cortex_m_pass.py",
        "cortex_m_pass_manager.py",
        "decompose_hardswish_pass.py",
        "decompose_lstm_cell_pass.py",
        "decompose_mean_pass.py",
        "quantized_clamp_activation_pass.py",
        "scratch_buffer_sizes.py",
    ],
    deps=[
        "//caffe2:torch",
        "//executorch/backends/arm/_passes:passes",
        "//executorch/backends/cortex_m:cmsis_nn",
        "//executorch/backends/cortex_m:target_config",
        "//executorch/backends/cortex_m/ops:ops",
        "//executorch/backends/cortex_m/passes:passes_utils",
        "//executorch/backends/cortex_m/passes:replace_quant_nodes_pass",
        "//executorch/backends/transforms:aten_to_dialect_pass",
        "//executorch/backends/transforms:remove_getitem_op",
        "//executorch/backends/transforms:replace_scalar_with_tensor",
        "//executorch/backends/transforms:utils",
        "//executorch/exir:lib",
        "//executorch/exir:pass_base",
        "//executorch/exir:pass_manager",
        "//executorch/exir/program:lib",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name="passes_utils",
    srcs=[
        "passes_utils.py",
    ],
    deps=[
        "fbcode//caffe2:torch",
    ],
)
