load("@fbsource//tools/build_defs/android:fb_android_library.bzl", "fb_android_library")

oncall("executorch")

fb_android_library(
    name = "executorch",
    srcs = [
        "executorch_android/src/main/java/org/pytorch/executorch/DType.java",
        "executorch_android/src/main/java/org/pytorch/executorch/EValue.java",
        "executorch_android/src/main/java/org/pytorch/executorch/Module.java",
        "executorch_android/src/main/java/org/pytorch/executorch/NativePeer.java",
        "executorch_android/src/main/java/org/pytorch/executorch/Tensor.java",
        "executorch_android/src/main/java/org/pytorch/executorch/annotations/Experimental.java",
    ],
    autoglob = False,
    language = "JAVA",
    deps = [
        "//fbandroid/java/com/facebook/jni:jni",
        "//fbandroid/libraries/soloader/java/com/facebook/soloader/nativeloader:nativeloader",
    ],
)

fb_android_library(
    name = "executorch_llama",
    srcs = [
        "executorch_android/src/main/java/org/pytorch/executorch/LlamaCallback.java",
        "executorch_android/src/main/java/org/pytorch/executorch/LlamaModule.java",
    ],
    autoglob = False,
    language = "JAVA",
    deps = [
        ":executorch",
        "//fbandroid/java/com/facebook/jni:jni",
        "//fbandroid/libraries/soloader/java/com/facebook/soloader/nativeloader:nativeloader",
    ],
)
