load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//tools/build_defs/android:fb_android_library.bzl", "fb_android_library")

oncall("executorch")

# Thin Android shell. The platform-neutral API sources moved to
# //xplat/executorch/extension/java; these targets keep their historical names
# and re-export the shared targets so existing dependents keep working.

non_fbcode_target(_kind = fb_android_library,
    name = "executorch",
    warnings_as_errors = False,
    required_for_source_only_abi = True,
    srcs = [
        "executorch_android/src/main/java/org/pytorch/executorch/AndroidLogger.kt",
        "executorch_android/src/main/java/org/pytorch/executorch/ExecuTorchInitProvider.kt",
    ],
    autoglob = False,
    language = "KOTLIN",
    pure_kotlin = False,
    extra_kotlinc_arguments = ["-Xjvm-default=all"],
    exported_deps = [
        "//xplat/executorch/extension/java:executorch",
    ],
    deps = [
        "//fbandroid/java/com/facebook/jni:jni",
        "//fbandroid/libraries/soloader/java/com/facebook/soloader/nativeloader:nativeloader",
    ],
)

non_fbcode_target(_kind = fb_android_library,
    name = "executorch_training",
    warnings_as_errors = False,
    autoglob = False,
    language = "KOTLIN",
    exported_deps = [
        "//xplat/executorch/extension/java:executorch_training",
    ],
)

non_fbcode_target(_kind = fb_android_library,
    name = "executorch_llama",
    warnings_as_errors = False,
    autoglob = False,
    language = "KOTLIN",
    exported_deps = [
        "//xplat/executorch/extension/java:executorch_llama",
    ],
)

non_fbcode_target(_kind = fb_android_library,
    name = "executorch_asr",
    warnings_as_errors = False,
    autoglob = False,
    language = "KOTLIN",
    exported_deps = [
        "//xplat/executorch/extension/java:executorch_asr",
    ],
)
