load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "delegation_info",
    srcs = [
        "__init__.py",
        "delegation_info.py",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//third-party/pypi/pandas:pandas",
        "//caffe2:torch",
        "//executorch/exir:lowered_backend_module",
        "//executorch/exir/backend/canonical_partitioners:duplicate_constant_node_pass",
    ],
)
