# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Generate src/mv2_input.h from a real image.

The sample ships with a synthetic input so it can run without bundling an
image. That exercises the runtime but produces meaningless predictions. Point
this script at a photograph to get a header the device can actually classify:

    python gen_input.py cat.jpg

The image is resized and centre-cropped using the preset that ships with
torchvision's default MobileNetV2 weights, then stored as uint8 RGB in NCHW
order. The same weights produce the float32 prediction recorded in a comment,
so the device output has a reference to be compared against. Normalisation is
applied on device by main.cpp.

Requires: pillow, torch, torchvision.
"""

import argparse
import os

import numpy as np
import torch
import torchvision
from PIL import Image
from torchvision import transforms

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "mv2_input.h")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", help="path to a source image")
    parser.add_argument("-o", "--output", default=HEADER, help="header to write")
    args = parser.parse_args()

    # Match examples/models/mobilenet_v2, which exports MobileNet_V2_Weights.DEFAULT.
    # Resize and crop are taken from the weights so this cannot drift if the
    # default checkpoint changes.
    weights = torchvision.models.MobileNet_V2_Weights.DEFAULT
    model = torchvision.models.mobilenet_v2(weights=weights).eval()
    categories = weights.meta["categories"]

    preset = weights.transforms()
    resize_size = preset.resize_size[0]
    crop_size = preset.crop_size[0]

    crop = transforms.Compose(
        [transforms.Resize(resize_size), transforms.CenterCrop(crop_size)]
    )
    normalize = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize(mean=preset.mean, std=preset.std),
        ]
    )

    # main.cpp applies these constants on device; bail out if the weights
    # ever move to a different normalisation.
    device_mean = [0.485, 0.456, 0.406]
    device_std = [0.229, 0.224, 0.225]
    if list(preset.mean) != device_mean or list(preset.std) != device_std:
        raise SystemExit(
            f"weights expect mean={list(preset.mean)} std={list(preset.std)}, but "
            f"main.cpp applies mean={device_mean} std={device_std}; update both."
        )

    image = crop(Image.open(args.image).convert("RGB"))
    with torch.no_grad():
        logits = model(normalize(image).unsqueeze(0))[0]
    probs = torch.softmax(logits, dim=0)
    top1 = int(torch.argmax(logits))
    print(
        f"{os.path.basename(args.image)} -> class {top1} "
        f"({categories[top1]}) {probs[top1].item() * 100:.1f}%"
    )

    chw = np.transpose(np.asarray(image, dtype=np.uint8), (2, 0, 1)).copy()
    raw = chw.tobytes()

    lines = [
        "/* Copyright (c) Meta Platforms, Inc. and affiliates.",
        " * All rights reserved.",
        " *",
        " * This source code is licensed under the BSD-style license found in the",
        " * LICENSE file in the root directory of this source tree.",
        " *",
        f" * Generated by gen_input.py from {os.path.basename(args.image)}.",
        f" * Resized {resize_size}, centre-cropped {crop_size}, uint8 RGB in NCHW order.",
        " *",
        f" * float32 torchvision MobileNetV2 ({weights.name}) predicts class {top1} "
        f"({categories[top1]}) at {probs[top1].item() * 100:.1f}%.",
        " */",
        "",
        "#ifndef MV2_INPUT_H",
        "#define MV2_INPUT_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define MV2_INPUT_SIZE {len(raw)}",
        f"#define MV2_HOST_TOP1 {top1}",
        f'#define MV2_HOST_LABEL "{categories[top1]}"',
        "",
        "static const uint8_t mv2_input_data[MV2_INPUT_SIZE] __attribute__((aligned(4)))",
        '__attribute__((section(".rodata.mv2_input"))) = {',
    ]
    for i in range(0, len(raw), 16):
        lines.append("    " + ",".join(f"0x{b:02x}" for b in raw[i : i + 16]) + ",")
    lines += ["};", "", "#endif /* MV2_INPUT_H */"]

    with open(args.output, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
