# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Generate src/mv2_input.h from a real image.

The sample ships with a synthetic input so it can run without bundling an
image. That exercises the runtime but produces meaningless predictions. Point
this script at a photograph to get a header the device can actually classify:

    python gen_input.py cat.jpg

The image is resized to 256, centre-cropped to 224x224 and stored as uint8 RGB
in NCHW order, matching the normalisation main.cpp applies on device. The
float32 torchvision prediction is recorded in a comment so the device output
has a reference to be compared against.

Requires: pillow, torch, torchvision.
"""

import argparse
import os

import numpy as np
import torch
import torchvision
from PIL import Image
from torchvision import transforms

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "mv2_input.h")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", help="path to a source image")
    parser.add_argument("-o", "--output", default=HEADER, help="header to write")
    args = parser.parse_args()

    weights = torchvision.models.MobileNet_V2_Weights.IMAGENET1K_V1
    model = torchvision.models.mobilenet_v2(weights=weights).eval()
    categories = weights.meta["categories"]

    crop = transforms.Compose([transforms.Resize(256), transforms.CenterCrop(224)])
    normalize = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )

    image = crop(Image.open(args.image).convert("RGB"))
    with torch.no_grad():
        logits = model(normalize(image).unsqueeze(0))[0]
    probs = torch.softmax(logits, dim=0)
    top1 = int(torch.argmax(logits))
    print(
        f"{os.path.basename(args.image)} -> class {top1} "
        f"({categories[top1]}) {probs[top1].item() * 100:.1f}%"
    )

    chw = np.transpose(np.asarray(image, dtype=np.uint8), (2, 0, 1)).copy()
    raw = chw.tobytes()

    lines = [
        "/* Copyright (c) Meta Platforms, Inc. and affiliates.",
        " * All rights reserved.",
        " *",
        " * This source code is licensed under the BSD-style license found in the",
        " * LICENSE file in the root directory of this source tree.",
        " *",
        f" * Generated by gen_input.py from {os.path.basename(args.image)}.",
        " * Resized 256, centre-cropped 224, uint8 RGB in NCHW order.",
        " *",
        f" * float32 torchvision MobileNetV2 predicts class {top1} "
        f"({categories[top1]}) at {probs[top1].item() * 100:.1f}%.",
        " */",
        "",
        "#ifndef MV2_INPUT_H",
        "#define MV2_INPUT_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define MV2_INPUT_SIZE {len(raw)}",
        f"#define MV2_HOST_TOP1 {top1}",
        f'#define MV2_HOST_LABEL "{categories[top1]}"',
        "",
        "static const uint8_t mv2_input_data[MV2_INPUT_SIZE] __attribute__((aligned(4)))",
        '__attribute__((section(".rodata.mv2_input"))) = {',
    ]
    for i in range(0, len(raw), 16):
        lines.append("    " + ",".join(f"0x{b:02x}" for b in raw[i : i + 16]) + ",")
    lines += ["};", "", "#endif /* MV2_INPUT_H */"]

    with open(args.output, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
