# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
# Copyright 2025-2026 Arm Limited and/or its affiliates.
#
# SPDX-License-Identifier: Apache-2.0

# Enable ExecuTorch
CONFIG_EXECUTORCH=y

# C++
CONFIG_CPP=y
CONFIG_STD_CPP17=y

# Config - increased for MobileNetV2 memory requirements
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_HEAP_MEM_POOL_SIZE=65536

# Logging
CONFIG_REQUIRES_FLOAT_PRINTF=y

# Configuration for selective operator builds
CONFIG_EXECUTORCH_BUILD_PORTABLE_OPS=n

# Enable Helium (MVE) builds of CMSIS-NN by selecting the FPU and hard-float ABI.
CONFIG_FPU=y
CONFIG_FP_HARDABI=y

# Setup memory requirements for MobileNetV2.
# MV2 is a larger model than the default hello-executorch add model.
CONFIG_EXECUTORCH_METHOD_ALLOCATOR_POOL_SIZE=1572864
CONFIG_EXECUTORCH_TEMP_ALLOCATOR_POOL_SIZE=1572864
