# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(
    _kind = runtime.python_library,
    name = "test_operators",
    srcs = glob(["*.py"]),
    deps = [
        "//caffe2:torch",
        "//executorch/backends/test/suite:flow",
        "fbsource//third-party/pypi/pytest:pytest",
    ],
)
