load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("targets.bzl", "define_common_targets")


non_fbcode_target(_kind = define_common_targets,)

# !!!! fbcode/executorch/backends/cortex_m/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("targets.bzl", "define_common_targets")

fbcode_target(_kind = python_unittest,
    name="test_replace_quant_nodes",
    srcs=[
        "test_helpers_passes_utils.py",
        "test_replace_quant_nodes.py",
    ],
    deps=[
        "//pytorch/ao:torchao",  # @manual
        "//caffe2:torch",
        "//executorch/backends/cortex_m/passes:replace_quant_nodes_pass",
        "//executorch/backends/cortex_m/ops:ops",
    ],
)

fbcode_target(_kind = define_common_targets,)
