load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Copyright 2025-2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load(":targets.bzl", "define_arm_tests")


oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "conftest",
    srcs = ["conftest.py"],
    deps = [
        "//executorch/exir:lib",
        "//executorch/exir/backend:compile_spec_schema",
        "fbsource//third-party/pypi/pytest:pytest",
    ]
)

fbcode_target(_kind = runtime.python_library,
    name = "runner_utils",
    srcs = ["runner_utils.py"],
    resources = {
        "fbsource//third-party/flatbuffers:flatc-host": "flatbuffers-flatc",
    },
    deps = [
        ":conftest",
        "//executorch/backends/arm:arm_compile_spec",
        "//executorch/backends/arm:ethosu",
        "//executorch/backends/arm/tosa:compile_spec",
        "//executorch/backends/arm/tosa:schemas",
        "//executorch/backends/arm:vgf",
        "//executorch/backends/arm/tosa:specification",
        "//executorch/exir:lib",
        "//executorch/exir/backend:compile_spec_schema",
    ]
)

fbcode_target(_kind = runtime.python_library,
    name = "common",
    srcs = ["common.py"],
    deps = [
        ":runner_utils",
        "//executorch/backends/arm/tosa:tosa",
        "fbsource//third-party/pypi/pytest:pytest",
    ]
)

fbcode_target(_kind = runtime.python_library,
    name = "custom_vgf_test_utils",
    srcs = ["_custom_vgf_test_utils.py"],
    resources = [
        "assets/test_add_buffer.glsl",
        "assets/test_grid_read_tensor_debug.glsl",
        "assets/test_grid_sample_buffer_nchw_debug.glsl",
        "assets/test_grid_sample_sampler.glsl",
        "assets/test_grid_sample_sampler_buffer_debug.glsl",
        "assets/test_identity_buffer.glsl",
        "assets/test_identity_image_packed_buffer.glsl",
        "assets/test_threes_buffer.glsl",
        "assets/test_threes_image_packed_buffer.glsl",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/arm:constants",
        "//executorch/backends/arm/_passes:passes",
        "//executorch/backends/arm/tosa/dialect:lib",
        "//executorch/exir:lib",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "vgf_runtime_test_utils",
    srcs = ["runtime/_vgf_runtime_test_utils.py"],
    deps = [
        ":custom_vgf_test_utils",
        ":runner_utils",
        "//executorch/backends/arm:vgf",
        "//executorch/backends/arm/_passes:passes",
        "//executorch/exir:lib",
        "fbsource//third-party/pypi/pytest:pytest",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "arm_tester_serialize",
    srcs = ["tester/serialize.py"],
    deps = [
        "//executorch/backends/test/harness:tester",
        "//executorch/devtools/backend_debug:delegation_info",
    ]
)

fbcode_target(_kind = runtime.python_library,
    name = "arm_tester_lib",
    srcs = glob(["tester/*.py"], exclude = ["tester/serialize.py"]),
    deps = [
        ":common",
        "//executorch/backends/test/harness:tester",
        "//executorch/backends/arm:ethosu",
        "//executorch/backends/arm/quantizer:lib",
        "//executorch/backends/arm/tosa:mapping",
        "//executorch/backends/arm:vgf",
        "//executorch/backends/arm:_factory",
        "//executorch/devtools/backend_debug:delegation_info",
        "//executorch/exir/backend:operator_support",
        "fbsource//third-party/pypi/tabulate:tabulate",
    ]
)


fbcode_target(_kind = runtime.python_library,
    name = "arm_tester",
    deps = [
        "//executorch/backends/arm/test:arm_tester_lib",
        "//executorch/backends/arm/test:arm_tester_serialize",
    ]
)

fbcode_target(_kind = define_arm_tests,)
