load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
oncall("executorch")
# add this empty BUCK file to unblock landing. Without this, we get land error:
#   "No build file at xplat/executorch/exir/BUCK when resolving target fbsource//xplat/executorch/exir:."


# !!!! fbcode/executorch/exir/capture/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")


fbcode_target(_kind = runtime.python_library,
    name = "lib",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":capture",
        ":config",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "capture",
    srcs = [
        "_capture.py",
    ],
    deps = [
        ":config",
        "//caffe2:torch",
        "//executorch/exir:error",
        "//executorch/exir:tracer",
        "//executorch/exir/program:lib",
        "//executorch/exir/program:program",
        "//executorch/exir/verification:verifier",
    ],
)

fbcode_target(_kind = runtime.python_library,
    name = "config",
    srcs = [
        "_config.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:dynamic_shape",
        "//executorch/exir:pass_manager",
        "//executorch/exir:tracer",
        "//executorch/exir/passes:lib",
        "//executorch/exir/passes:sym_shape_eval_pass",
    ],
)
