# Auto-generated FlatBuffer bindings
# Re-exports from mlx_delegate namespace for convenient imports

from executorch.backends.mlx.serialization._generated.mlx_delegate.ARangeNode import ARangeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AbsNode import AbsNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AddIntNode import AddIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AddNode import AddNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AddmmNode import AddmmNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AllNode import AllNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AnyNode import AnyNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArccosNode import ArccosNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArccoshNode import ArccoshNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArcsinNode import ArcsinNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArcsinhNode import ArcsinhNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArctanNode import ArctanNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArctanhNode import ArctanhNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArgPartitionNode import ArgPartitionNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArgmaxNode import ArgmaxNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArgminNode import ArgminNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ArgsortNode import ArgsortNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AsStridedNode import AsStridedNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.AsTypeNode import AsTypeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Atan2Node import Atan2Node
from executorch.backends.mlx.serialization._generated.mlx_delegate.BitwiseXorNode import BitwiseXorNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.BroadcastToNode import BroadcastToNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.CeilNode import CeilNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ClipNode import ClipNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ConcatenateNode import ConcatenateNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ContiguousNode import ContiguousNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Conv1DNode import Conv1DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Conv2DNode import Conv2DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Conv3DNode import Conv3DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ConvTranspose1DNode import ConvTranspose1DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ConvTranspose2DNode import ConvTranspose2DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ConvTranspose3DNode import ConvTranspose3DNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.CosNode import CosNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.CoshNode import CoshNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.CumsumNode import CumsumNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.DequantizeNode import DequantizeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.DivideNode import DivideNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.EqualNode import EqualNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ErfNode import ErfNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ExpNode import ExpNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ExpandDimsNode import ExpandDimsNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Expm1Node import Expm1Node
from executorch.backends.mlx.serialization._generated.mlx_delegate.FloatOrVid import FloatOrVid
from executorch.backends.mlx.serialization._generated.mlx_delegate.FloorDivideIntNode import FloorDivideIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.FloorDivideNode import FloorDivideNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.FloorNode import FloorNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.FullLikeNode import FullLikeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.FullNode import FullNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GatherMmNode import GatherMmNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GatherNode import GatherNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GatherQmmNode import GatherQmmNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GeluNode import GeluNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GreaterEqualNode import GreaterEqualNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.GreaterNode import GreaterNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.IdCopyNode import IdCopyNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.IndexCopyNode import IndexCopyNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Instruction import Instruction
from executorch.backends.mlx.serialization._generated.mlx_delegate.InstructionChain import InstructionChain
from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVid import IntOrVid
from executorch.backends.mlx.serialization._generated.mlx_delegate.IntOrVidOrTid import IntOrVidOrTid
from executorch.backends.mlx.serialization._generated.mlx_delegate.ItemIntNode import ItemIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LayerNormNode import LayerNormNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LessEqualNode import LessEqualNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LessNode import LessNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Log10Node import Log10Node
from executorch.backends.mlx.serialization._generated.mlx_delegate.Log1pNode import Log1pNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Log2Node import Log2Node
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogAddExpNode import LogAddExpNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogNode import LogNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogSumExpNode import LogSumExpNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogicalAndNode import LogicalAndNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogicalNotNode import LogicalNotNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.LogicalOrNode import LogicalOrNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MLXGraph import MLXGraph
from executorch.backends.mlx.serialization._generated.mlx_delegate.MaxNode import MaxNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MaximumNode import MaximumNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MeanNode import MeanNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MedianNode import MedianNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MetalKernelNode import MetalKernelNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MinNode import MinNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MinimumNode import MinimumNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ModIntNode import ModIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MultiplyIntNode import MultiplyIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.MultiplyNode import MultiplyNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.NamedSlot import NamedSlot
from executorch.backends.mlx.serialization._generated.mlx_delegate.NegNode import NegNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.NoopNode import NoopNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.NotEqualNode import NotEqualNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.OpNode import OpNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.PadNode import PadNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.PartitionNode import PartitionNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.PowerNode import PowerNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ProdNode import ProdNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.QuantizedMatmulNode import QuantizedMatmulNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RMSNormNode import RMSNormNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ReciprocalNode import ReciprocalNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RemainderNode import RemainderNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RepeatNode import RepeatNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ReshapeNode import ReshapeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RopeNode import RopeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RoundNode import RoundNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.RsqrtNode import RsqrtNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ScanNode import ScanNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ScatterAddNode import ScatterAddNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SdpaNode import SdpaNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.ShapeDim import ShapeDim
from executorch.backends.mlx.serialization._generated.mlx_delegate.SigmoidNode import SigmoidNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SignNode import SignNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SiluNode import SiluNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SinNode import SinNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SinhNode import SinhNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SliceNode import SliceNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SliceUpdateNode import SliceUpdateNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SlotType import SlotType
from executorch.backends.mlx.serialization._generated.mlx_delegate.SlotVariant import SlotVariant
from executorch.backends.mlx.serialization._generated.mlx_delegate.SoftmaxNode import SoftmaxNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SortNode import SortNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SplitNode import SplitNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SqrtNode import SqrtNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SquareNode import SquareNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SqueezeNode import SqueezeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.StackNode import StackNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.StdNode import StdNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SubtractIntNode import SubtractIntNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SubtractNode import SubtractNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SumNode import SumNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.SymSizeNode import SymSizeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TakeAlongAxisNode import TakeAlongAxisNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TakeNode import TakeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TanNode import TanNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TanhNode import TanhNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TensorMeta import TensorMeta
from executorch.backends.mlx.serialization._generated.mlx_delegate.Tid import Tid
from executorch.backends.mlx.serialization._generated.mlx_delegate.TileNode import TileNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TransposeNode import TransposeNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TriNode import TriNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TrilNode import TrilNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.TriuNode import TriuNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.VarNode import VarNode
from executorch.backends.mlx.serialization._generated.mlx_delegate.Vid import Vid
from executorch.backends.mlx.serialization._generated.mlx_delegate.VidOrTid import VidOrTid
from executorch.backends.mlx.serialization._generated.mlx_delegate.WhereNode import WhereNode

__all__ = ['ARangeNode', 'AbsNode', 'AddIntNode', 'AddNode', 'AddmmNode', 'AllNode', 'AnyNode', 'ArccosNode', 'ArccoshNode', 'ArcsinNode', 'ArcsinhNode', 'ArctanNode', 'ArctanhNode', 'ArgPartitionNode', 'ArgmaxNode', 'ArgminNode', 'ArgsortNode', 'AsStridedNode', 'AsTypeNode', 'Atan2Node', 'BitwiseXorNode', 'BroadcastToNode', 'CeilNode', 'ClipNode', 'ConcatenateNode', 'ContiguousNode', 'Conv1DNode', 'Conv2DNode', 'Conv3DNode', 'ConvTranspose1DNode', 'ConvTranspose2DNode', 'ConvTranspose3DNode', 'CosNode', 'CoshNode', 'CumsumNode', 'DequantizeNode', 'DivideNode', 'EqualNode', 'ErfNode', 'ExpNode', 'ExpandDimsNode', 'Expm1Node', 'FloatOrVid', 'FloorDivideIntNode', 'FloorDivideNode', 'FloorNode', 'FullLikeNode', 'FullNode', 'GatherMmNode', 'GatherNode', 'GatherQmmNode', 'GeluNode', 'GreaterEqualNode', 'GreaterNode', 'IdCopyNode', 'IndexCopyNode', 'Instruction', 'InstructionChain', 'IntOrVid', 'IntOrVidOrTid', 'ItemIntNode', 'LayerNormNode', 'LessEqualNode', 'LessNode', 'Log10Node', 'Log1pNode', 'Log2Node', 'LogAddExpNode', 'LogNode', 'LogSumExpNode', 'LogicalAndNode', 'LogicalNotNode', 'LogicalOrNode', 'MLXGraph', 'MaxNode', 'MaximumNode', 'MeanNode', 'MedianNode', 'MetalKernelNode', 'MinNode', 'MinimumNode', 'ModIntNode', 'MultiplyIntNode', 'MultiplyNode', 'NamedSlot', 'NegNode', 'NoopNode', 'NotEqualNode', 'OpNode', 'PadNode', 'PartitionNode', 'PowerNode', 'ProdNode', 'QuantizedMatmulNode', 'RMSNormNode', 'ReciprocalNode', 'RemainderNode', 'RepeatNode', 'ReshapeNode', 'RopeNode', 'RoundNode', 'RsqrtNode', 'ScanNode', 'ScatterAddNode', 'SdpaNode', 'ShapeDim', 'SigmoidNode', 'SignNode', 'SiluNode', 'SinNode', 'SinhNode', 'SliceNode', 'SliceUpdateNode', 'SlotType', 'SlotVariant', 'SoftmaxNode', 'SortNode', 'SplitNode', 'SqrtNode', 'SquareNode', 'SqueezeNode', 'StackNode', 'StdNode', 'SubtractIntNode', 'SubtractNode', 'SumNode', 'SymSizeNode', 'TakeAlongAxisNode', 'TakeNode', 'TanNode', 'TanhNode', 'TensorMeta', 'Tid', 'TileNode', 'TransposeNode', 'TriNode', 'TrilNode', 'TriuNode', 'VarNode', 'Vid', 'VidOrTid', 'WhereNode']
