# Board-specific config for nRF54LM20DK (nRF54LM20B with AXON NPU)

# AXON NPU
CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=256
CONFIG_NRF_AXON_PSUM_BUFFER_SIZE=0

# RRAM must stay in standby mode for AXON
CONFIG_MPSL_FORCE_RRAM_ON_ALL_THE_TIME=y
