load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "qwen3",
    srcs = [
        "__init__.py",
        "convert_weights.py",
    ],
    _is_external_target = True,
    base_module = "executorch.examples.models.qwen3",
    resources = {
        "config/0_6b_config.json": "config/0_6b_config.json",
        "config/1_7b_config.json": "config/1_7b_config.json",
        "config/4b_config.json": "config/4b_config.json",
        "config/qwen3_xnnpack_q8da4w.yaml": "config/qwen3_xnnpack_q8da4w.yaml",
    },
    deps = [
        "//caffe2:torch",
        "//executorch/examples/models:model_base",
        "//executorch/examples/models/llama:llama2_model",
        "fbcode//pytorch/torchtune:lib",
    ],
    visibility = ["PUBLIC"],
)
