load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_binary,
    name = "export_bundled_program",
    main_function = ".export_bundled_program.main",
    main_src = "export_bundled_program.py",
    deps = [
        "//caffe2:torch",
        "//executorch/devtools:lib",
        "//executorch/devtools/bundled_program:config",
        "//executorch/devtools/bundled_program/serialize:lib",
        "//executorch/examples/models:models",
        "//executorch/extension/export_util:export_util",
    ],
)

fbcode_target(_kind = runtime.python_binary,
    name = "gen_sample_etrecord",
    srcs = ["gen_sample_etrecord.py"],
    main_function = "executorch.examples.devtools.scripts.gen_sample_etrecord.main",
    deps = [
        "//executorch/devtools:lib",
        "//executorch/devtools/etrecord:etrecord",
        "//executorch/examples/models:models",
        "//executorch/exir:lib",
    ],
)
