#
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#

"""Serialization utilities for MLX delegate."""

from executorch.backends.apple.mlx.serialization.mlx_graph_schema import (
    AddNode,
    AddScalarNode,
    ARangeNode,
    ArgmaxNode,
    CastNode,
    ConcatNode,
    ContiguousNode,
    Conv1DNode,
    DataSegment,
    DTypeId,
    ExpandDimsNode,
    FloatOrVid,
    FullNode,
    GatherNode,
    GeluNode,
    IdCopyNode,
    Instruction,
    IntOrVid,
    ItemIntNode,
    LayerNormNode,
    LinearNode,
    MLXGraph,
    MulNode,
    NamedSlot,
    NoopNode,
    OnesNode,
    QuantizedGatherNode,
    QuantizedLinearNode,
    ReshapeNode,
    RMSNormNode,
    RopeNode,
    SdpaNode,
    SiluNode,
    SliceNode,
    SliceUpdateNode,
    SlotType,
    SlotVariant,
    SymSizeNode,
    TakeAlongAxisNode,
    TensorMeta,
    Tid,
    TileNode,
    TransposeNode,
    Vid,
    ZerosNode,
)
from executorch.backends.apple.mlx.serialization.mlx_graph_serialize import (
    deserialize_to_json,
    parse_header,
    serialize_mlx_graph,
)

__all__ = [
    # Schema types
    "AddNode",
    "AddScalarNode",
    "ARangeNode",
    "ArgmaxNode",
    "CastNode",
    "ConcatNode",
    "ContiguousNode",
    "Conv1DNode",
    "DataSegment",
    "DTypeId",
    "ExpandDimsNode",
    "FloatOrVid",
    "FullNode",
    "GatherNode",
    "GeluNode",
    "IdCopyNode",
    "Instruction",
    "IntOrVid",
    "ItemIntNode",
    "LayerNormNode",
    "LinearNode",
    "MLXGraph",
    "MulNode",
    "NamedSlot",
    "NoopNode",
    "OnesNode",
    "QuantizedGatherNode",
    "QuantizedLinearNode",
    "ReshapeNode",
    "RMSNormNode",
    "RopeNode",
    "SdpaNode",
    "SiluNode",
    "SliceNode",
    "SliceUpdateNode",
    "SlotType",
    "SlotVariant",
    "SymSizeNode",
    "TakeAlongAxisNode",
    "TensorMeta",
    "Tid",
    "TileNode",
    "TransposeNode",
    "Vid",
    "ZerosNode",
    # Serialization functions
    "deserialize_to_json",
    "parse_header",
    "serialize_mlx_graph",
]
