name: apple-perf (private devices)

on:
  # TODO (huydhn): Disable the schedule run until we land the change to add device pool and device name
  # to separate between public and private iOS devices
  # schedule:
  # - cron: 0 0,4,8,12,16,20 * * *
  pull_request:
    paths:
      - .github/workflows/apple-perf-private-device-experiment.yml
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/apple-perf-private-device-experiment.yml
  # Note: GitHub has an upper limit of 10 inputs
  workflow_dispatch:
    inputs:
      models:
        description: Models to be benchmarked
        required: false
        type: string
        default: mv3,meta-llama/Llama-3.2-1B-Instruct-SpinQuant_INT4_EO8,meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8
      devices:
        description: Target devices to run benchmark
        required: false
        type: string
        default: apple_iphone_15_private
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string
  workflow_call:
    inputs:
      models:
        description: Models to be benchmarked
        required: false
        type: string
        default: mv3,meta-llama/Llama-3.2-1B-Instruct-SpinQuant_INT4_EO8,meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8
      devices:
        description: Target devices to run benchmark
        required: false
        type: string
        default: apple_iphone_15_private
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string

concurrency:
  group: apple-perf-private-devices-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  apple:
    uses: ./.github/workflows/apple-perf.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      models: ${{ inputs.models || 'mv3,meta-llama/Llama-3.2-1B-Instruct-SpinQuant_INT4_EO8,meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8' }}
      devices: apple_iphone_15_private
      benchmark_configs: ${{ inputs.benchmark_configs }}
