name: RISC-V

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/trunk/*
  pull_request:
    paths:
      - .github/workflows/riscv64.yml
      - .ci/scripts/test_riscv_qemu.sh
      - tools/cmake/preset/riscv64_linux.cmake
      - examples/riscv/**
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 2 AM PST

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  test-riscv:
    name: test-riscv
    uses: ./.github/workflows/_test_riscv.yml
    strategy:
      matrix:
        include:
          - { model: add,        xnnpack: false, quantize: false }
          - { model: add,        xnnpack: true,  quantize: false }
          - { model: mv2,        xnnpack: false, quantize: false }
          - { model: mv2,        xnnpack: true,  quantize: false }
          - { model: mv2,        xnnpack: true,  quantize: true }
          - { model: mobilebert, xnnpack: false, quantize: false }
          - { model: mobilebert, xnnpack: true,  quantize: false }
          - { model: mobilebert, xnnpack: true,  quantize: true }
          - { model: llama2,     xnnpack: false, quantize: false }
          - { model: llama2,     xnnpack: true,  quantize: false }
          - { model: llama2,     xnnpack: true,  quantize: true }
    permissions:
      id-token: write
      contents: read
    with:
      model: ${{ matrix.model }}
      xnnpack: ${{ matrix.xnnpack }}
      quantize: ${{ matrix.quantize }}
      # XNNPACK requires GCC 14+
      gcc-version: ${{ matrix.xnnpack && 14 }}
      docker-image: ${{ matrix.xnnpack && 'ci-image:executorch-ubuntu-24.04-gcc14' }}
