name: Test CUDA Backend

on:
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - release/*
    tags:
      - ciflow/nightly/*
  pull_request:
    paths:
      - .github/workflows/test-backend-cuda.yml
      - .ci/scripts/test_backend.sh
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  test-cuda:
    strategy:
      fail-fast: false
      matrix:
        suite: [models, operators]

    uses: pytorch/test-infra/.github/workflows/linux_job_v2.yml@main
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      runner: linux.g5.4xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: '12.6'
      use-custom-docker-registry: false
      submodules: recursive
      timeout: 120
      upload-artifact: test-report-cuda-${{ matrix.suite }}
      script: |
        set -eux

        source .ci/scripts/test_backend.sh "${{ matrix.suite }}" "cuda" "${RUNNER_ARTIFACT_DIR}"
