name: Test CoreML Backend

on:
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/nightly/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  test-coreml:
    uses: ./.github/workflows/_test_backend.yml
    with:
      backend: coreml
      flows: >-
        ${{ github.event_name == 'pull_request'
            && '["coreml"]'
            || '["coreml", "coreml_static_int8"]' }}
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      timeout: 120
      run-macos: true
