load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_binary,
    name = "export",
    srcs = [
        "export.py",
    ],
    main_function = "executorch.examples.portable.scripts.export.main",
    resources = {
        "//executorch/examples/models/llama/params:params": "params",
    },
    visibility = ["//executorch/..."],
    deps = [
        "//executorch/examples/models:models",
        "//executorch/extension/export_util:export_util",
    ],
)
